// 英検5級の問題データ
Object.assign(REVIEW_ARCHIVE, {
'5': {
library:[
{id:'g5-library-001',d:1,q:"I read a ___ in the library.",c:["book","shoe","carrot","chair"],a:0,e:"book は「本」。read a book で「本を読む」。"},
{id:'g5-library-002',d:1,q:"My father's sister is my ___.",c:["brother","aunt","uncle","son"],a:1,e:"お父さんの姉や妹は aunt(おば)。"},
{id:'g5-library-003',d:1,q:"A banana is a type of ___.",c:["sport","animal","fruit","room"],a:2,e:"banana(バナナ)は fruit(くだもの)の一種。"},
{id:'g5-library-004',d:1,q:"One week has seven ___.",c:["months","years","hours","days"],a:3,e:"1週間には7つの days(日)がある。"},
{id:'g5-library-005',d:1,q:"I write with a ___.",c:["pencil","sock","door","fish"],a:0,e:"pencil は「えんぴつ」。write with a pencil で「えんぴつで書く」。"},
{id:'g5-library-006',d:1,q:"We see with our ___.",c:["feet","eyes","hands","ears"],a:1,e:"eyes は「目」。耳は ears。"},
{id:'g5-library-007',d:2,q:"I am thirsty. Please give me some ___.",c:["paper","shoes","water","pencils"],a:2,e:"thirsty は「のどがかわいた」。water(水)をたのんでいる。"},
{id:'g5-library-008',d:2,q:"We eat breakfast in the ___.",c:["evening","night","afternoon","morning"],a:3,e:"breakfast は「朝ごはん」。morning は「朝」。"},
{id:'g5-library-009',d:2,q:"My mother's mother is my ___.",c:["grandmother","sister","daughter","aunt"],a:0,e:"お母さんのお母さんは grandmother(おばあさん)。"},
{id:'g5-library-010',d:2,q:"The day after Monday is ___.",c:["Sunday","Tuesday","Friday","Saturday"],a:1,e:"Monday(月曜日)の次の日は Tuesday(火曜日)。"},
{id:'g5-library-011',d:2,q:"Please ___ the door. Come in!",c:["drink","sing","open","eat"],a:2,e:"open the door で「ドアを開ける」。Come in! は「入って!」。"},
{id:'g5-library-012',d:2,q:"We play soccer with a ___.",c:["cup","book","hat","ball"],a:3,e:"サッカーには ball(ボール)を使う。"},
{id:'g5-library-013',d:3,q:"I go to school ___ bus.",c:["by","in","on","of"],a:0,e:"by bus は「バスで」。交通手段を表す。"},
{id:'g5-library-014',d:3,q:"Please listen ___ your teacher.",c:["on","to","at","in"],a:1,e:"listen to で「〜の話を聞く」。"},
{id:'g5-library-015',d:3,q:"I get ___ at seven every morning.",c:["under","of","up","to"],a:2,e:"get up は「起きる」。毎朝7時に起きる、という文。"},
{id:'g5-library-016',d:3,q:"We eat lunch ___ twelve o'clock.",c:["on","in","under","at"],a:3,e:"時刻の前には at を使う。at twelve o'clock で「12時に」。"},
{id:'g5-library-017',d:3,q:"I play tennis ___ Sundays.",c:["on","in","to","of"],a:0,e:"曜日の前には on。on Sundays は「毎週日曜日に」。"},
{id:'g5-library-018',d:3,q:"Please take ___ your shoes before you enter this room.",c:["of","off","at","to"],a:1,e:"take off your shoes は「くつをぬぐ」。"},
{id:'g5-library-019',d:1,q:"It is ___ today. Let's go swimming.",c:["rain","sun","wind","sunny"],a:3,e:"「今日は晴れです。泳ぎに行こう」。sunny は晴れた。"},
{id:'g5-library-020',d:1,q:"I'm ___. I want pizza.",c:["thirsty","sleepy","busy","hungry"],a:3,e:"「おなかがすいた。ピザが食べたい」。hungry はおなかがすいた。"},
{id:'g5-library-021',d:1,q:"Her ___ is in May.",c:["name","age","house","birthday"],a:3,e:"「彼女の誕生日は5月です」。birthday は誕生日。"},
{id:'g5-library-022',d:1,q:"Fish ___ in the river.",c:["swims","swam","swimming","swim"],a:3,e:"Fish が複数の魚のとき動詞は原形。swim は泳ぐ。"},
{id:'g5-library-023',d:1,q:"Do you ___ tennis?",c:["plays","played","playing","play"],a:3,e:"Do you のあとは動詞の原形 play。"},
{id:'g5-library-024',d:1,q:"How ___ are you?",c:["many","much","long","old"],a:3,e:"年齢を聞くときは How old。"},
{id:'g5-library-025',d:2,q:"It often ___ in June.",c:["rain","rained","raining","rains"],a:3,e:"It が主語なので rains。「6月はよく雨が降る」。"},
{id:'g5-library-026',d:2,q:"Brush your ___ after meals.",c:["tooth","tooths","teeths","teeth"],a:3,e:"歯の複数形は teeth。「食後に歯をみがきなさい」。"},
{id:'g5-library-027',d:2,q:"She is ___ a red dress.",c:["wears","wore","wear","wearing"],a:3,e:"is + wearing で「着ている」。"},
{id:'g5-library-028',d:2,q:"___ your room every week!",c:["Cleans","Cleaned","Cleaning","Clean"],a:3,e:"命令文は動詞の原形 Clean から始める。"},
{id:'g5-library-029',d:2,q:"I eat ___ at seven.",c:["lunch","dinner","supper","breakfast"],a:3,e:"朝7時に食べるのは breakfast(朝食)。"},
{id:'g5-library-030',d:2,q:"Open ___ mouth.",c:["my","his","our","your"],a:3,e:"歯医者などで「口を開けて」は Open your mouth。"},
{id:'g5-library-031',d:3,q:"What ___ flowers!",c:["beautiful","beautifully","beauty","beautify"],a:0,e:"「なんて美しい花々!」。What + 形容詞 + 複数名詞の感嘆文。beautiful は美しい。beautifully は副詞、beauty は名詞。"},
{id:'g5-library-032',d:3,q:"He ___ ten books last month.",c:["borrows","borrow","borrowing","borrowed"],a:3,e:"last month(先月)は過去。borrowed を使う。"},
{id:'g5-library-033',d:3,q:"Two ___ to Osaka, please.",c:["ticket","coins","papers","tickets"],a:3,e:"Two のあとは複数形 tickets。「大阪まで2枚ください」。"},
{id:'g5-library-034',d:3,q:"The express ___ here yesterday.",c:["stops","stop","stopping","stopped"],a:3,e:"yesterday(昨日)は過去。stopped を使う。"},
{id:'g5-library-035',d:3,q:"I like ___ apples.",c:["red big","big red","red, big","big, red"],a:1,e:"大きい赤いりんごは big red apples。size + color の順。"},
{id:'g5-library-036',d:3,q:"The test starts ___ ten.",c:["in","on","of","at"],a:3,e:"時刻の前には at。at ten は「10時に」。"}
],
school:[
{id:'g5-school-001',d:1,q:"I ___ a student.",c:["am","is","are","be"],a:0,e:"主語が I のときは am。I am a student. は「私は学生です」。"},
{id:'g5-school-002',d:1,q:"This ___ my bag.",c:["am","is","are","be"],a:1,e:"This は1つのものを指すので is を使う。"},
{id:'g5-school-003',d:1,q:"You ___ my friend.",c:["am","is","are","be"],a:2,e:"You といっしょに使う be 動詞は are。"},
{id:'g5-school-004',d:1,q:"I ___ dogs.",c:["likes","liking","am like","like"],a:3,e:"I が主語なら一般動詞はそのまま。I like dogs. で「犬が好きです」。"},
{id:'g5-school-005',d:1,q:"___ you have a pencil?",c:["Do","Does","Is","Are"],a:0,e:"一般動詞 have の質問は Do you have ...?。"},
{id:'g5-school-006',d:1,q:"This is ___ book.",c:["I","my","me","he"],a:1,e:"「私の本」は my book。my は名詞の前に置く。"},
{id:'g5-school-007',d:2,q:"She ___ tennis every day.",c:["play","playing","plays","are play"],a:2,e:"主語が She で習慣を表すので play に s をつける。"},
{id:'g5-school-008',d:2,q:"Ken ___ not like milk.",c:["do","is","are","does"],a:3,e:"Ken は三人称単数なので does not like。like は原形のまま。"},
{id:'g5-school-009',d:2,q:"My sister can ___ English.",c:["speak","speaks","speaking","to speak"],a:0,e:"can のあとは動詞の原形 speak。"},
{id:'g5-school-010',d:2,q:"___ your father a teacher?",c:["Do","Is","Are","Does"],a:1,e:"「お父さんは先生ですか」は Is your father a teacher?。"},
{id:'g5-school-011',d:2,q:"___ run in the classroom.",c:["Doesn't","Not","Don't","Isn't"],a:2,e:"Don't + 動詞の原形で「〜しないで」。"},
{id:'g5-school-012',d:2,q:"I have two ___.",c:["cat","a cat","cat's","cats"],a:3,e:"two のあとは複数形 cats。"},
{id:'g5-school-013',d:3,q:"Look! The boy has a book.",c:["have","has","are","is"],a:1,e:"「見て!男の子は本を持っています」。三人称単数なので has。"},
{id:'g5-school-014',d:3,q:"The children ___ in the park now.",c:["play","plays","played","playing"],a:0,e:"「子どもたちは今公園で遊んでいます」。They には原形 play。now は今。"},
{id:'g5-school-015',d:3,q:"___ is your bag? It is under the desk.",c:["Who","What","Where","How old"],a:2,e:"under the desk は場所。「どこ」は Where。"},
{id:'g5-school-016',d:3,q:"How many pencils ___ you have?",c:["does","are","is","do"],a:3,e:"How many pencils のあとに do you have を続ける。"},
{id:'g5-school-017',d:3,q:"This is my brother. I play with ___ every day.",c:["him","he","his","she"],a:0,e:"with のあとで「彼と」は with him。"},
{id:'g5-school-018',d:3,q:"Can she swim? Yes, she ___.",c:["does","can","is","am"],a:1,e:"Can she ...? に「はい」と答えるときは Yes, she can.。"},
{id:'g5-school-019',d:1,q:"We ___ friends.",c:["am","are","is","be"],a:1,e:"「私たちは友達です」。主語が We のときは are。"},
{id:'g5-school-020',d:1,q:"___ you busy?",c:["Is","Are","Am","Be"],a:1,e:"「あなたは忙しいですか」。You といっしょに使う be 動詞は Are。"},
{id:'g5-school-021',d:1,q:"She ___ twelve years old.",c:["is","are","am","be"],a:0,e:"She が主語のときは is。"},
{id:'g5-school-022',d:1,q:"They ___ happy.",c:["is","are","am","be"],a:1,e:"They が主語のときは are。"},
{id:'g5-school-023',d:1,q:"We ___ in the park.",c:["is","are","am","be"],a:1,e:"We が主語のときは are。"},
{id:'g5-school-024',d:1,q:"It ___ Monday today.",c:["are","is","am","be"],a:1,e:"It が主語のときは is。"},
{id:'g5-school-025',d:2,q:"He ___ soccer last Sunday.",c:["play","plays","played","playing"],a:2,e:"last Sunday(先週の日曜)は過去。played を使う。"},
{id:'g5-school-026',d:2,q:"She ___ TV yesterday evening.",c:["watch","watches","watched","watching"],a:2,e:"yesterday evening(昨日の夜)は過去。watched を使う。"},
{id:'g5-school-027',d:2,q:"I ___ to school on foot yesterday.",c:["walk","walks","walked","walking"],a:2,e:"yesterday(昨日)は過去。walked を使う。"},
{id:'g5-school-028',d:2,q:"They ___ English every day.",c:["study","studies","studied","studying"],a:0,e:"「彼らは毎日英語を勉強します」。They には原形 study。"},
{id:'g5-school-029',d:2,q:"She ___ her homework every day.",c:["do","does","did","doing"],a:1,e:"「彼女は毎日宿題をします」。She には does。"},
{id:'g5-school-030',d:2,q:"We ___ lunch at noon.",c:["eat","eats","ate","eating"],a:0,e:"「私たちは正午に昼食を食べます」。We には原形 eat。"},
{id:'g5-school-031',d:3,q:"Does she ___ a dog?",c:["has","have","had","having"],a:1,e:"Does のあとは動詞の原形 have。"},
{id:'g5-school-032',d:3,q:"Do they ___ in Osaka?",c:["lives","live","lived","living"],a:1,e:"Do のあとは動詞の原形 live。"},
{id:'g5-school-033',d:3,q:"What ___ you do last Sunday?",c:["do","does","did","doing"],a:2,e:"last Sunday(先週の日曜)は過去。did を使う。"},
{id:'g5-school-034',d:3,q:"Who ___ she?",c:["are","is","am","be"],a:1,e:"Who is she? で「彼女は誰ですか」。"},
{id:'g5-school-035',d:3,q:"___ are you from?",c:["What","Which","Who","Where"],a:3,e:"出身を聞くときは Where are you from?。"},
{id:'g5-school-036',d:3,q:"What time ___ you go to bed?",c:["What day","What color","What food","What time"],a:3,e:"時刻を聞くときは What time。"}
],
cafe:[
{id:'g5-cafe-001',d:1,q:"A: What is your name?\nB: ___",c:["My name is Yui.","I am ten.","It is red.","I like cats."],a:0,e:"名前を聞く What is your name? には My name is ... で答える。"},
{id:'g5-cafe-002',d:1,q:"A: How old are you?\nB: ___",c:["It is blue.","I am ten.","I am from Japan.","It is a pen."],a:1,e:"How old は年れいを聞く言い方。I am ten. は「10歳です」。"},
{id:'g5-cafe-003',d:1,q:"A: What color is your bag?\nB: ___",c:["It is a bag.","It is on the desk.","It is blue.","I have two."],a:2,e:"What color は色の質問。blue(青)で答える。"},
{id:'g5-cafe-004',d:1,q:"A: Do you like apples?\nB: ___",c:["Yes, I am.","Yes, it is.","Yes, I can.","Yes, I do."],a:3,e:"Do you ...? の質問には Yes, I do. と答える。"},
{id:'g5-cafe-005',d:1,q:"A: Good morning, Ken!\nB: ___",c:["Good morning, Yui!","Good night, Yui!","I am eleven.","It is a dog."],a:0,e:"朝のあいさつには Good morning. で返す。"},
{id:'g5-cafe-006',d:1,q:"A: What is this?\nB: ___",c:["I am fine.","It is a pencil.","At seven.","I am from Japan."],a:1,e:"What is this? は「これは何ですか」。ものの名前で答える。"},
{id:'g5-cafe-007',d:2,q:"A: Where do you live?\nB: ___",c:["I like music.","I am eleven.","I live in Tokyo.","It is Monday."],a:2,e:"住んでいる場所を聞かれたら I live in Tokyo. のように答える。"},
{id:'g5-cafe-008',d:2,q:"A: Can you swim?\nB: ___",c:["Yes, I do.","Yes, I am.","Yes, it is.","Yes, I can."],a:3,e:"Can you ...? には Yes, I can. と答える。"},
{id:'g5-cafe-009',d:2,q:"A: What time is it?\nB: ___",c:["It is three o'clock.","It is Friday.","It is sunny.","It is my book."],a:0,e:"What time は時刻の質問。three o'clock は「3時」。"},
{id:'g5-cafe-010',d:2,q:"A: How many cats do you have?\nB: ___",c:["They are white.","I have two cats.","I like dogs.","Under the chair."],a:1,e:"How many は数を聞く。I have two cats. は「2匹います」。"},
{id:'g5-cafe-011',d:2,q:"A: Who is that woman?\nB: ___",c:["It is a school.","It is green.","She is my mother.","I play tennis."],a:2,e:"Who は人の質問。She is my mother. は「私の母です」。"},
{id:'g5-cafe-012',d:2,q:"A: What do you eat for breakfast?\nB: ___",c:["At seven.","In the kitchen.","With my brother.","I eat bread."],a:3,e:"What do you eat は食べるものの質問。bread は「パン」。"},
{id:'g5-cafe-013',d:3,q:"A: What is your sister's name?\nB: ___",c:["Miki.","She is twelve.","She is tall.","She likes cats."],a:0,e:"「妹の名前は何ですか」「ミキです」。名前を答える。"},
{id:'g5-cafe-014',d:3,q:"A: Where is my pencil?\nB: ___",c:["It is yellow.","It is on the desk.","It is a pencil.","You have three."],a:1,e:"Where は場所の質問。on the desk は「机の上に」。"},
{id:'g5-cafe-015',d:3,q:"A: Does your brother play soccer?\nB: ___",c:["Yes, he is.","Yes, I am.","Yes, he does.","Yes, it is."],a:2,e:"Does your brother ...? には Yes, he does. と答える。"},
{id:'g5-cafe-016',d:3,q:"A: How do you go to school?\nB: ___",c:["At eight.","With my sister.","Every day.","By bus."],a:3,e:"How do you go は行き方の質問。By bus. は「バスで」。"},
{id:'g5-cafe-017',d:3,q:"A: Whose book is this?\nB: ___",c:["It is Ken's book.","It is on the table.","It is big.","It is about dogs."],a:0,e:"Whose は「だれの」。Ken's book は「ケンの本」。"},
{id:'g5-cafe-018',d:3,q:"A: Where are the children?\nB: ___",c:["In the park.","They are happy.","They like games.","They are ten."],a:0,e:"「子どもたちはどこですか」「公園です」。Where には場所で答える。"},
{id:'g5-cafe-019',d:1,q:"A: Good morning!\nB: ___",c:["Good night.","Good afternoon.","Good evening.","Good morning!"],a:3,e:"朝のあいさつには Good morning! と返す。"},
{id:'g5-cafe-020',d:1,q:"A: Thank you.\nB: ___",c:["Thank you.","Goodbye.","Hello.","You're welcome."],a:3,e:"お礼には You're welcome.(どういたしまして)と返す。"},
{id:'g5-cafe-021',d:1,q:"A: Goodbye!\nB: ___",c:["Hello.","Goodbye!","Good morning.","Thank you."],a:1,e:"別れのあいさつには Goodbye! と返す。"},
{id:'g5-cafe-022',d:1,q:"A: See you tomorrow!\nB: ___",c:["See you!","Good night.","Hello.","Thank you."],a:0,e:"See you tomorrow! には See you! と返す。"},
{id:'g5-cafe-023',d:1,q:"A: What's your name?\nB: ___",c:["Ken is here.","My name.","I am.","I'm Ken."],a:3,e:"名前を聞かれたら I'm Ken. と答える。"},
{id:'g5-cafe-024',d:1,q:"A: How old is your sister?\nB: ___",c:["She's eight.","She eight.","Eight she.","She is eight years."],a:0,e:"「妹は何歳ですか」「8歳です」。年齢は She's eight.と答える。"},
{id:'g5-cafe-025',d:2,q:"A: Where is the library?\nB: ___",c:["Library is big.","Over there is.","It library.","It's over there."],a:3,e:"場所を聞かれたら It's over there.(あそこです)と答える。"},
{id:'g5-cafe-026',d:2,q:"A: What month is it?\nB: ___",c:["It's May.","It's hot.","It's Monday.","It's spring."],a:0,e:"「今は何月ですか」「5月です」。月は It's May.と答える。"},
{id:'g5-cafe-027',d:2,q:"A: Whose pen is this?\nB: ___",c:["Pen is red.","It's pen.","Mine pen.","It's mine."],a:3,e:"誰のかを聞かれたら It's mine.(私のです)と答える。"},
{id:'g5-cafe-028',d:2,q:"A: Do you like dogs?\nB: ___",c:["Yes, I do.","I like dogs.","Dogs are cute.","I have one."],a:0,e:"「犬は好きですか」「はい」。Do you ...? に「はい」と答えるときは Yes, I do.。"},
{id:'g5-cafe-029',d:2,q:"A: Are you busy?\nB: ___",c:["Busy yes.","I busy.","No, busy.","No, I'm free."],a:3,e:"Are you ...? に「いいえ」と答えるときは No, I'm free.。"},
{id:'g5-cafe-030',d:2,q:"A: Can you run fast?\nB: ___",c:["Yes, I can.","I run daily.","Running is fun.","I like sports."],a:0,e:"「速く走れますか」「はい」。Can you ...? に「はい」と答えるときは Yes, I can.。"},
{id:'g5-cafe-031',d:3,q:"A: What do you want for lunch?\nB: ___",c:["Lunch is good.","Want curry.","Please lunch.","Curry and rice, please."],a:3,e:"食べたいものを聞かれたら Curry and rice, please. と答える。"},
{id:'g5-cafe-032',d:3,q:"A: How's the weather today?\nB: ___",c:["Weather is.","Sunny day.","It weather.","It's sunny."],a:3,e:"天気は It's sunny.(晴れです)と答える。"},
{id:'g5-cafe-033',d:3,q:"A: What day is it today?\nB: ___",c:["Day is Monday.","Monday today.","It Monday.","It's Monday."],a:3,e:"曜日は It's Monday.(月曜日です)と答える。"},
{id:'g5-cafe-034',d:3,q:"A: How many pencils do you have?\nB: ___",c:["Three pencils.","Have three.","Pencils three.","I have three."],a:3,e:"数は I have three.(3本持っています)と答える。"},
{id:'g5-cafe-035',d:3,q:"A: What color do you like?\nB: ___",c:["Blue color.","Like blue.","Color blue.","I like blue."],a:3,e:"好きな色は I like blue.(青が好きです)と答える。"},
{id:'g5-cafe-036',d:3,q:"A: Where is your school?\nB: ___",c:["Near the park.","It's big.","I like school.","For studying."],a:0,e:"「学校はどこですか」「公園の近くです」。Where には場所で答える。"},
],
station:[
{id:'g5-station-001',d:1,jp:"私はケンです。",words:["I","am","Ken"],e:"I am + 名前で「私は〜です」。"},
{id:'g5-station-002',d:1,jp:"これはペンです。",words:["This","is","a","pen"],e:"This is a pen. の順に並べる。"},
{id:'g5-station-003',d:1,jp:"私は猫が好きです。",words:["I","like","cats"],e:"I + like + 好きなものの順。"},
{id:'g5-station-004',d:1,jp:"あなたは親切です。",words:["You","are","kind"],e:"You のあとは are。kind は「親切な」。"},
{id:'g5-station-005',d:1,jp:"それは私のかばんです。",words:["That","is","my","bag"],e:"That is のあとに my bag(私のかばん)を続ける。"},
{id:'g5-station-006',d:1,jp:"私たちは友だちです。",words:["We","are","friends"],e:"We のあとは are。friends は「友だち」の複数形。"},
{id:'g5-station-007',d:2,jp:"彼女はテニスをします。",words:["She","plays","tennis"],e:"She が主語なので動詞は plays。"},
{id:'g5-station-008',d:2,jp:"私は泳ぐことができます。",words:["I","can","swim"],e:"can のあとは動詞の原形 swim。"},
{id:'g5-station-009',d:2,jp:"あなたは犬を飼っていますか。",words:["Do","you","have","a","dog"],e:"Do you have ...? で「〜を持っていますか・飼っていますか」。"},
{id:'g5-station-010',d:2,jp:"そのドアを開けなさい。",words:["Open","the","door"],e:"命令文は動詞の原形 Open から始める。"},
{id:'g5-station-011',d:2,jp:"彼は牛乳が好きではありません。",words:["He","does","not","like","milk"],e:"He does not like ... で「彼は〜が好きではない」。"},
{id:'g5-station-012',d:2,jp:"その猫はそのいすの下にいます。",words:["The cat","is","under","the chair"],e:"The cat is のあとに under the chair(いすの下に)を置く。"},
{id:'g5-station-013',d:3,jp:"彼女は本が好きです。",words:["She","likes","books"],e:"She likes books. の順。三人称単数なので likes。"},
{id:'g5-station-014',d:3,jp:"あなたはどこに住んでいますか。",words:["Where","do","you","live"],e:"Where + do + you + live の順で住んでいる場所を聞く。"},
{id:'g5-station-015',d:3,jp:"彼は英語を話せますか。",words:["Can","he","speak","English"],e:"Can + 主語 + 動詞の原形の順で「〜できますか」。"},
{id:'g5-station-016',d:3,jp:"あなたはペンを何本持っていますか。",words:["How many","pens","do","you","have"],e:"How many pens を先頭に置き、do you have を続ける。"},
{id:'g5-station-017',d:3,jp:"彼らはよくサッカーをします。",words:["They","often","play","soccer"],e:"They often play soccer. の順。often はよく。"},
{id:'g5-station-018',d:3,jp:"ここで走らないで。",words:["Don't","run","here"],e:"Don't + 動詞の原形で「〜しないで」。here は「ここで」。"}
],
park:[
{id:'g5-park-001',d:1,t:'qa',say:"I am Ken. I am ten years old.",q:"How old is Ken?",s:["Ten.","Eight.","Nine.","Eleven."],a:0,e:"ten years old = 10歳。ケンは10歳と言っている。"},
{id:'g5-park-002',d:1,t:'qa',say:"This is my bag. It is red.",q:"What color is the bag?",s:["Blue.","Red.","White.","Black."],a:1,e:"It is red. = 赤いです。かばんの色は赤。"},
{id:'g5-park-003',d:1,t:'qa',say:"I have a dog. His name is Max.",q:"What animal does the speaker have?",s:["A cat.","A bird.","A dog.","A fish."],a:2,e:"I have a dog. = 犬を飼っています。"},
{id:'g5-park-004',d:1,t:'qa',say:"My name is Yui. I like apples.",q:"What fruit does Yui like?",s:["Bananas.","Oranges.","Grapes.","Apples."],a:3,e:"I like apples. = りんごが好きです。"},
{id:'g5-park-005',d:1,t:'qa',say:"I have three pencils.",q:"How many pencils does the speaker have?",s:["Three.","One.","Two.","Four."],a:0,e:"three pencils = えんぴつ3本。"},
{id:'g5-park-006',d:1,t:'qa',say:"This is my sister. Her name is Emi.",q:"What is the sister's name?",s:["Yui.","Emi.","Miki.","Rika."],a:1,e:"Her name is Emi. = 彼女の名前はエミです。"},
{id:'g5-park-007',d:2,t:'qa',say:"Ken, can you swim? Yes, I can.",q:"What can Ken do?",s:["Cook.","Sing.","Swim.","Dance."],a:2,e:"Can you swim? Yes, I can. = 泳げますか。はい、泳げます。"},
{id:'g5-park-008',d:2,t:'qa',say:"What time do you get up, Yui? I get up at seven.",q:"What time does Yui get up?",s:["At six.","At eight.","At nine.","At seven."],a:3,e:"I get up at seven. = 7時に起きます。"},
{id:'g5-park-009',d:2,t:'qa',say:"Where is my book, Mom? It is on the desk.",q:"Where is the book?",s:["On the desk.","In the bag.","Under the chair.","On the bed."],a:0,e:"on the desk = 机の上に。本は机の上にある。"},
{id:'g5-park-010',d:2,t:'qa',say:"Do you like milk, Tom? No, I don't. I like orange juice.",q:"What drink does Tom like?",s:["Milk.","Orange juice.","Tea.","Water."],a:1,e:"I like orange juice. = オレンジジュースが好きです。"},
{id:'g5-park-011',d:2,t:'qa',say:"How do you go to school, Emi? I go by bus.",q:"How does Emi go to school?",s:["By train.","By bike.","By bus.","On foot."],a:2,e:"I go by bus. = バスで行きます。"},
{id:'g5-park-012',d:2,t:'qa',say:"What do you want, Ken? I want a red ball.",q:"What does Ken want?",s:["A red ball.","A blue pen.","A green book.","A big cake."],a:0,e:"I want a red ball. = 赤いボールがほしいです。"},
{id:'g5-park-013',d:3,t:'qa',say:"I am Miki. I have a brother. He likes soccer. I like tennis.",q:"What sport does Miki like?",s:["Tennis.","Soccer.","Baseball.","Basketball."],a:0,e:"I like tennis. = 私はテニスが好きです。サッカーが好きなのは兄弟。"},
{id:'g5-park-014',d:3,t:'qa',say:"This is my room. My bag is on the bed. My cat is under the desk.",q:"Where is the cat?",s:["On the bed.","Under the desk.","In the bag.","Under the chair."],a:1,e:"My cat is under the desk. = 私の猫は机の下にいます。"},
{id:'g5-park-015',d:3,t:'qa',say:"It is Sunday. Ken plays soccer in the park with his friends.",q:"What does Ken do on Sundays?",s:["He plays soccer.","He reads books.","He cooks dinner.","He cleans rooms."],a:0,e:"He plays soccer. = 彼はサッカーをします。"},
{id:'g5-park-016',d:3,t:'qa',say:"I am Tom. I eat breakfast at seven. I go to school at eight.",q:"What time does Tom eat breakfast?",s:["At six.","At eight.","At nine.","At seven."],a:3,e:"I eat breakfast at seven. = 7時に朝ごはんを食べます。8時は学校へ行く時刻。"},
{id:'g5-park-017',d:3,t:'qa',say:"Please open your books. Look at page ten. Read the words with me.",q:"What page does the teacher say?",s:["Page ten.","Page two.","Page five.","Page eight."],a:0,e:"Look at page ten. = 10ページを見てください。"},
{id:'g5-park-018',d:3,t:'qa',say:"I am Emi. I have two sisters. We play tennis on Saturdays. We read books on Sundays.",q:"What do Emi and her sisters do on Sundays?",s:["Play tennis.","Read books.","Play soccer.","Watch TV."],a:1,e:"We read books on Sundays. = 日曜日には本を読みます。テニスは土曜日。"}
],
flower:[
{id:'g5-flower-001',d:1,en:"What is your name?",jp:"任意の追加練習です。本番の英作文ではありません。名前を1文で書こう。架空の名前でもOK。",hints:["My name is ..."],sample:"My name is Yui.",e:"My name is + 名前で書けるよ。この問題は任意の追加練習です。"},
{id:'g5-flower-002',d:1,en:"What color do you like?",jp:"任意の追加練習です。本番の英作文ではありません。好きな色を1文で書こう。",hints:["I like ...","red / blue / green"],sample:"I like blue.",e:"I like + 色で書こう。短い1文で大丈夫。"},
{id:'g5-flower-003',d:2,en:"What food do you like?",jp:"任意の追加練習です。本番の英作文ではありません。好きな食べ物を短く書こう。",hints:["I like ...","It is good."],sample:"I like rice. It is good.",e:"I like rice. は「ごはんが好きです」。自分の好きな食べ物に変えてみよう。"},
{id:'g5-flower-004',d:2,en:"What can you do?",jp:"任意の追加練習です。本番の英作文ではありません。できることを1文で書こう。",hints:["I can ...","swim / sing / run"],sample:"I can swim.",e:"I can のあとは動詞の原形。できることを1つ書けばOK。"},
{id:'g5-flower-005',d:3,en:"What are you doing now?",jp:"任意の追加練習です。本番の英作文ではありません。今していることを1文で書こう。",hints:["I am ...","studying English / reading a book"],sample:"I am studying English.",e:"I am + 動詞の -ing 形で、今していることを書こう。"},
{id:'g5-flower-006',d:3,en:"Where is your bag?",jp:"任意の追加練習です。本番の英作文ではありません。かばんの場所を1文で書こう。想像でもOK。",hints:["My bag is ...","on the desk / under the chair"],sample:"My bag is on the desk.",e:"My bag is のあとに場所を書く。on は「〜の上に」、under は「〜の下に」。"},
{id:'g5-flower-007',d:1,en:"Who is your friend?",jp:"任意の追加練習です。本番の英作文ではありません。友だちを1文で書こう。",hints:["My friend is ..."],sample:"My friend is Ken.",e:"My friend is + 名前で書けるよ。この問題は任意の追加練習です。"},
{id:'g5-flower-008',d:1,en:"What sport do you like?",jp:"任意の追加練習です。本番の英作文ではありません。好きなスポーツを1文で書こう。",hints:["I like ..."],sample:"I like soccer.",e:"I like + スポーツで書こう。短い1文で大丈夫。"},
{id:'g5-flower-009',d:2,en:"What do you eat for breakfast?",jp:"任意の追加練習です。本番の英作文ではありません。朝ごはんを短く書こう。",hints:["I eat ..."],sample:"I eat bread and milk.",e:"I eat + 食べ物で書こう。自分の朝ごはんに変えてみよう。"},
{id:'g5-flower-010',d:2,en:"Where do you play?",jp:"任意の追加練習です。本番の英作文ではありません。遊ぶ場所を1文で書こう。",hints:["I play ...","in the park"],sample:"I play in the park.",e:"I play のあとは場所。in the park は「公園で」。"},
{id:'g5-flower-011',d:3,en:"What did you do yesterday?",jp:"任意の追加練習です。本番の英作文ではありません。昨日したことを1文で書こう。",hints:["I ...ed ...","played / watched"],sample:"I played soccer yesterday.",e:"yesterday と来たら過去形。played は play の過去形。"},
{id:'g5-flower-012',d:3,en:"What are you going to do tomorrow?",jp:"任意の追加練習です。本番の英作文ではありません。明日することを1文で書こう。",hints:["I am going to ..."],sample:"I am going to swim tomorrow.",e:"be going to + 動詞の原形で「〜する予定」。"}
]
},
});
Object.assign(QUESTION_BANKS, {
'5': {
library:REVIEW_ARCHIVE['5'].library,
school:REVIEW_ARCHIVE['5'].school,
cafe:REVIEW_ARCHIVE['5'].cafe,
 station:[],
 park:[],
 flower:REVIEW_ARCHIVE['5'].flower
},
});
Object.assign(PRACTICE_ORDER_DATA, {
'5':[
["これは赤いかばんです。",["red","is","bag","a"],[2,4,1,3],"This ",".","This is a red bag. の順。a + 色 + 名詞で「赤いかばん」。"],
["私は新しいペンを持っています。",["a","pen","have","new"],[3,1,4,2],"I ",".","I have a new pen. の順。have の後に a new pen を続ける。"],
["あなたのお兄さんは歌を歌いますか。",["your brother","Does","songs","sing"],[2,1,4,3],"","?","Does your brother sing songs? の順。Does + 主語 + 動詞の原形。sing songs は歌を歌う。"],
["その青い箱を開けてください。",["box","blue","the","open"],[4,3,2,1],"Please ",".","Please open the blue box. の順。命令文の動詞 open の後に the blue box。"],
["これは私の新しい自転車です。",["new","bike","is","my"],[3,4,1,2],"This ",".","This is my new bike. の順。my + new + bike で「私の新しい自転車」。"],
["あなたは何歳ですか。",["you","old","How","are"],[3,2,4,1],"","?","How old are you? の順。How old は年齢を聞く表現。"],
["ケンは英語を話せますか。",["speak","Ken","English","Can"],[4,2,1,3],"","?","Can Ken speak English? の順。Can + 主語 + 動詞の原形。"],
["あなたはどこに住んでいますか。",["live","do","Where","you"],[3,2,4,1],"","?","Where do you live? の順。Where の後に do you live を続ける。"],
["彼女はテニスをしますか。",["she","tennis","Does","play"],[3,1,4,2],"","?","Does she play tennis? の順。Does の後は主語と動詞の原形。"],
["ケンは牛乳が好きではありません。",["like","milk","not","does"],[4,3,1,2],"Ken ",".","Ken does not like milk. の順。does not の後は動詞の原形 like。"],
["あなたはいつ英語を勉強しますか。",["you","When","study English","do"],[2,4,1,3],"","?","When do you study English? の順。When はいつ。study English は固定のひとまとまり。"],
["あなたは犬を飼っていますか。",["have","Do","a dog","you"],[2,4,1,3],"","?","Do you have a dog? の順。Do + 主語 + have + a dog。"],
["彼らはテニスをしますか。",["tennis","Do","play","they"],[2,4,3,1],"","?","Do they play tennis? の順。Do + 主語 + 動詞の原形。"],
["彼女は本が好きです。",["likes","She","books"],[2,1,3],"",".","She likes books. の順。三人称単数なので likes。books は複数。"],
["あなたはどこで昼食を食べますか。",["you","Where","eat lunch","do"],[2,4,1,3],"","?","Where do you eat lunch? の順。Where は場所を聞く。eat lunch は固定のひとまとまり。"],
["あなたはペンを何本持っていますか。",["do","have","How many pens","you"],[3,1,4,2],"","?","How many pens do you have? の順。How many pens をまとめて先頭に置く。"],
["彼は今何を読みますか。",["read","he","What","does"],[3,4,2,1],""," now?","What does he read now? の順。Does + 主語 + 動詞の原形。now は固定の文末で「今」。"],
 ["あなたの妹はどこで英語を勉強しますか。",["your sister","Where","study English","does"],[2,4,1,3],"","?","Where does your sister study English? の順。your sister は単数なので does。"],
["私は学生です。",["am","I","student","a"],[2,1,4,3],"",".","I am a student. の順。I のあとは am。"],
["あなたはとても親切です。",["are","You","kind","very"],[2,1,4,3],"",".","You are very kind. の順。You のあとは are。"],
["これは私の本です。",["is","This","book","my"],[2,1,4,3],"",".","This is my book. の順。This のあとは is。"],
["彼は先生です。",["is","He","teacher","a"],[2,1,4,3],"",".","He is a teacher. の順。He のあとは is。"],
["私たちは仲良しです。",["are","We","friends","good"],[2,1,4,3],"",".","We are good friends. の順。We のあとは are。"],
["私は白い猫が好きです。",["like","I","cats","white"],[2,1,4,3],"",".","I like white cats. の順。like のあとは好きなもの。"],
["あなたは猫が好きですか。",["like","Do","cats","you"],[2,4,1,3],"","?","Do you like cats? の順。Do + 主語 + 動詞の原形。cats は複数。"],
["彼はサッカーが好きですか。",["like","Does","he","soccer"],[2,3,1,4],"","?","Does he like soccer? の順。Does + 主語 + 動詞の原形。"],
["あなたは英語を話しますか。",["speak","Do","you","English"],[2,3,1,4],"","?","Do you speak English? の順。Do + 主語 + 動詞の原形。"],
["彼女は毎日牛乳を飲みます。",["drinks","She","milk","every day"],[2,1,3,4],"",".","She drinks milk every day. の順。三人称単数なので drinks。"],
["あなたは犬が好きですか。",["like","Do","dogs","you"],[2,4,1,3],"","?","Do you like dogs? の順。Do + 主語 + like。"],
["あなたは兄弟がいますか。",["brothers","Do","have","you"],[2,4,3,1],"","?","Do you have brothers? の順。Do + 主語 + have + 複数名詞。"],["彼は昨日学校に来ましたか。",["come","Did","to school","he"],[2,4,1,3],""," yesterday?","Did he come to school yesterday? の順。Did + 主語 + 動詞の原形。"],
["あなたは昨日何をしましたか。",["did","What","do","you"],[2,1,4,3],""," yesterday?","What did you do yesterday? の順。did の後は do。"],
["彼女は昨夜テレビを見ました。",["watched","She","last","TV"],[2,1,4,3],""," night.","She watched TV last night. の順。watched は watch の過去形。"],
["私は昨日友達に会いました。",["met","I","friend","my"],[2,1,4,3],""," yesterday.","I met my friend yesterday. の順。met は meet の過去形。"],
["あなたは朝何を食べますか。",["eat","What","in the morning","you","do"],[2,5,4,1,3],"","?","What do you eat in the morning? の順。What + do + 主語 + 動詞。eat は食べる。"],
["彼らはよくサッカーをします。",["play","They","soccer","often"],[2,4,1,3],"",".","They often play soccer. の順。often はよく。"]
],
});
Object.assign(PRACTICE_LISTENING_DATA, {
'5':[
['response',1,[{speaker:'A',text:"Hello. How are you?"}],"",["I'm fine, thank you.","It's a pencil.","At nine o'clock."],0,"「こんにちは。元気ですか」への返事は「元気です、ありがとう」。How are you? は調子を聞くあいさつ。",'school'],
['response',1,[{speaker:'A',text:"Can I help you?"}],"",["I'm ten years old.","Yes. A notebook, please.","It's sunny today."],1,"店での「何かお探しですか」には「はい。ノートをください」。Can I help you? は店員がよく使う表現。",'shop'],
['response',2,[{speaker:'A',text:"Do you like apples?"}],"",["Yes, I do.","It's red.","Apples are big."],0,"「りんごは好きですか」「はい、大好きです」。Do you ...? への肯定の返事は Yes, I do.。",'library'],
['response',2,[{speaker:'A',text:"What do you want to eat?"}],"",["A sandwich, please.","On Sunday.","With my sister."],0,"「何を食べたいですか」「サンドイッチをください」。食べ物を聞いているので、曜日や相手ではなく食べ物を答える。",'picnic'],
['response',3,[{speaker:'A',text:"How many soccer balls do you have?"}],"",["It's black and white.","I have two.","I play on Sundays."],1,"「サッカーボールを何個持っていますか」「二つです」。How many は数の質問。",'sports'],
['response',3,[{speaker:'A',text:"Hello, this is Ann. Can I speak to Tom, please?"}],"",["It's a big phone.","I like English.","Just a minute, please."],2,"「アンです。トムと話せますか」「少々お待ちください」。電話で相手を呼ぶ間は Just a minute, please. と返す。",'phone'],
['dialogue',1,[{speaker:'A',text:"What fruit do you like, Hana?"},{speaker:'B',text:"I like oranges. How about you, Bill?"},{speaker:'A',text:"I like bananas."}],"What fruit does Hana like?",["Apples.","Oranges.","Bananas.","Grapes."],1,"「ハナ、好きな果物は？」「オレンジです。ビルは？」「バナナです」。聞かれているのはハナなので Oranges.。"],
['dialogue',1,[{speaker:'A',text:"Is this your bag, Jack?"},{speaker:'B',text:"No, that's my sister's bag. My bag is green."}],"What color is Jack's bag?",["Red.","Blue.","Green.","White."],2,"「これはあなたのかばん？」「いいえ、姉のです。僕のかばんは緑です」。Jack 自身のかばんは green。"],
['dialogue',2,[{speaker:'A',text:"Emma, where is your cat?"},{speaker:'B',text:"She's under the bed."},{speaker:'A',text:"Oh, I can see her now."}],"Where is Emma's cat?",["On the chair.","In the box.","Under the table.","Under the bed."],3,"「エマ、猫はどこ？」「ベッドの下だよ」「あ、見えた」。under the bed はベッドの下。"],
['dialogue',2,[{speaker:'A',text:"What time do you go to school, Taro?"},{speaker:'B',text:"At eight. I eat breakfast at seven."}],"What time does Taro go to school?",["At eight.","At seven.","At six.","At nine."],0,"「タロウ、何時に学校へ行く？」「8時。朝食は7時に食べる」。学校へ行く時刻は8時。"],
['dialogue',3,[{speaker:'A',text:"Do you like weekends, Lucy?"},{speaker:'B',text:"Yes. I play tennis with my sister."},{speaker:'A',text:"That's nice."}],"What does Lucy do on weekends?",["She plays tennis.","She reads books.","She cooks dinner.","She cleans rooms."],0,"「週末は好き、ルーシー？」「うん。姉とテニスをするの」。play tennis が週末の習慣。"],
['dialogue',3,[{speaker:'A',text:"Do you play tennis on Saturdays, Ben?"},{speaker:'B',text:"No, I play on Fridays. I swim on Saturdays."}],"What does Ben do on Saturdays?",["He plays tennis.","He runs in the park.","He swims.","He plays soccer."],2,"「土曜にテニスをするの？」「いいえ、金曜にします。土曜は泳ぎます」。Saturday の活動は泳ぐこと。"],
['picture',1,[],"",["The boy is eating an apple.","The boy is reading a book.","The boy is playing the piano."],1,"絵は本を開いて読んでいる男の子。「男の子は本を読んでいます」が合う。is reading a book は本を読んでいる。",'reading'],
['picture',1,[],"",["The ball is on the table.","The ball is in a box.","The ball is under the table."],2,"絵のボールはテーブルの下にある。「ボールはテーブルの下にあります」。under は〜の下に。",'ball'],
['picture',2,[],"",["There are two apples on the plate.","There are three apples on the plate.","There are two bananas on the plate."],0,"皿の上にりんごが二つある。「皿の上にりんごが二つあります」が合う。two apples はりんご二つ。",'apples'],
['picture',2,[],"",["The girl is riding a bike.","The girl is holding an umbrella.","The girl is carrying a box."],1,"女の子は雨の中で傘を持っている。「女の子は傘を持っています」。holding an umbrella は傘を持っている。",'umbrella'],
['picture',3,[],"",["The bird is on a chair.","The bird is under a bed.","The bird is in a cage."],2,"鳥は鳥かごの中にいる。「鳥はかごの中にいます」。in a cage はかごの中に。",'bird'],
 ['picture',3,[],"",["The two children are raising their hands.","The two children are washing their hands.","The two children are sleeping."],0,"二人とも両手を上げている。「二人の子どもが手を上げています」。raising their hands は手を上げている。",'raisedHands'],
 ['response',1,[{speaker:'A',text:"What is your name?"}],"",["My name is Ken.","I am ten.","Nice to meet you."],0,"「あなたの名前は何ですか」「ケンです」。What is your name? は名前を聞く言い方。",'school'],
 ['response',1,[{speaker:'A',text:"How are you?"}],"",["I'm fine.","I'm Ken.","Goodbye."],0,"「元気ですか」「元気です」。How are you? への返事は I'm fine.。",'picnic'],
 ['response',2,[{speaker:'A',text:"Where is my desk?"}],"",["It's over there.","Desk is big.","Over there."],0,"「机はどこですか」「あそこです」。Where is ...? には場所で答える。",'school'],
 ['response',2,[{speaker:'A',text:"Who is she?"}],"",["She's my sister.","Sister is kind.","She sister."],0,"「彼女は誰ですか」「妹です」。Who is ...? は人を聞く。",'library'],
 ['response',3,[{speaker:'A',text:"When is your birthday?"}],"",["It's in May.","Birthday is fun.","May birthday."],0,"「誕生日はいつですか」「5月です」。When is ...? は時期を聞く。",'shop'],
 ['response',3,[{speaker:'A',text:"What time do you get up?"}],"",["At six.","Get up early.","Six time."],0,"「何時に起きますか」「6時です」。What time は時刻を聞く。",'phone'],
 ['dialogue',1,[{speaker:'A',text:"What is this?"},{speaker:'B',text:"It's an apple."}],"What is this?",["An apple.","A pen.","A book.","A dog."],0,"「これは何」「りんごです」。This is ... の文。"],
 ['dialogue',1,[{speaker:'A',text:"Who is he?"},{speaker:'B',text:"He is my father."}],"Who is he?",["My father.","My mother.","My brother.","My teacher."],0,"「彼は誰」「父です」。He is ... の文。"],
 ['dialogue',2,[{speaker:'A',text:"Do you like milk?"},{speaker:'B',text:"No. I like orange juice."}],"What does she like?",["Milk.","Orange juice.","Tea.","Water."],1,"「牛乳は好きですか」「いいえ。オレンジジュースが好きです」。like の対象に注意。"],
 ['dialogue',2,[{speaker:'A',text:"Is your bag new?"},{speaker:'B',text:"Yes. My mother bought it yesterday."}],"Is her bag new?",["Yes, it is.","No, it is old.","Yes, yesterday.","New bag."],0,"「かばんは新しいの」「うん。母が昨日買った」。Yes で始まる返事に注意。"],
 ['dialogue',3,[{speaker:'A',text:"What did you do yesterday?"},{speaker:'B',text:"I played baseball with my brother."}],"What did he do yesterday?",["Played baseball.","Watched TV.","Played soccer.","Studied English."],0,"「昨日何をしたの」「兄と野球をした」。played baseball に注意。"],
 ['dialogue',3,[{speaker:'A',text:"Where were you last night?"},{speaker:'B',text:"I was at home."}],"Where was he last night?",["At home.","At school.","At the park.","At the shop."],0,"「昨夜どこにいたの」「家にいた」。was at home に注意。"],
 ['picture',1,[],"",["The cat is on the chair.","The cat is under the chair.","The cat is on the table."],0,"絵の猫はいすの上にいる。「猫はいすの上にいます」。on は〜の上に。",'ball'],
 ['picture',1,[],"",["A dog is running.","A dog is sleeping.","A dog is eating."],1,"絵の犬は眠っている。「犬は眠っています」。is sleeping に注意。",'bird'],
 ['picture',2,[],"",["The girl is singing a song.","The girl is dancing.","The girl is reading."],0,"絵の女の子は歌を歌っている。「女の子は歌を歌っています」。is singing に注意。",'umbrella'],
 ['picture',2,[],"",["There is one book on the desk.","There are two books on the desk.","There are three books on the desk."],1,"絵の机の上には本が2冊ある。「本が2冊あります」。There are two books に注意。",'apples'],
 ['picture',3,[],"",["The children are playing soccer.","The children are swimming.","The children are running."],0,"絵の子どもたちはサッカーをしている。「子どもたちはサッカーをしています」。are playing soccer に注意。",'raisedHands'],
 ['picture',3,[],"",["The man is wearing a hat.","The man is drinking tea.","The man is reading a newspaper."],2,"絵の男性は新聞を読んでいる。「男性は新聞を読んでいます」。is reading a newspaper に注意。",'reading']
],
});
