// 英検3級の問題データ
Object.assign(REVIEW_ARCHIVE, {
'3': {
library:[
{id:'g3-library-101',d:1,q:"I have an ___ with Dr. Brown at two o'clock.",c:["appointment","promise","dream","excuse"],a:0,e:"「ブラウン先生と2時に約束があります」。appointment は(病院などの)予約・約束。"},
{id:'g3-library-102',d:1,q:"The train ___ changed last month. Now it leaves at eight.",c:["menu","schedule","diary","letter"],a:1,e:"「電車の時刻表が先月変わりました」。schedule は時刻表・予定表。"},
{id:'g3-library-103',d:1,q:"Thank you for your ___ to the concert. I enjoyed it very much.",c:["invention","invitation","question","station"],a:1,e:"「コンサートへのご招待ありがとう。とても楽しかった」。invitation は招待。"},
{id:'g3-library-104',d:1,q:"Mina had a long ___ with her friend on the phone.",c:["conversation","celebration","collection","vacation"],a:0,e:"「ミナは友達と電話で長く話しました」。conversation は会話。"},
{id:'g3-library-105',d:1,q:"It was sunny this morning, but it ___ started to rain.",c:["loudly","suddenly","widely","nearly"],a:1,e:"「今朝は晴れていたのに、突然雨が降り出しました」。suddenly は突然に。"},
{id:'g3-library-106',d:1,q:"The ___ is terrible today. Take an umbrella.",c:["letter","dinner","weather","answer"],a:2,e:"「今日は天気がひどいです。傘を持って行きなさい」。weather は天気。"},
{id:'g3-library-107',d:2,q:"We wanted tea, but there was only coffee, so we drank coffee ___.",c:["instead","indeed","inside","alike"],a:0,e:"「紅茶が欲しかったがコーヒーしかなく、代わりにコーヒーを飲んだ」。instead は代わりに。"},
{id:'g3-library-108',d:2,q:"We must ___ for the test. Let's study together tonight.",c:["protect","prepare","promise","praise"],a:1,e:"「テストに備えなければ。今夜一緒に勉強しよう」。prepare for は〜に備える。"},
{id:'g3-library-109',d:2,q:"Don't ___ water. Turn off the tap while you brush your teeth.",c:["drop","waste","lose","burn"],a:1,e:"「水を無駄にしないで。歯を磨く間は蛇口を閉めて」。waste は無駄にする。"},
{id:'g3-library-110',d:2,q:"Exercise is part of my ___ life. I jog every morning.",c:["noisy","lucky","daily","silly"],a:2,e:"「運動は日常生活の一部です。毎朝ジョギングします」。daily life は日常生活。"},
{id:'g3-library-111',d:2,q:"My uncle moved here ___. He doesn't know the town well yet.",c:["nearly","loudly","recently","widely"],a:2,e:"「おじは最近ここに引っ越しました。まだ町をよく知りません」。recently は最近。"},
{id:'g3-library-112',d:2,q:"We must ___ nature for our children.",c:["predict","present","prefer","protect"],a:3,e:"「子どもたちのために自然を守らなければ」。protect は守る。"},
{id:'g3-library-113',d:3,q:"The doctor's ___ was very useful. I feel better now.",c:["promise","advice","dream","song"],a:1,e:"「医師の助言はとても役に立ちました。気分がよくなりました」。advice は助言(数えられない名詞)。"},
{id:'g3-library-114',d:3,q:"If you practice every day, you will ___.",c:["success","successful","successfully","succeed"],a:3,e:"「毎日練習すれば成功するでしょう」。will の後は動詞の原形 succeed。success は名詞。"},
{id:'g3-library-115',d:3,q:"To save money, we should ___ how much electricity we use.",c:["reuse","repeat","reduce","reply"],a:2,e:"「節約のため、電気の使用量を減らすべきです」。reduce は減らす。"},
{id:'g3-library-116',d:3,q:"May I ___ my friend Yuki to you?",c:["invite","invent","introduce","inform"],a:2,e:"「友達のユキを紹介してもいいですか」。introduce は紹介する。"},
{id:'g3-library-117',d:3,q:"I ___ seeing you again soon.",c:["look for","look after","look at","look forward to"],a:3,e:"「またすぐ会えるのを楽しみにしています」。look forward to + 動名詞で〜を楽しみにする。"},
 {id:'g3-library-118',d:3,q:"Each country has its own ___. We should respect them.",c:["nature","future","culture","picture"],a:2,e:"「それぞれの国には独自の文化があります。尊重すべきです」。culture は文化。"},
{id:'g3-library-119',d:1,q:"The ___ of this lake is very clean. Many birds live here.",c:["water","stone","wood","glass"],a:0,e:"「この湖の水はとてもきれいです。多くの鳥が住んでいます」。water は水。"},
{id:'g3-library-120',d:1,q:"A: What ___ you do?\nB: I'm a bus driver.",c:["do","are","is","does"],a:0,e:"「お仕事は何ですか」「バスの運転手です」。職業を聞く What do you do。"},
{id:'g3-library-121',d:1,q:"My sister practices the piano for two ___ every day.",c:["hours","weeks","years","minutes"],a:0,e:"「姉は毎日2時間ピアノを練習します」。for two hours で2時間。"},
{id:'g3-library-122',d:1,q:"The baby is sleeping. Please close the door ___.",c:["quietly","loudly","angrily","happily"],a:0,e:"「赤ちゃんが寝ています。静かにドアを閉めて」。quietly は静かに。"},
{id:'g3-library-123',d:1,q:"We had a ___ time at the park yesterday.",c:["great","bad","sad","late"],a:0,e:"「昨日は公園で楽しい時間を過ごしました」。have a great time で楽しく過ごす。"},
{id:'g3-library-124',d:1,q:"It's ___ today. The temperature is thirty-five degrees.",c:["hot","warm","cool","cold"],a:0,e:"「今日は暑いです。気温は35度です」。hot は暑い。temperature は気温。"},
{id:'g3-library-125',d:2,q:"He fell and ___ his leg during the game.",c:["hurt","helped","heard","held"],a:0,e:"「試合中に転んで足を痛めました」。hurt は痛める。helped は手伝った。"},
{id:'g3-library-126',d:2,q:"The little girl was ___ to see the fireworks.",c:["excited","bored","tired","late"],a:0,e:"「女の子は花火を見てわくわくしました」。excited はわくわくした。"},
{id:'g3-library-127',d:2,q:"The price of vegetables ___ up last month.",c:["went","came","got","took"],a:0,e:"「先月野菜の値段が上がりました」。go up で上がる。went は go の過去形。"},
{id:'g3-library-128',d:2,q:"She ___ the door open because it was hot.",c:["left","forgot","kept","stood"],a:0,e:"「暑かったのでドアを開けたままにした」。leave + 物 + 形容詞で〜を〜のままにする。"},
{id:'g3-library-129',d:2,q:"I was ___ when I heard the news.",c:["surprised","surprising","surprise","surprises"],a:0,e:"「その知らせを聞いて驚きました」。be surprised で驚く。人が主語のときは -ed。"},
{id:'g3-library-130',d:2,q:"Our team finally ___ the game.",c:["won","beat","got","lost"],a:0,e:"「うちのチームはついに試合に勝ちました」。win の過去形 won は勝った。lost は負けた。"},
{id:'g3-library-131',d:3,q:"The rules of this game are too ___ for me.",c:["complicated","simple","easy","clear"],a:0,e:"「このゲームの規則は私には複雑すぎます」。complicated は複雑な。too + 形容詞で〜すぎる。"},
{id:'g3-library-132',d:3,q:"He ___ to help me with my homework.",c:["promised","allowed","suggested","enjoyed"],a:0,e:"「彼は宿題を手伝うと約束した」。promise to do で〜すると約束する。"},
{id:'g3-library-133',d:3,q:"Smoking is ___ here. Let's go outside.",c:["prohibited","allowed","limited","shared"],a:0,e:"「ここでは喫煙は禁止です。外へ行きましょう」。prohibit は禁じる。allowed は許可された。"},
{id:'g3-library-134',d:3,q:"He is ___ enough to swim across the river.",c:["strong","weak","tall","short"],a:0,e:"「彼は川を泳いで渡れるほど強い」。strong enough to で〜するほど強い。"},
{id:'g3-library-135',d:3,q:"She ___ a cure for the disease.",c:["discovered","invented","drew","broke"],a:0,e:"「彼女はその病気の治療法を発見した」。discover は発見する。disease は病気。"},
{id:'g3-library-136',d:3,q:"The game was ___ because of rain.",c:["postponed","canceled","continued","started"],a:0,e:"「試合は雨のため延期された」。postpone は延期する。because of + 名詞で〜のために。"}
],
school:[
{id:'g3-school-101',d:1,q:"This watch ___ in Japan.",c:["made","is made","makes","making"],a:1,e:"「この時計は日本で作られています」。is made で受動態(作られる)ことを表す。"},
{id:'g3-school-102',d:1,q:"I have never ___ such a big fish.",c:["seeing","saw","see","seen"],a:3,e:"「こんなに大きな魚は見たことがありません」。have never + 過去分詞で〜したことがない。"},
{id:'g3-school-103',d:1,q:"The boy ___ is playing the piano is my brother.",c:["which","who","whose","whom"],a:1,e:"「ピアノを弾いている男の子は私の弟です」。人を説明する関係代名詞は who。"},
{id:'g3-school-104',d:1,q:"They enjoyed ___ baseball last Sunday.",c:["play","to play","played","playing"],a:3,e:"「彼らは先週の日曜日野球を楽しみました」。enjoy の後は動名詞 playing。"},
{id:'g3-school-105',d:1,q:"You must ___ your hands before lunch.",c:["washes","washed","wash","washing"],a:2,e:"「昼食の前に手を洗いなさい」。must の後は動詞の原形 wash。"},
{id:'g3-school-106',d:1,q:"My bag is ___ than yours.",c:["heavy","heaviest","heavier","more heavy"],a:2,e:"「私のかばんはあなたのより重い」。than と比べるので比較級 heavier。"},
{id:'g3-school-107',d:2,q:"How long ___ you lived in Osaka?",c:["have","has","did","do"],a:0,e:"「大阪にどのくらい住んでいますか」。How long have you lived で期間を聞く。you には have。"},
{id:'g3-school-108',d:2,q:"This bridge ___ in 1990.",c:["built","is built","was built","has built"],a:2,e:"「この橋は1990年に建てられました」。過去の受動態は was built。"},
{id:'g3-school-109',d:2,q:"I lost the pen ___ my father gave me.",c:["who","which","whose","whom"],a:1,e:"「父がくれたペンをなくしました」。物を説明する関係代名詞は which。"},
{id:'g3-school-110',d:2,q:"I look forward to ___ you at the party.",c:["see","to see","seen","seeing"],a:3,e:"「パーティーで会えるのを楽しみにしています」。look forward to の後は動名詞 seeing。"},
{id:'g3-school-111',d:2,q:"He is too young ___ alone.",c:["travel","traveling","to travel","traveled"],a:2,e:"「彼は若すぎて一人旅できない」。too + 形容詞 + to で〜するには…すぎる。"},
{id:'g3-school-112',d:2,q:"If it ___ tomorrow, we will stay home.",c:["rain","rains","will rain","rained"],a:1,e:"「明日雨なら家にいます」。if の中は現在形で未来を表す。三人称単数なので rains。"},
{id:'g3-school-113',d:3,q:"She has lived here ___ 2015.",c:["for","from","at","since"],a:3,e:"「彼女は2015年からここに住んでいます」。起点を表す since + 年。"},
{id:'g3-school-114',d:3,q:"Can you tell me ___ to get to the station?",c:["which","how","what","where"],a:1,e:"「駅への行き方を教えてくれますか」。how to で〜の方法。"},
{id:'g3-school-115',d:3,q:"The test was ___ difficult that I couldn't finish it.",c:["very","too","so","such"],a:2,e:"「テストは難しすぎて終えられなかった」。so + 形容詞 + that でとても〜なので…。"},
{id:'g3-school-116',d:3,q:"English is ___ in many countries.",c:["spoke","speaks","spoken","speaking"],a:2,e:"「英語は多くの国で話されています」。is spoken で受動態。"},
{id:'g3-school-117',d:3,q:"I ___ study late last night.",c:["have to","has to","had to","must"],a:2,e:"「昨夜は遅くまで勉強しなければなりませんでした」。過去の must は had to。"},
 {id:'g3-school-118',d:3,q:"Mt. Fuji is higher than any ___ mountain in Japan.",c:["others","another","other","else"],a:2,e:"「富士山は日本の他のどの山より高い」。any other + 単数名詞。"},
{id:'g3-school-119',d:1,q:"I ___ my key. I can't open the door.",c:["lose","loses","lost","losing"],a:2,e:"「鍵をなくしました。ドアが開けられません」。すでになくしたので過去形 lost。"},
{id:'g3-school-120',d:1,q:"She ___ a letter to her friend now.",c:["writes","wrote","is writing","write"],a:2,e:"「彼女は今友達に手紙を書いています」。now があるので現在進行形 is writing。"},
{id:'g3-school-121',d:1,q:"They ___ to school on foot every day.",c:["walk","walks","walked","walking"],a:0,e:"「彼らは毎日歩いて通学します」。They には原形 walk。every day で習慣。"},
{id:'g3-school-122',d:1,q:"There ___ a new bookstore near my house.",c:["is","are","was","were"],a:0,e:"「家の近くに新しい本屋があります」。a new bookstore と単数なので is。"},
{id:'g3-school-123',d:1,q:"He ___ TV when his mother came home.",c:["watches","watched","was watching","is watching"],a:2,e:"「母が帰宅したとき彼はテレビを見ていました」。そのとき進行中は was watching。"},
{id:'g3-school-124',d:1,q:"We ___ dinner at seven yesterday.",c:["have","has","had","having"],a:2,e:"「昨日7時に夕食を食べました」。yesterday で過去の話なので had。"},
{id:'g3-school-125',d:2,q:"I have ___ to London twice.",c:["been","gone","went","go"],a:0,e:"「ロンドンへ2回行ったことがあります」。have been to で〜へ行ったことがある。twice は2回。"},
{id:'g3-school-126',d:2,q:"This is the movie ___ everyone is talking about.",c:["who","that","whose","where"],a:1,e:"「これはみんなが話題にしている映画です」。物を説明する関係代名詞は that。"},
{id:'g3-school-127',d:2,q:"She asked me ___ her with math.",c:["help","helping","to help","helped"],a:2,e:"「彼女は数学を手伝うよう私に頼んだ」。ask 人 to do で人に〜するよう頼む。"},
{id:'g3-school-128',d:2,q:"He is interested ___ collecting stamps.",c:["in","on","at","for"],a:0,e:"「彼は切手集めに興味があります」。be interested in で〜に興味がある。"},
{id:'g3-school-129',d:2,q:"The room was so dark that we ___ see nothing.",c:["can","could","must","should"],a:1,e:"「部屋は暗くて何も見えませんでした」。過去の話なので could。see nothing で何も見えない。"},
{id:'g3-school-130',d:2,q:"It has ___ raining since morning.",c:["been","being","be","is"],a:0,e:"「朝からずっと雨が降っています」。has been raining で降り続けている。since は〜以来。"},
{id:'g3-school-131',d:3,q:"They ___ TV every night.",c:["watch","watches","watched","watching"],a:0,e:"「彼らは毎晩テレビを見ます」。They には原形 watch。"},
{id:'g3-school-132',d:3,q:"She speaks English as ___ as Ken.",c:["fluently","fluent","fluency","more fluently"],a:0,e:"「彼女はケンと同じくらい流ちょうに英語を話す」。as + 副詞 + as の形。fluently は流ちょうに。"},
{id:'g3-school-133',d:3,q:"The longer you wait, ___ worse it gets.",c:["the","a","so","very"],a:0,e:"「待てば待つほど悪くなる」。The 比較級 + 主語 + 動詞, the 比較級 の形。"},
{id:'g3-school-134',d:3,q:"I ___ busy yesterday.",c:["am","is","was","were"],a:2,e:"「昨日は忙しかった」。yesterday で過去の話なので was。"},
{id:'g3-school-135',d:3,q:"We ___ tired after the game.",c:["am","is","are","were"],a:3,e:"「試合の後は疲れた」。We には were。after the game は試合の後。"},
{id:'g3-school-136',d:3,q:"He talks as if he ___ everything.",c:["knows","knew","known","know"],a:1,e:"「彼は何でも知っているかのように話す」。as if の後は過去形 knew。実際は知らない。"}
],
cafe:[
{id:'g3-cafe-101',d:1,q:"A: Would you like to come to my birthday party on Sunday?\nB: ___",c:["Sure, I'd love to.","I went there yesterday.","It's my birthday.","At three o'clock."],a:0,e:"「日曜の誕生日会に来ませんか」「ぜひ行きたいです」。誘いへの返事は Sure, I'd love to.。"},
{id:'g3-cafe-102',d:1,q:"A: Hello, this is Yuki. May I speak to Ken?\nB: ___",c:["Just a moment, please.","Nice to meet you.","I'm fine, thank you.","Good night."],a:0,e:"「ユキです。ケンと話せますか」「少々お待ちください」。電話の取次ぎは Just a moment, please.。"},
{id:'g3-cafe-103',d:1,q:"A: How much is this T-shirt?\nB: ___",c:["It's red.","It's new.","It's 2,000 yen.","It's mine."],a:2,e:"「このTシャツはいくらですか」「2,000円です」。How much は値段を聞く。"},
{id:'g3-cafe-104',d:1,q:"A: You look tired. Shall I carry your bag?\nB: ___",c:["That's very kind of you.","I'm tired.","It's heavy.","Carry this."],a:0,e:"「疲れているようですね。かばんを持ちましょうか」「ご親切にありがとう」。申し出へのお礼は That's very kind of you.。"},
{id:'g3-cafe-105',d:1,q:"A: Excuse me. Where is the post office?\nB: ___",c:["It's two o'clock.","I went there.","Very far.","Go straight for two blocks."],a:3,e:"「郵便局はどこですか」「2ブロックまっすぐ行ってください」。道順を答える。"},
{id:'g3-cafe-106',d:1,q:"A: It will rain tomorrow. What shall we do?\nB: ___",c:["Let's play tennis.","Let's swim.","Let's visit the museum.","Let's play baseball."],a:2,e:"「明日は雨です。どうしましょう」「博物館へ行こう」。雨の日に合うのは博物館。"},
{id:'g3-cafe-107',d:2,q:"A: I'm free this Sunday. What shall we do?\nB: ___",c:["We are free.","Sunday is fun.","Why don't we go fishing?","I like Sundays."],a:2,e:"「今週の日曜は空いています。何をしよう」「釣りに行くのはどう」。提案は Why don't we ...?。"},
{id:'g3-cafe-108',d:2,q:"A: Are you ready to order?\nB: ___",c:["I cooked curry yesterday.","My mother likes curry.","Yes. I'll have curry and rice.","Curry comes from India."],a:2,e:"「ご注文はお決まりですか」「はい。カレーとごはんをください」。注文は I'll have ... で伝える。"},
{id:'g3-cafe-109',d:2,q:"A: Could you take a picture of us?\nB: ___",c:["I like pictures.","This is a camera.","Sure. Say cheese!","We are three."],a:2,e:"「写真を撮ってもらえますか」「もちろん。はいチーズ!」。依頼への返事は Sure.。"},
{id:'g3-cafe-110',d:2,q:"A: I'm sorry I'm late. The bus was late.\nB: ___",c:["You are late.","The bus is late.","Hurry up.","That's all right."],a:3,e:"「遅れてごめんなさい。バスが遅れて」「大丈夫ですよ」。謝罪への返事は That's all right.。"},
{id:'g3-cafe-111',d:2,q:"A: What's the matter? You look pale.\nB: ___",c:["I have a stomachache.","I'm very happy.","I won the game.","I love summer."],a:0,e:"「どうしたの。顔色が悪いよ」「おなかが痛いんだ」。pale は青白い。体調不良を答える。"},
{id:'g3-cafe-112',d:2,q:"A: How are you going to Hokkaido in winter?\nB: ___",c:["In winter.","Hokkaido is cold.","By plane.","I like trips."],a:2,e:"「冬にどうやって北海道へ行くの」「飛行機で」。交通手段を答える。"},
{id:'g3-cafe-113',d:3,q:"A: Which do you like better, the red sweater or the blue one?\nB: ___",c:["I like sweaters.","Red and blue.","The blue is blue.","I prefer the blue one."],a:3,e:"「赤と青のセーター、どちらが好き」「青の方が好きです」。prefer は〜を好む。"},
{id:'g3-cafe-114',d:3,q:"A: May I use your pen?\nB: ___",c:["It's my pen.","Use it yesterday.","Pens are useful.","Of course. Here you are."],a:3,e:"「ペンを使ってもいいですか」「もちろん。どうぞ」。許可は Of course.。"},
{id:'g3-cafe-115',d:3,q:"A: What will you do after you graduate from high school?\nB: ___",c:["I graduated yesterday.","High school is fun.","I like studying.","I'll study abroad in Canada."],a:3,e:"「高校を卒業したら何をしますか」「カナダに留学します」。未来の予定を答える。"},
{id:'g3-cafe-116',d:3,q:"A: This camera doesn't work. I bought it here yesterday.\nB: ___",c:["It works well.","Cameras are expensive.","I like this shop.","I'm sorry. We'll fix it right away."],a:3,e:"「このカメラは動きません。昨日ここで買いました」「申し訳ありません。すぐ修理します」。店員の対応は謝罪から。"},
{id:'g3-cafe-117',d:3,q:"A: Can you come to my house on Saturday?\nB: ___",c:["Yes, I like houses.","Saturday is Saturday.","I live near you.","I'm sorry, I have to visit my grandmother."],a:3,e:"「土曜にうちに来られますか」「ごめんなさい。祖母を訪ねないと」。断りは I'm sorry から。"},
 {id:'g3-cafe-118',d:3,q:"A: I can't sleep well these days. What should I do?\nB: ___",c:["Sleep is important.","I sleep well.","Good night.","Why don't you drink warm milk before bed?"],a:3,e:"「最近よく眠れません。どうすればいい」「寝る前に温かい牛乳を飲むのはどう」。助言は Why don't you ...?。"},
{id:'g3-cafe-119',d:1,q:"A: What did you eat for breakfast?\nB: ___",c:["Toast and eggs.","At seven.","With my mother.","It was good."],a:0,e:"「朝食に何を食べましたか」「トーストと卵です」。食べ物を答える。"},
{id:'g3-cafe-120',d:1,q:"A: Where were you last night?\nB: ___",c:["At home.","For three hours.","With dinner.","It was fun."],a:0,e:"「昨夜はどこにいましたか」「家にいました」。Where には場所で答える。"},
{id:'g3-cafe-121',d:1,q:"A: Do you like cats or dogs?\nB: ___",c:["I like dogs better.","Yes, I have one.","No, they're cute.","I like animals."],a:0,e:"「猫と犬、どちらが好き」「犬の方が好き」。A or B には好きな方を答える。"},
{id:'g3-cafe-122',d:1,q:"A: What color do you want?\nB: ___",c:["Blue, please.","A big one.","Two, please.","It is nice."],a:0,e:"「何色がいいですか」「青をお願いします」。色を答える。"},
{id:'g3-cafe-123',d:1,q:"A: Can I help you?\nB: ___",c:["Yes. I'm looking for a gift.","I came by car.","It's over there.","I like shopping."],a:0,e:"「何かお探しですか」「はい。贈り物を探しています」。店での声かけへの返事。"},
{id:'g3-cafe-124',d:1,q:"A: How do you come here?\nB: ___",c:["By train.","For an hour.","At nine.","With my bag."],a:0,e:"「どうやってここへ来ますか」「電車で」。手段は By train。"},
{id:'g3-cafe-125',d:2,q:"A: What's wrong with your bike?\nB: ___",c:["The tire is flat.","It's red.","I ride it daily.","My brother has one."],a:0,e:"「自転車はどうしたの」「タイヤがパンクしたんだ」。What's wrong はどうしたの。flat はパンクした。"},
{id:'g3-cafe-126',d:2,q:"A: How long have you studied English?\nB: ___",c:["For three years.","Three years ago.","Since I like it.","Every day."],a:0,e:"「どのくらい英語を勉強していますか」「3年間です」。期間は For three years。"},
{id:'g3-cafe-127',d:2,q:"A: Could I have the bill, please?\nB: ___",c:["Here you are.","Thank you for coming.","Enjoy your meal.","Welcome back."],a:0,e:"「お会計をお願いします」「はい、どうぞ」。bill は勘定書。Here you are で渡す。"},
{id:'g3-cafe-128',d:2,q:"A: What kind of music do you like?\nB: ___",c:["I like quiet music.","I like concerts.","I play well.","My friend sings."],a:0,e:"「どんな音楽が好きですか」「静かな音楽が好きです」。What kind of はどんな種類の。"},
{id:'g3-cafe-129',d:2,q:"A: Shall we go for a walk?\nB: ___",c:["That's a good idea.","I walk fast.","We went far.","It's a park."],a:0,e:"「散歩に行きましょうか」「いい考えですね」。誘いへの賛成は That's a good idea。"},
{id:'g3-cafe-130',d:2,q:"A: Do you know what time it is?\nB: ___",c:["It's half past three.","It's time to go.","I have a watch.","Time flies."],a:0,e:"「今何時か分かりますか」「3時半です」。時刻は It's half past three。"},
{id:'g3-cafe-131',d:3,q:"A: I have a headache and a fever.\nB: ___",c:["You should see a doctor.","You are healthy.","I like hospitals.","Take a walk."],a:0,e:"「頭痛と熱があります」「医者にみてもらうべきです」。助言は You should ...。"},
{id:'g3-cafe-132',d:3,q:"A: Can I return this book tomorrow?\nB: ___",c:["Yes, that's fine.","Yes, it's new.","No, it's old.","No, I like it."],a:0,e:"「明日この本を返してもいいですか」「はい、大丈夫です」。許可は Yes, that's fine。"},
{id:'g3-cafe-133',d:3,q:"A: What do you think of my new haircut?\nB: ___",c:["It looks great on you.","It was expensive.","I cut it myself.","It grows fast."],a:0,e:"「新しい髪型はどう」「とても似合っているよ」。感想を聞かれたらほめる。looks great で素敵に見える。"},
{id:'g3-cafe-134',d:3,q:"A: I'm worried about tomorrow's test.\nB: ___",c:["You'll do fine.","I like tests.","Tests are hard.","Don't study."],a:0,e:"「明日のテストが心配です」「きっとうまくいくよ」。励ましは You'll do fine。"},
{id:'g3-cafe-135',d:3,q:"A: Is this seat taken?\nB: ___",c:["No, go ahead.","Yes, I'm eating.","No, it's mine.","Yes, I like trains."],a:0,e:"「この席は空いていますか」「どうぞ」。空いていることは No, go ahead。taken は使用中の。"},
{id:'g3-cafe-136',d:3,q:"A: Thank you for your help.\nB: ___",c:["You're welcome.","I'm sorry.","Good luck.","Take care."],a:0,e:"「手伝ってくれてありがとう」「どういたしまして」。お礼には You're welcome。"}
],
station:[],
park:[],
flower:[],
essay:[
{id:'g3-essay-101',d:1,kind:'writing',en:"Do you think students should study English every day?",points:["communication","future","fun"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think students should study English every day. First, English helps them talk with people around the world. Second, it will be useful for their future jobs. Also, studying a little every day is fun.",e:"I think ... で考えを書き、First, ... Second, ... で理由を2つ書くのが3級英作文の基本形。"},
{id:'g3-essay-102',d:1,kind:'writing',en:"Do you think it is good for children to have a pet?",points:["happy","responsibility","family"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think it is good for children to have a pet. First, pets make children happy every day. Second, taking care of a pet teaches responsibility. Also, pets make the family closer.",e:"理由は観点(POINTS)に沿って2つ書こう。taking care of ... で〜の世話をすること。"},
{id:'g3-essay-103',d:2,kind:'writing',en:"Which do you like better, summer or winter?",points:["weather","activities","food"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like summer better than winter. First, the weather is warm and I can swim. Second, I can enjoy many outdoor activities with my friends. Also, summer food like ice cream is delicious.",e:"Which do you like better ...? には I like ... better ... で答え、理由を2つ続ける。"},
{id:'g3-essay-104',d:2,kind:'writing',en:"Do you want to live in a big city in the future?",points:["convenient","jobs","nature"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I want to ...","First, ...","Second, ..."],sample:"I want to live in a big city in the future. First, big cities are convenient because there are many shops and stations. Second, I can find an interesting job there. However, I know there is little nature.",e:"I want to ... で希望を書き、because で理由をつなげると説得力が増す。"},
{id:'g3-essay-105',d:3,kind:'writing',en:"Do you think children should help with housework?",points:["family","skill","time"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think children should help with housework. First, helping is good for the family. Second, they can learn important life skills. Also, working together saves everyone's time.",e:"should で〜すべきという意見を表す。life skills は生活の技能。"},
{id:'g3-essay-106',d:3,kind:'writing',en:"Which do you like better, reading books or watching TV?",points:["learning","fun","time"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like reading books better than watching TV. First, I can learn many new things from books. Second, reading is quiet and fun. Also, I can enjoy books any time I want.",e:"動名詞を主語にした I like reading ... better ... の形に注意。any time でいつでも。"},
{id:'g3-essay-107',d:1,kind:'writing',en:"Do you like spring best of all the seasons?",points:["flowers","weather","trip"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["Yes, I like ... best ...","First, ...","Second, ..."],sample:"Yes, I like spring best of all the seasons. First, many beautiful flowers bloom in spring. Second, the weather is warm and nice. Also, we can enjoy school trips in spring.",e:"Yes, I like ... best ... でいちばん好きと書き、First, ... Second, ... で理由を2つ。bloom は咲く。"},
{id:'g3-essay-108',d:1,kind:'writing',en:"Do you think breakfast is important?",points:["energy","health","morning"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think breakfast is important. First, it gives me energy for the morning. Second, eating breakfast every day is good for my health. Also, I can enjoy many kinds of food.",e:"I think ... で考えを書き、First, ... Second, ... で理由を2つ。energy は力、health は健康。"},
{id:'g3-essay-109',d:1,kind:'writing',en:"Which do you like better, dogs or cats?",points:["cute","friendly","fun"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like dogs better than cats. First, dogs are friendly and cute. Second, I can play outside with them. Also, dogs always welcome me when I come home.",e:"I like A better than B の形に注意。friendly は人なつこい、welcome は迎える。"},
{id:'g3-essay-110',d:1,kind:'writing',en:"Do you want to visit a foreign country in the future?",points:["food","culture","language"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["Yes, I want to ...","First, ...","Second, ..."],sample:"Yes, I want to visit a foreign country in the future. First, I want to eat food from many countries. Second, I want to learn about other cultures. Also, I can use English there.",e:"want to visit で訪れたい。culture は文化。foreign country は外国。"},
{id:'g3-essay-111',d:1,kind:'writing',en:"Do you think it is fun to cook?",points:["family","food","skill"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think it is fun to cook. First, I can make food for my family. Second, cooking new dishes is exciting. Also, I learn many cooking skills.",e:"it is fun to cook で料理するのは楽しい。dish は料理、skill は技術。"},
{id:'g3-essay-112',d:1,kind:'writing',en:"Which season do you like better, spring or fall?",points:["weather","food","events"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like fall better than spring. First, the weather is cool and nice. Second, I can eat delicious fruits like apples and grapes. Also, there are many school events in fall.",e:"fall は秋(autumn とも言う)。delicious はおいしい。like apples で〜のような。"},
{id:'g3-essay-113',d:2,kind:'writing',en:"Do you think students should read newspapers?",points:["news","study","world"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think students should read newspapers. First, they can learn news about the world. Second, reading helps them study many subjects. Also, they can talk about news with friends.",e:"should read で読むべき。subject は教科。news は形が複数でも単数扱い。"},
{id:'g3-essay-114',d:2,kind:'writing',en:"Which do you like better, living in the city or living in the countryside?",points:["nature","shops","friends"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like living in the countryside better than living in the city. First, nature is beautiful and the air is clean. Second, I can play outside with my friends. Also, it is quiet at night.",e:"living in ... で〜に住むこと。countryside は田舎。air は空気。"},
{id:'g3-essay-115',d:2,kind:'writing',en:"Do you want to learn to play an instrument?",points:["music","friends","fun"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["Yes, I want to ...","First, ...","Second, ..."],sample:"Yes, I want to learn to play the piano. First, I love music very much. Second, I can play with my friends at school. Also, playing the piano is relaxing.",e:"want to learn to play で演奏を習いたい。instrument は楽器。relaxing はゆったりする。"},
{id:'g3-essay-116',d:2,kind:'writing',en:"Do you think children should use smartphones?",points:["study","family","danger"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think children should use smartphones carefully. First, they are useful for studying. Second, children can call their family any time. But they should not use them too long.",e:"carefully は注意深く。useful は役に立つ。too long は長すぎ。"},
{id:'g3-essay-117',d:2,kind:'writing',en:"Which do you like better, playing sports or watching sports?",points:["health","team","friends"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like playing sports better than watching sports. First, playing sports is good for my health. Second, I can make friends on a team. Also, winning a game feels great.",e:"playing と watching の対比に注意。team はチーム。feels great は最高の気分。"},
{id:'g3-essay-118',d:2,kind:'writing',en:"Do you think it is good to travel by train?",points:["scenery","cheap","safe"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think it is good to travel by train. First, I can enjoy beautiful scenery from the window. Second, trains are safe and usually on time. Also, tickets are not expensive.",e:"travel by train で電車で旅行する。scenery は景色。on time は時間通り。"},
{id:'g3-essay-119',d:3,kind:'writing',en:"Do you think schools should have longer summer vacations?",points:["trip","family","rest"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think schools should have longer summer vacations. First, students can enjoy long trips with their families. Second, they can rest well and study at their own pace. Also, summer is the best season for outdoor fun.",e:"longer summer vacations でより長い夏休み。at their own pace で自分のペースで。outdoor は屋外の。"},
{id:'g3-essay-120',d:3,kind:'writing',en:"Which is more important to you, money or time?",points:["family","life","money"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ... is more important ...","First, ...","Second, ..."],sample:"I think time is more important than money. First, lost time never comes back. Second, I want to spend time with my family. Money is useful, but time with people I love is special.",e:"more important than で〜より大切。never comes back で二度と戻らない。special は特別な。"},
{id:'g3-essay-121',d:3,kind:'writing',en:"Do you think people should eat less meat?",points:["health","animals","earth"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think people should eat less meat. First, eating too much meat is not good for our health. Second, raising animals uses a lot of water and land. Also, vegetables and fish are delicious and healthy.",e:"less meat で肉を少なめに。raising animals は動物を育てること。a lot of でたくさんの。"},
{id:'g3-essay-122',d:3,kind:'writing',en:"Which do you like better, watching movies at home or at the theater?",points:["screen","sound","family"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I like ... better ...","First, ...","Second, ..."],sample:"I like watching movies at the theater better than at home. First, the screen is big and the sound is great. Second, I feel excited with many people. Also, eating popcorn there is special fun.",e:"theater は映画館。screen は画面、sound は音。excited はわくわくした。"},
{id:'g3-essay-123',d:3,kind:'writing',en:"Do you think robots will do housework in the future?",points:["family","time","help"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ...","First, ...","Second, ..."],sample:"I think robots will do housework in the future. First, they can clean rooms and wash dishes. Second, families will have more free time. Also, old people living alone will get good help.",e:"will do で〜するようになる。housework は家事。living alone は一人暮らしの。"},
{id:'g3-essay-124',d:3,kind:'writing',en:"Which is better for the earth, bikes or cars?",points:["air","health","earth"],jp:"あなたの考えとその理由を2つ、25〜50語の英語で書こう。",hints:["I think ... are better ...","First, ...","Second, ..."],sample:"I think bikes are better for the earth than cars. First, bikes do not make the air dirty. Second, riding bikes is good exercise. Also, bikes are quiet and need little space.",e:"for the earth で地球のために。make the air dirty で空気を汚す。little space で狭い場所。"}
]
}
,
});
Object.assign(PRACTICE_PASSAGES, {
'g3-reading-notice-1':"Basketball Club Tryouts\nDo you want to play basketball? Our team is looking for new players. Tryouts are on Friday afternoon at the school gym. Please bring sports shoes and a towel. You do not need a ball. The team practices twice a week. If you have questions, ask Mr. Sato in Room Two.",
'g3-reading-notice-2':"Christmas Concert\nThe school music club will have a Christmas concert on December twentieth. It starts at six in the evening in the school hall. The club members have practiced many songs since October. Tickets are free, but you need one to enter. You can get a ticket at the school office. Small children must come with their parents.",
'g3-reading-email-1':"Hi Ken,\nThank you for your letter. I was happy to hear that you won the speech contest. You practiced hard for a month, so I am not surprised.\nOur family moved to a new house last week. It is bigger than our old house, and I have my own room now. There is a park near our house. I often play soccer there with my new friends.\nPlease come and visit us soon.\nYuki",
'g3-reading-email-2':"Dear Ms. Green,\nI am sorry I was absent from your class yesterday. I had a bad cold and stayed home all day. My mother took me to the hospital in the morning. The doctor gave me some medicine and told me to rest for two days.\nI missed the English test. Can I take it next week? Please tell me what I should study.\nThank you,\nTaro",
'g3-reading-story-1':"Last summer, Riku visited his grandmother in the countryside. She lives alone in a small house near the sea. Every morning, Riku helped her carry water from the well. In the afternoon, they walked on the beach and looked for shells.\nOne day, Riku found a small black dog near the house. It was hungry, so he gave it some bread. The dog came back the next day, too. Soon it came every day.\nWhen summer ended, Riku had to go home. He was sad to leave the dog. His grandmother smiled and said, \"Don't worry. I will take care of it.\" Now the dog lives with his grandmother.",
'g3-reading-story-2':"Mia has kept a diary since she was ten. She writes about interesting things every night. Last month, something surprising happened.\nMia was walking home from school when she saw an old wallet on the road. There were some bills and a card in it. She took it to the police station near her house. The officer thanked her and asked for her name and address.\nA week later, Mia got a letter. It was from the man who lost the wallet. He wrote, \"Thank you very much. You are an honest girl.\" Mia was very happy. She wrote about the letter in her diary that night.",
'g3-reading-notice-3':"Swimming Club Members Wanted\nDo you like swimming? Our swimming club is looking for new members. We practice every Tuesday and Friday afternoon at the town pool. You need swimming clothes and a towel. You do not need goggles. If you want to join, please talk to Ms. Kato in Room Five.",
'g3-reading-email-3':"Hi Aya,\nThank you for coming to my house last Sunday. I enjoyed playing cards with you. My sister's birthday is next month. We will have a small party at home. It will start at three on Saturday afternoon. Can you come? My sister likes you very much. Please write back soon.\nYour friend,\nSaki",
'g3-reading-email-4':"Hi Ken,\nI went to my grandmother's house last weekend. She lives in the mountains. We picked mushrooms together on Saturday morning. In the afternoon, we made jam from the grapes in her garden. It was sweet and delicious. My grandmother is eighty years old, but she is very strong. Please visit her with me next time.\nYuki",
'g3-reading-story-3':"Last spring, Takeshi found a small black cat in the park. It was crying under a bench. Takeshi gave the cat some milk from his lunch box. The cat drank all the milk quickly.\nTakeshi wanted to take the cat home, but his father did not like animals. Takeshi asked his friend Mika for help. Mika's family already had a dog, but they said yes. Now the cat lives with Mika's family. Takeshi visits the cat every Sunday. He named the cat Kuro.",
'g3-reading-story-4':"Two years ago, Lisa moved to a new town with her family. She did not have any friends there. On the first day of school, she was very nervous. A girl named Emma sat next to her and talked to her kindly.\nEmma showed Lisa around the school. They ate lunch together every day. Soon Lisa made many friends. Last month, Lisa and Emma joined the tennis club together. They practice every Saturday morning. Lisa is happy that she met Emma.",
});
Object.assign(QUESTION_BANKS, {
'3': {
library:REVIEW_ARCHIVE['3'].library,
school:REVIEW_ARCHIVE['3'].school,
cafe:REVIEW_ARCHIVE['3'].cafe,
station:[],
park:[],
flower:[],
essay:REVIEW_ARCHIVE['3'].essay
},
});
Object.assign(PRACTICE_ORDER_DATA, {
'3':[
 ["私は去年京都を訪れました。",["Kyoto","visited","I","last","year"],[3,2,1,4,5],"",".","I visited Kyoto last year. の順。visited は visit の過去形。last year は去年。"],
 ["彼は毎朝6時に起きます。",["gets","He","six","up","at"],[2,1,4,5,3],""," every morning.","He gets up at six every morning. の順。get up で起きる。every morning は毎朝。"],
 ["私の母は毎晩本を読みます。",["reads","My mother","evening","a book","every"],[2,1,4,5,3],"",".","My mother reads a book every evening. の順。三人称単数なので reads。every evening は毎晩。"],
 ["あなたは傘を持っていくべきです。",["should","You","umbrella","take","an"],[2,1,4,5,3],""," with you.","You should take an umbrella with you. の順。should は〜すべき。"],
 ["昨夜あなたは夕食に何を食べましたか。",["did","you","eat","What","for dinner"],[4,1,2,3,5],""," last night?","What did you eat for dinner last night? の順。did の後は原形 eat。"],
 ["私たちは図書館で勉強します。",["study","We","the","library","in"],[2,1,5,3,4],"",".","We study in the library. の順。in the library は図書館で。"],
 ["彼女はテニスをするのがとても好きです。",["likes","She","playing","tennis","very much"],[2,1,3,4,5],"",".","She likes playing tennis very much. の順。like + 動名詞で〜するのが好き。"],
 ["彼らは来週大阪へ行く予定です。",["going","They","visit","are","to"],[2,4,1,5,3],""," Osaka next week.","They are going to visit Osaka next week. の順。are going to + 原形で予定。"],
 ["彼らは8時に家を出なければなりません。",["They","must","leave home","eight","at"],[1,2,3,5,4],"",".","They must leave home at eight. の順。must + 原形で〜しなければならない。"],
 ["あなたはこの機械の使い方を知っていますか。",["know","Do","to use","you","how"],[2,4,1,5,3],""," this machine?","Do you know how to use this machine? の順。how to use は使い方。"],
 ["動物の写真を撮るのは楽しいです。",["pictures","Taking","fun","is","of animals"],[2,1,5,4,3],"",".","Taking pictures of animals is fun. の順。動名詞が主語。"],
 ["この本はあの本より面白いです。",["is","This book","more","interesting","than"],[2,1,3,4,5],""," that one.","This book is more interesting than that one. の順。more interesting はより面白い。"],
 ["あなたはこの本をもう読みましたか。",["you","Have","yet","read","this book"],[2,1,4,5,3],"","?","Have you read this book yet? の順。Have you + 過去分詞で経験を聞く。yet はもう。"],
 ["この時計はスイスで作られました。",["made","was","This watch","Switzerland","in"],[3,2,1,5,4],"",".","This watch was made in Switzerland. の順。was made で作られた。"],
 ["彼女は3年前からここに住んでいます。",["has","She","here","lived","since"],[2,1,4,3,5],""," three years ago.","She has lived here since three years ago. の順。has lived since で〜以来住んでいる。"],
 ["富士山は日本で最も高い山です。",["Mt. Fuji","is","highest","mountain","the"],[1,2,5,3,4],""," in Japan.","Mt. Fuji is the highest mountain in Japan. の順。the highest は最も高い。"],
 ["ケンは私より速く走れます。",["can","Ken","faster","run","than me"],[2,1,4,3,5],"",".","Ken can run faster than me. の順。faster than で〜より速く。"],
 ["私たちは昨夜宿題をしなければなりませんでした。",["had","We","homework","to do","our"],[2,1,4,5,3],""," last night.","We had to do our homework last night. の順。had to で過去の〜しなければならなかった。"],
["彼女は昨日新しいかばんを買いました。",["a new bag","She","yesterday","bought"],[2,4,1,3],"",".","She bought a new bag yesterday. の順。buy の過去形 bought。yesterday は固定の文末。"],
["あなたは週末に何をしましたか。",["you","What","last weekend","did","do"],[2,4,1,5,3],"","?","What did you do last weekend? の順。What + did + 主語 + 動詞の原形。last weekend は先週末。"],
["私たちは来月北海道へ行く予定です。",["Hokkaido","are","next month","We","going to visit"],[4,2,5,1,3],"",".","We are going to visit Hokkaido next month. の順。be going to で予定。"],
["この橋は100年前に建てられました。",["was","a hundred years ago","This bridge","built"],[3,1,4,2],"",".","This bridge was built a hundred years ago. の順。by がなくても受動態 was built。"],
["彼は疲れていたので早く寝ました。",["because","he was tired","He","went to bed early"],[3,4,1,2],"",".","He went to bed early because he was tired. の順。because のあとに理由の文。"],
["私はその映画を3回見ました。",["seen","have","that movie","I","three times"],[4,2,1,3,5],"",".","I have seen that movie three times. の順。have seen で見たことがある。three times は3回。"],
["あなたはこの問題を解けますか。",["solve","Can","this problem","you"],[2,4,1,3],"","?","Can you solve this problem? の順。Can + 主語 + 動詞の原形。solve は解く。"],
["私の父は毎晩遅く帰宅します。",["comes","My father","late","home","every night"],[2,1,4,3,5],"",".","My father comes home late every night. の順。come home で帰宅する。late は遅く。"],
["その子は大声で泣き始めました。",["crying","started","The child","loudly"],[3,2,1,4],"",".","The child started crying loudly. の順。start crying で泣き始める。loudly は大声で。"],
["私たちは駅で彼を待っています。",["are","for him","We","waiting","at the station"],[3,1,4,2,5],"",".","We are waiting for him at the station. の順。wait for で〜を待つ。現在進行形。"],
["この辞書はあの辞書より高いです。",["is","more expensive","This dictionary","that one","than"],[3,1,2,5,4],"",".","This dictionary is more expensive than that one. の順。長い形容詞の比較級は more expensive。"],
["あなたは昨日どこで昼食を食べましたか。",["eat lunch","did","Where","yesterday","you"],[3,2,5,1,4],"","?","Where did you eat lunch yesterday? の順。Where + did + 主語 + 動詞の原形。"],
["彼女は3時間もテニスをしました。",["for","played","three hours","She","tennis"],[4,2,5,1,3],"",".","She played tennis for three hours. の順。play tennis でテニスをする。for + 期間。"],
["私は将来医者になりたいです。",["to be","want","a doctor","I","in the future"],[4,2,1,3,5],"",".","I want to be a doctor in the future. の順。want to do で〜したい。in the future は将来。"],
["彼は私に英語を教えてくれました。",["me","taught","He","English"],[3,2,1,4],"",".","He taught me English. の順。teach 人 物で人に物を教える。taught は過去形。"],
["この川はその川より長いです。",["is","This river","that one","longer","than"],[2,1,4,5,3],"",".","This river is longer than that one. の順。longer than で〜より長い。"],
["あなたはもう宿題を終えましたか。",["finished","Have","yet","your homework","you"],[2,5,1,4,3],"","?","Have you finished your homework yet? の順。完了の疑問文の文末は yet。"],
["私たちはその知らせを聞いて驚きました。",["were","We","to hear the news","surprised"],[2,1,4,3],"",".","We were surprised to hear the news. の順。be surprised to do で〜して驚く。"]
],
});
Object.assign(PRACTICE_LISTENING_DATA, {
'3':[
 ['response',1,[{speaker:'A',text:"When is your birthday?"}],"",["It's on May third.","I'm twelve years old.","I like cake."],0,"「誕生日はいつですか」「5月3日です」。When is ...? は時期を聞く。",'shop'],
 ['response',1,[{speaker:'A',text:"What do you want to drink?"}],"",["Orange juice, please.","Yesterday.","With my brother."],0,"「何を飲みたいですか」「オレンジジュースをください」。飲み物を聞いているので飲み物を答える。",'picnic'],
 ['response',2,[{speaker:'A',text:"How did you come here today?"}],"",["By bus.","At eight.","For lunch."],0,"「今日はどうやって来ましたか」「バスで」。How は手段を聞く。",'school'],
 ['response',2,[{speaker:'A',text:"Whose umbrella is this?"}],"",["It's mine.","It's raining.","It's blue."],0,"「これは誰の傘ですか」「私のです」。Whose は誰のものかを聞く。mine は私のもの。",'library'],
 ['response',3,[{speaker:'A',text:"How often do you go swimming?"}],"",["Twice a month.","For two hours.","At the pool."],0,"「どのくらいの頻度で泳ぎに行きますか」「月に2回」。How often は頻度。",'sports'],
 ['response',3,[{speaker:'A',text:"Can I use your phone?"}],"",["It's new.","Sure. Here you are.","I like phones."],1,"「電話を使ってもいいですか」「もちろん。どうぞ」。許可を求められたら Sure.。",'phone'],
 ['dialogue',1,[{speaker:'A',text:"What are you doing, Sara?"},{speaker:'B',text:"I'm cooking dinner. Can you help me?"}],"What is Sara doing?",["Cooking dinner.","Helping Sara.","Eating dinner.","Washing dishes."],0,"「サラ、何をしているの」「夕食を作っているの。手伝ってくれる」。サラがしているのは夕食作り。"],
 ['dialogue',1,[{speaker:'A',text:"Do you have a pet, Tom?"},{speaker:'B',text:"Yes. I have two cats."}],"How many cats does Tom have?",["One.","Two.","Three.","He has no cats."],1,"「ペットを飼っているの」「うん。猫を2匹」。two cats は2匹。"],
 ['dialogue',2,[{speaker:'A',text:"Where were you yesterday afternoon, Emma?"},{speaker:'B',text:"I was at the museum with my class."}],"Where was Emma yesterday afternoon?",["At school.","At the museum.","At home.","At the zoo."],1,"「昨日の午後どこにいたの」「クラスで博物館にいた」。was at the museum は博物館にいた。"],
 ['dialogue',2,[{speaker:'A',text:"What did you buy at the store, Dad?"},{speaker:'B',text:"Some apples and milk."}],"What did Dad buy?",["Apples and milk.","Bread and eggs.","Fish and meat.","Books and pens."],0,"「店で何を買ったの」「りんごと牛乳」。some apples and milk に注意。"],
 ['dialogue',3,[{speaker:'A',text:"Have you finished your homework, Leo?"},{speaker:'B',text:"Not yet. I will finish it after dinner."}],"Has Leo finished his homework?",["Yes, he has.","No, he hasn't.","He doesn't have homework.","He finished it yesterday."],1,"「宿題は終わったの」「まだだよ。夕食後に終える」。Not yet はまだ〜していない。"],
 ['dialogue',3,[{speaker:'A',text:"Why were you absent from school last Friday, Ann?"},{speaker:'B',text:"I had a bad cold, so I stayed home."}],"Why was Ann absent?",["She went shopping.","She had a bad cold.","She visited her friend.","She played tennis."],1,"「先週金曜に学校を休んだのはなぜ」「ひどい風邪をひいたから」。had a bad cold が理由。"],
 ['passage',1,[{speaker:'narrator',text:"I am Ken. I get up at six every morning. I eat breakfast with my family. Then I walk to school."}],"How does Ken go to school?",["By bus.","On foot.","By bike.","By car."],1,"「ケンです。毎朝6時に起き、家族と朝食を食べ、それから歩いて登校します」。walk to school は歩いて登校。"],
 ['passage',1,[{speaker:'narrator',text:"This is our classroom. There are twenty desks. The windows are big and clean. We like our classroom."}],"How many desks are there?",["Ten.","Fifteen.","Twenty.","Thirty."],2,"「ここは私たちの教室です。机が20あります」。twenty desks は20の机。"],
 ['passage',2,[{speaker:'narrator',text:"Last Saturday, my family went to the zoo. We saw lions and elephants. My little brother liked the monkeys best. We ate ice cream for lunch."}],"What did the brother like best?",["Lions.","Elephants.","Monkeys.","Ice cream."],2,"「先週土曜に家族で動物園へ。ライオンと象を見た。弟が一番気に入ったのは猿」。liked best は一番好きだった。"],
 ['passage',2,[{speaker:'narrator',text:"Ms. White is our new English teacher. She comes from Canada. She speaks English and French. Her classes are interesting."}],"Where does Ms. White come from?",["America.","England.","Canada.","Australia."],2,"「ホワイト先生は新しい英語の先生で、カナダ出身。英語とフランス語を話す」。comes from Canada はカナダ出身。"],
 ['passage',3,[{speaker:'narrator',text:"Tom wanted to buy a birthday present for his mother. He saved his money for three months. Last Sunday, he bought a beautiful scarf. His mother was very happy."}],"How long did Tom save money?",["For a week.","For a month.","For three months.","For a year."],2,"「トムは母への誕生日プレゼントを買いたく、3か月お金を貯めた。先週日曜に美しいスカーフを買うと母はとても喜んだ」。for three months は3か月間。"],
 ['passage',3,[{speaker:'narrator',text:"Our town has a new library. It opens at nine in the morning and closes at seven in the evening. It is closed on Mondays. Many children read books there on weekends."}],"When is the library closed?",["On Sundays.","On Mondays.","In the morning.","In the evening."],1,"「町に新しい図書館ができた。午前9時開館、午後7時閉館。月曜休館」。closed on Mondays は月曜休み。"],
['response',1,[{speaker:'A',text:"What is that?"}],"",["It's a watch.","It's old.","I like it."],0,"「あれは何」「時計です」。物を聞く What is that。"],
['response',1,[{speaker:'A',text:"Whose book is this?"}],"",["It's mine.","It's new.","It's thick."],0,"「これは誰の本」「私のです」。持ち主を聞く Whose。mine は私のもの。"],
['response',2,[{speaker:'A',text:"When does the store open?"}],"",["At ten.","On Main Street.","It's big."],0,"「店は何時に開きますか」「10時です」。開店時刻を聞く When does。"],
['response',2,[{speaker:'A',text:"How do you spell your name?"}],"",["K-E-N.","Ken is fine.","My name is Ken."],0,"「名前のつづりは」「K-E-N です」。spell はつづる。"],
['response',3,[{speaker:'A',text:"Why did you cry yesterday?"}],"",["I lost my wallet.","At home.","For an hour."],0,"「昨日なぜ泣いたの」「財布をなくしたんだ」。lose の過去形 lost。"],
['response',3,[{speaker:'A',text:"Could you open the window?"}],"",["Sure.","It's big.","I like air."],0,"「窓を開けてくれますか」「もちろん」。丁寧な依頼は Could you。"],
['dialogue',1,[{speaker:'A',text:"What do you want for lunch, Emi?"},{speaker:'B',text:"Some noodles."}],"What does Emi want for lunch?",["Some noodles.","Some rice.","Some bread.","Some fish."],0,"「昼食に何がほしい、エミ」「麺類」。Some noodles とある。"],
['dialogue',1,[{speaker:'A',text:"Is that your umbrella, Sota?"},{speaker:'B',text:"No. Mine is blue."}],"What color is Sota's umbrella?",["Blue.","Red.","Black.","Green."],0,"「それはあなたの傘、ソウタ」「違う。僕のは青い」。Mine is blue とある。",'umbrella'],
['dialogue',2,[{speaker:'A',text:"Where did you go last weekend, Yui?"},{speaker:'B',text:"I went to the mountains."}],"Where did Yui go last weekend?",["To the mountains.","To the sea.","To the zoo.","To the park."],0,"「先週末はどこへ行ったの、ユイ」「山へ行った」。went to the mountains とある。"],
['dialogue',2,[{speaker:'A',text:"What time do you finish school, Ren?"},{speaker:'B',text:"At four. Then I play soccer."}],"What does Ren do after school?",["He plays soccer.","He studies math.","He reads books.","He watches TV."],0,"「何時に学校が終わるの、レン」「4時。その後サッカーをする」。Then I play soccer とある。"],
['dialogue',3,[{speaker:'A',text:"Have you read this book, Mika?"},{speaker:'B',text:"Yes. It was very exciting."}],"What did Mika think of the book?",["It was very exciting.","It was very long.","It was very difficult.","It was very boring."],0,"「この本を読んだ、ミカ」「うん。とてもわくわくした」。very exciting とある。"],
['dialogue',3,[{speaker:'A',text:"Why are you tired, Kenta?"},{speaker:'B',text:"I played video games until midnight."}],"Why is Kenta tired?",["He played video games late.","He ran in the morning.","He studied all night.","He cleaned his room."],0,"「なぜ疲れているの、ケンタ」「夜中までゲームをしたんだ」。until midnight は夜中まで。"],
['passage',1,[{speaker:'narrator',text:"I am Aki. I have a brother and a sister. My brother is ten and my sister is seven. We walk to school together every day."}],"How many children are there in Aki's family?",["Three.","Two.","Four.","Five."],0,"「アキです。兄と姉がいて、兄10歳、姉7歳。毎日一緒に歩いて登校します」。子どもはアキを含め3人。"],
['passage',1,[{speaker:'narrator',text:"Our dog's name is Momo. She is white and small. Every morning, my father takes Momo for a walk. In the evening, I play with Momo in the garden."}],"What color is Momo?",["White.","Black.","Brown.","Gray."],0,"「犬の名前はモモ。白くて小さい。毎朝父が散歩に連れて行き、夕方は庭で遊びます」。white and small とある。"],
['passage',2,[{speaker:'narrator',text:"Last month, our class grew tomatoes in the school garden. We gave them water every day. Last week, we picked many red tomatoes. We ate them for lunch. They were sweet and fresh."}],"What did the class grow?",["Tomatoes.","Carrots.","Potatoes.","Flowers."],0,"「先月クラスで学校の庭にトマトを植え、毎日水をやり、先週赤いトマトをたくさん収穫して昼に食べた」。grew tomatoes とある。"],
['passage',2,[{speaker:'narrator',text:"My uncle lives near the sea. Last summer, I stayed at his house for a week. Every morning, we swam in the sea. In the afternoon, we walked on the beach and looked for shells."}],"How long did the writer stay at the uncle's house?",["For a week.","For a month.","For three days.","For a year."],0,"「おじは海の近くに住み、去年の夏は1週間泊まった。毎朝泳ぎ、午後は浜を歩いて貝を探した」。for a week とある。"],
['passage',3,[{speaker:'narrator',text:"Midori wants to be a nurse in the future. She studies hard every day. On weekends, she helps at a hospital near her house. The nurses there teach her many things. Midori hopes to work there one day."}],"What does Midori want to be?",["A nurse.","A teacher.","A doctor.","A cook."],0,"「ミドリは将来看護師になりたい。毎日熱心に勉強し、週末は近くの病院を手伝う」。be a nurse とある。"],
['passage',3,[{speaker:'narrator',text:"Our school had a sports festival last Sunday. More than five hundred people came. My class won the relay race. I ran the last part of the race. Everyone cheered loudly. It was a wonderful day."}],"What did the writer's class win?",["The relay race.","The soccer game.","The swimming race.","The singing contest."],0,"「先週日曜は運動会で500人以上が来た。クラスはリレーで優勝し、自分は最終走者だった」。won the relay race とある。",'sports']
],
});
PRACTICE_READING_DATA.push(
['3','notice',1,[
 ["When are the basketball tryouts?",["On Friday morning.","On Friday afternoon.","On Saturday morning.","On Sunday afternoon."],1,"トライアウトは金曜の午後。Tryouts are on Friday afternoon at the school gym. とある。"],
 ["What should students bring?",["A ball and shoes.","Sports shoes and a towel.","A uniform and money.","Books and pencils."],1,"持ち物は運動靴とタオル。Please bring sports shoes and a towel. とあり、ボールは不要。"]
]],
['3','notice',2,[
 ["When will the concert start?",["At six in the morning.","At six in the evening.","At seven in the evening.","At eight in the morning."],1,"開演は夜6時。It starts at six in the evening in the school hall. とある。"],
 ["What do children need to enter the concert?",["Some money.","A ticket.","An instrument.","A uniform."],1,"入場にはチケットが必要。Tickets are free, but you need one to enter. とある。無料だがチケットは要る。"]
]],
['3','email',1,[
 ["Why is Yuki not surprised that Ken won?",["Ken practiced hard for a month.","Ken is good at writing letters.","Ken won last year, too.","Ken likes contests."],0,"1か月一生懸命練習したから驚かない。You practiced hard for a month, so I am not surprised. とある。"],
 ["How is Yuki's new house different?",["It is smaller.","It is bigger.","It is noisier.","It is darker."],1,"新しい家は前の家より大きい。It is bigger than our old house とある。"],
 ["What does Yuki often do with her new friends?",["Swim in the pool.","Play soccer in the park.","Ride bikes to school.","Watch movies at home."],1,"新しい友達と公園でサッカーをすることが多い。I often play soccer there with my new friends. とある。"]
]],
['3','email',2,[
 ["Why was Taro absent yesterday?",["He had a bad cold.","He took an English test.","He visited his friend.","He lost his bag."],0,"ひどい風邪で休んだ。I had a bad cold and stayed home all day. とある。"],
 ["What did Taro miss at school?",["A soccer game.","A music class.","An English test.","A school trip."],2,"英語のテストを受けられなかった。I missed the English test. とある。"],
 ["What does Taro want Ms. Green to tell him?",["What he should study.","Where the hospital is.","Why he was absent.","How to write a letter."],0,"何を勉強すべきか教えてほしい。Please tell me what I should study. とある。"]
]],
['3','story',1,[
 ["Where does Riku's grandmother live?",["In a big city.","Near the sea.","On a mountain.","Near a station."],1,"祖母は海の近くの小さな家に一人で住む。in a small house near the sea とある。"],
 ["What did Riku do every morning?",["Carried water from the well.","Cooked breakfast.","Walked to school.","Fed the dog."],0,"毎朝井戸から水を運ぶ手伝いをした。helped her carry water from the well とある。"],
 ["What did Riku give the dog?",["Some milk.","Some bread.","Some fish.","Some rice."],1,"おなかをすかせていたのでパンをあげた。he gave it some bread とある。"],
 ["Why was Riku sad at the end of summer?",["He lost his bag.","He had to go home.","The dog was sick.","His grandmother was sick."],1,"夏が終わり家に帰らねばならず、犬と別れるのが悲しかった。He had to go home. とある。"],
 ["Who will take care of the dog?",["Riku.","His mother.","His grandmother.","Nobody."],2,"祖母が世話をすると言った。I will take care of it. とある。"]
]],
['3','story',2,[
 ["How long has Mia kept a diary?",["Since she was ten.","For a month.","Since last week.","For a year."],0,"10歳のときから日記をつけている。has kept a diary since she was ten とある。"],
 ["What did Mia find on the road?",["A bag.","A key.","An old wallet.","A letter."],2,"道で古い財布を拾った。she saw an old wallet on the road とある。"],
 ["Where did Mia take the wallet?",["To her school.","To the police station.","To her house.","To the store."],1,"家の近くの交番へ届けた。took it to the police station near her house とある。"],
 ["What was in the wallet?",["Some bills and a card.","Some photos and keys.","A phone and money.","Books and pencils."],0,"お札とカードが入っていた。There were some bills and a card in it. とある。"],
 ["Who wrote a letter to Mia?",["The police officer.","The man who lost the wallet.","Her teacher.","Her friend."],1,"財布をなくした男性からの手紙だった。from the man who lost the wallet とある。"]
]],
['3','notice',3,[
["When does the swimming club practice?",["Every Tuesday and Friday.","Every Monday and Thursday.","Every Saturday.","Every Sunday."],0,"毎週火曜と金曜。every Tuesday and Friday afternoon とある。町のプールで練習。"],
["What do members need?",["Swimming clothes and a towel.","A ball and shoes.","Books and pencils.","Lunch and a drink."],0,"水着とタオル。swimming clothes and a towel とある。ゴーグルは不要。"]
]],
['3','email',3,[
["What did Saki enjoy last Sunday?",["Playing cards with Aya.","Watching TV with Aya.","Cooking lunch with Aya.","Reading books with Aya."],0,"アヤとカード遊びを楽しんだ。enjoyed playing cards with you とある。"],
["When will the party start?",["At three on Saturday.","At two on Sunday.","At four on Friday.","At five on Monday."],0,"土曜3時開始。start at three on Saturday afternoon とある。"],
["What does Saki want Aya to do?",["Write back soon.","Bring a cake.","Call her sister.","Come by car."],0,"早く返事がほしい。Please write back soon とある。"]
]],
['3','email',4,[
["Where does Yuki's grandmother live?",["In the mountains.","Near the sea.","In a big town.","On an island."],0,"山に住む。lives in the mountains とある。先週末に訪ねた。"],
["What did Yuki and her grandmother make?",["Grape jam.","Apple pie.","Rice balls.","Fish soup."],0,"ジャムを作った。made jam from the grapes とある。庭のぶどうで作った。"],
["How old is Yuki's grandmother?",["Eighty.","Seventy.","Ninety.","Sixty."],0,"80歳。eighty years old とある。とても元気。"]
]],
['3','story',3,[
["Where did Takeshi find the cat?",["In the park.","At school.","Near the station.","In his garden."],0,"公園で見つけた。found a small black cat in the park とある。ベンチの下で鳴いていた。"],
["What did Takeshi give the cat?",["Some milk.","Some bread.","Some fish.","Some water."],0,"牛乳をあげた。gave the cat some milk from his lunch box とある。すぐ飲み干した。"],
["Why couldn't Takeshi take the cat home?",["His father did not like animals.","His mother was sick.","His house was too small.","He had a dog."],0,"父が動物を好きでないから。father did not like animals とある。友達のミカに助けを求めた。"],
["Who takes care of the cat now?",["Mika's family.","Takeshi's family.","The park keeper.","A pet shop."],0,"今はミカの家で飼う。lives with Mika's family とある。ミカの家には犬がいる。"],
["What is the cat's name?",["Kuro.","Mika.","Takeshi.","Shiro."],0,"クロと名付けた。named the cat Kuro とある。毎週日曜に会いに行く。"]
]],
['3','story',4,[
["When did Lisa move to the new town?",["Two years ago.","Last year.","Three years ago.","Last month."],0,"2年前。Two years ago とある。家族と引っ越した。"],
["How did Lisa feel on the first day?",["Nervous.","Excited.","Angry.","Sleepy."],0,"緊張していた。was very nervous とある。友達がいなかった。"],
["Who talked to Lisa first?",["Emma.","Her teacher.","Her mother.","A boy."],0,"エマが最初に話しかけた。sat next to her and talked to her kindly とある。"],
["What club did Lisa and Emma join?",["The tennis club.","The soccer club.","The music club.","The art club."],0,"テニス部に入った。joined the tennis club together とある。先月のこと。"],
["When do they practice?",["Every Saturday morning.","Every Sunday afternoon.","Every Friday evening.","Every Monday morning."],0,"毎週土曜の朝。every Saturday morning とある。"]
]],
);
