// 英検4級の問題データ
Object.assign(REVIEW_ARCHIVE, {
'4': {
library:[
{id:'g4-library-001',legacyIndex:0,d:1,q:"My mother ___ dinner for us every evening.",c:["cooks","cook","cooked","cooking"],a:0,e:"「毎晩」の話で、主語が My mother(三人称単数)なので動詞に s をつけて cooks。「母は毎晩夕食を作ってくれる」。"},
{id:'g4-library-002',legacyIndex:1,d:1,q:"I ___ to school by bus every day.",c:["go","goes","going","went"],a:0,e:"主語が I のとき一般動詞は原形のまま。「毎日バスで学校へ行く」。"},
{id:'g4-library-003',legacyIndex:2,d:1,q:"She ___ TV last night.",c:["watched","watch","watches","watching"],a:0,e:"last night(ゆうべ)は過去を表す言葉なので過去形 watched を使う。"},
{id:'g4-library-004',legacyIndex:3,d:1,q:"There ___ two cats in the garden.",c:["are","is","was","be"],a:0,e:"two cats と複数なので There are。is は単数のときに使う。"},
{id:'g4-library-005',legacyIndex:4,d:1,q:"Look! The children ___ soccer in the park.",c:["are playing","play","plays","played"],a:0,e:"Look!(見て!)といっているときは、今まさにしていること=現在進行形 are playing。"},
{id:'g4-library-006',legacyIndex:5,d:1,q:"Did you ___ your hands before lunch?",c:["wash","washed","washes","washing"],a:0,e:"Did を使った疑問文では動詞は原形にもどす(Did you wash ...?)。"},
{id:'g4-library-007',legacyIndex:6,d:1,q:"Ken can ___ very fast.",c:["run","runs","ran","running"],a:0,e:"can(〜できる)のあとは動詞の原形を置く。"},
{id:'g4-library-008',legacyIndex:7,d:1,q:"This book is ___ than that one.",c:["more interesting","interesting","most interesting","interestinger"],a:0,e:"than(〜より)でくらべているので比較級。長い単語の比較級は more をつける。"},
{id:'g4-library-009',legacyIndex:8,d:1,q:"Mt. Fuji is ___ mountain in Japan.",c:["the highest","high","higher","highest"],a:0,e:"「日本でいちばん高い」のように一番を表すのは最上級 the highest。"},
{id:'g4-library-010',legacyIndex:9,d:1,q:"How ___ water do you drink every day?",c:["much","many","old","long"],a:0,e:"water(水)は数えられない名詞なので How much。数えられるものは How many。"},
{id:'g4-library-011',legacyIndex:10,d:1,q:"We have no bread. Let's go ___.",c:["shopping","shop","shopped","shops"],a:0,e:"「買い物に行く」は go shopping とセットで覚える。"},
{id:'g4-library-012',legacyIndex:11,d:1,q:"My birthday is ___ October.",c:["in","on","at","of"],a:0,e:"月や年には in(10月に=in October)。日付には on、時刻には at。"},
{id:'g4-library-013',legacyIndex:12,d:1,q:"Please turn ___ the light. It's dark here.",c:["on","off","in","up"],a:0,e:"暗いから電気をつける=turn on。消すは turn off。"},
{id:'g4-library-014',legacyIndex:13,d:1,q:"A: ___ is that bag? B: It's 2,000 yen.",c:["How much","How many","How old","How long"],a:0,e:"値段を聞くときは How much(いくら)。"},
{id:'g4-library-015',legacyIndex:14,d:1,q:"Winter is my favorite ___ of the year.",c:["season","month","day","week"],a:0,e:"一年の中で好きなのは season(季節)。month=月、week=週。"},
{id:'g4-library-016',legacyIndex:15,d:1,q:"He plays tennis ___ weekends.",c:["on","in","under","for"],a:0,e:"米国英語では on weekends。英国英語では at weekends とも言う。ここでは on を選ぶ。"},
{id:'g4-library-017',legacyIndex:16,d:2,q:"She is good ___ playing the violin.",c:["at","in","for","of"],a:0,e:"「〜が得意」は be good at 〜ing とセット。"},
{id:'g4-library-018',legacyIndex:17,d:2,q:"Thank you ___ helping me with my homework.",c:["for","to","of","with"],a:0,e:"「〜してくれてありがとう」= Thank you for 〜ing。"},
{id:'g4-library-019',legacyIndex:18,d:2,q:"I'm looking ___ my cat. She's lost!",c:["for","at","after","up"],a:0,e:"「探している」= look for。look at はただ「見る」。"},
{id:'g4-library-020',legacyIndex:19,d:2,q:"If it rains tomorrow, we ___ stay home.",c:["will","did","are","be"],a:0,e:"if(もし〜なら)の文で未来のことは will を使って表す。"},
{id:'g4-library-021',legacyIndex:20,d:2,q:"You look tired. You ___ go to bed early tonight.",c:["should","must not","can't","would not"],a:0,e:"アドバイスには should(〜したほうがいい)。"},
{id:'g4-library-022',legacyIndex:21,d:2,q:"I enjoy ___ music in my room.",c:["listening to","listen to","to listening","listened"],a:0,e:"enjoy のあとは動名詞(-ing)。聴くは listen TO music なので to も忘れずに。"},
{id:'g4-library-023',legacyIndex:22,d:2,q:"A: Whose bag is this? B: It's ___.",c:["mine","my","me","I"],a:0,e:"「私のもの」は所有代名詞 mine。my はあとに名詞(my bag)が必要。"},
{id:'g4-library-024',legacyIndex:23,d:2,q:"How ___ is it from here to the station?",c:["far","long","much","many"],a:0,e:"距離を聞くのは How far。時間の長さなら How long。"},
{id:'g4-library-025',legacyIndex:24,d:2,q:"I have lived in Kyoto ___ ten years.",c:["for","since","from","during"],a:0,e:"ten years のように期間を表すのは for。since は起点(2015年など)。"},
{id:'g4-library-026',legacyIndex:25,d:2,q:"She enjoys playing the piano ___ her free time.",c:["in","on","at","to"],a:0,e:"ひまな時間=free time には in を使うのがふつう。"},
{id:'g4-library-027',legacyIndex:26,d:2,q:"I was late ___ the heavy rain this morning.",c:["because of","because","so","if"],a:0,e:"because of のあとは名詞。because のあとは主語+動詞の文。"},
{id:'g4-library-028',legacyIndex:27,d:2,q:"You ___ eat more vegetables. They are good for you.",c:["should","shouldn't","can't","won't"],a:0,e:"野菜は体にいいので should(食べたほうがいい)。shouldn't は反対の意味。"},
{id:'g4-library-029',legacyIndex:28,d:2,q:"A: ___ do you play tennis? B: Twice a week.",c:["How often","How many","How much","How long"],a:0,e:"Twice a week(週2回)は回数=頻度なので How often。"},
{id:'g4-library-030',legacyIndex:29,d:2,q:"My dream is ___ a doctor.",c:["to become","become","became","becomes"],a:0,e:"「医者になること」は to 不定詞の名詞的用法 to become。"},
{id:'g4-library-031',legacyIndex:30,d:3,q:"The movie was so ___ that I cried at the end.",c:["sad","happy","funny","exciting"],a:0,e:"最後に泣いたのだから sad(かなしい)。文全体の意味から正しい形容詞を選ぼう。"},
{id:'g4-library-032',legacyIndex:31,d:3,q:"If it ___ tomorrow, the game will be canceled.",c:["rains","will rain","rained","rain"],a:0,e:"if 節の中では未来のことでも現在形 rains を使うのがルール。"},
{id:'g4-library-033',legacyIndex:32,d:3,q:"I don't know ___ to swim yet.",c:["how","what","where","who"],a:0,e:"「泳ぎ方」= how to swim。how to do で「〜のしかた」。"},
{id:'g4-library-034',legacyIndex:33,d:3,q:"My mother asked me ___ the dishes.",c:["to wash","wash","washing","washed"],a:0,e:"ask 人 to do=人に〜するよう頼む。目的語のあとは to 不定詞。"},
{id:'g4-library-035',legacyIndex:34,d:3,q:"You must ___ quiet in the library.",c:["be","is","are","being"],a:0,e:"must のあとは動詞の原形。quiet は形容詞なので be を使う。"},
{id:'g4-library-036',legacyIndex:35,d:3,q:"Neither answer ___ right.",c:["is","are","were","be"],a:0,e:"neither(どちらも〜ない)は単数扱い。「どちらの答えも正しくない」。"},
{id:'g4-library-037',legacyIndex:36,d:3,q:"She is looking forward to ___ you again.",c:["seeing","see","saw","be seeing"],a:0,e:"look forward to + 動名詞。「また会えるのを楽しみにしている」。to があっても -ing!"},
{id:'g4-library-038',legacyIndex:37,d:3,q:"It's getting dark. Let's ___ home.",c:["go","to go","going","went"],a:0,e:"Let's(〜しよう)のあとは動詞の原形 go。"},
{id:'g4-library-039',legacyIndex:38,d:3,q:"A: Must I bring my dictionary? B: No, you ___.",c:["don't have to","mustn't","can't","shouldn't"],a:0,e:"Must I 〜? の否定の答えは don't have to(持ってこなくていい)。mustn't は「〜してはいけない」なので注意!"},
{id:'g4-library-040',legacyIndex:39,d:3,q:"Ken is ___ honest boy.",c:["an","a","the","one"],a:0,e:"honest の h は発音しないので音では母音ではじまる言葉。「アン オネスト ボーイ」だから an。"}
],
school:[
{id:'g4-school-001',legacyIndex:0,d:1,q:"My brother ___ soccer after school every day.",c:["plays","play","playing","played"],a:0,e:"三人称単数(My brother)+習慣(every day)=三単現の s。"},
{id:'g4-school-002',legacyIndex:1,d:1,q:"They ___ at the library yesterday afternoon.",c:["were","was","are","is"],a:0,e:"They に対する be 動詞の過去形は were。"},
{id:'g4-school-003',legacyIndex:2,d:1,q:"What ___ you doing now?",c:["are","is","do","did"],a:0,e:"進行形は be + -ing。you には are。「今なにしてるの?」"},
{id:'g4-school-004',legacyIndex:3,d:1,q:"I'm going to ___ my grandmother this weekend.",c:["visit","visited","visits","visiting"],a:0,e:"be going to + 動詞の原形で「〜するつもり」。"},
{id:'g4-school-005',legacyIndex:4,d:1,q:"My sister ___ swim when she was three years old.",c:["could","can","may","must"],a:0,e:"3歳のとき(過去)にできていた=can の過去形 could。"},
{id:'g4-school-006',legacyIndex:5,d:1,q:"___ does your school start?",c:["What time","How much","How many","Which"],a:0,e:"時刻を聞く疑問詞は What time。"},
{id:'g4-school-007',legacyIndex:6,d:1,q:"___ quiet, please. The class is starting.",c:["Be","Is","Are","Being"],a:0,e:"命令文は動詞の原形ではじめる。quiet は形容詞なので Be quiet!(静かに!)" },
{id:'g4-school-008',legacyIndex:7,d:1,q:"___ there a big station near your old house?",c:["Was","Were","Is","Are"],a:0,e:"old house(昔の家)=過去の話。a station は単数なので Was there。"},
{id:'g4-school-009',legacyIndex:8,d:1,q:"This present is for Ken. Please give it to ___.",c:["him","he","his","she"],a:0,e:"前置詞 to のあとは目的格 him。"},
{id:'g4-school-010',legacyIndex:9,d:1,q:"I bought a ___ bag yesterday.",c:["beautiful","beautifully","beauty","beautify"],a:0,e:"名詞 bag を説明するのは形容詞 beautiful。beautifully は動詞を修飾する副詞。"},
{id:'g4-school-011',legacyIndex:10,d:1,q:"She sings very ___. Everyone likes her songs.",c:["well","good","nice","fine"],a:0,e:"動詞 sings を修飾するのは副詞 well(good の副詞形)。"},
{id:'g4-school-012',legacyIndex:11,d:1,q:"How ___ students are there in your class?",c:["many","much","long","often"],a:0,e:"students は数えられる名詞なので How many。"},
{id:'g4-school-013',legacyIndex:12,d:1,q:"I like dogs, ___ I don't like cats.",c:["but","and","or","so"],a:0,e:"好き/きらいで対比になっているので but(でも)。"},
{id:'g4-school-014',legacyIndex:13,d:1,q:"She ___ a letter to her friend last week.",c:["wrote","write","written","writes"],a:0,e:"write の過去形は wrote。last week で過去。"},
{id:'g4-school-015',legacyIndex:14,d:2,q:"I went to the station ___ my friend.",c:["to meet","meeting","met","meet"],a:0,e:"「会うために」目的の to 不定詞。"},
{id:'g4-school-016',legacyIndex:15,d:2,q:"___ color do you like better, red or blue?",c:["Which","What","Who","Whose"],a:0,e:"2つの選択肢から選ばせる疑問詞は Which(どちら)。"},
{id:'g4-school-017',legacyIndex:16,d:2,q:"The ___ tail is very long.",c:["cat's","cat","cats","of cat"],a:0,e:"「猫のしっぽ」は所有格 cat's tail。"},
{id:'g4-school-018',legacyIndex:17,d:2,q:"Ken is two years ___ than his sister.",c:["older","oldest","more old","old"],a:0,e:"「数 + 比較級 + than」で「〜歳ぶん年上」。"},
{id:'g4-school-019',legacyIndex:18,d:2,q:"Tom is as ___ as his father.",c:["tall","taller","tallest","more tall"],a:0,e:"as 原形 as で「同じくらい」。as tall as=父と同じくらいの身長。"},
{id:'g4-school-020',legacyIndex:19,d:2,q:"You ___ play soccer in the street. It's dangerous.",c:["must not","don't have to","may","will"],a:0,e:"禁止は must not(〜してはいけない)。don't have to は「必要がない」。"},
{id:'g4-school-021',legacyIndex:20,d:2,q:"I stayed home ___ I had a bad cold.",c:["because","but","or","though"],a:0,e:"風邪だった→家にいた。理由を表す because。"},
{id:'g4-school-022',legacyIndex:21,d:2,q:"My hobby is ___ video games.",c:["playing","play","plays","played"],a:0,e:"be 動詞のあとで「〜すること」は動名詞(-ing)。"},
{id:'g4-school-023',legacyIndex:22,d:2,q:"___ a nice day it is today!",c:["What","How","Which","Who"],a:0,e:"感嘆文 What a + 形容詞 + 名詞!(なんて良い天気!)How nice it is! とも言える。"},
{id:'g4-school-024',legacyIndex:23,d:2,q:"___ your brother like pizza?",c:["Does","Do","Is","Are"],a:0,e:"your brother は三人称単数。Does ではじめたら動詞は原形 like へ。"},
{id:'g4-school-025',legacyIndex:24,d:2,q:"My birthday is ___ March 3rd.",c:["on","in","at","by"],a:0,e:"日付があるときは on。月だけなら in March。"},
{id:'g4-school-026',legacyIndex:25,d:2,q:"I have two pens. One is blue, and ___ is black.",c:["the other","other","another","others"],a:0,e:"2つのうち残りの1つ=the other。"},
{id:'g4-school-027',legacyIndex:26,d:2,q:"There ___ a new shopping mall here next year.",c:["will be","was","were","are"],a:0,e:"next year は未来。There is の未来形は There will be。"},
{id:'g4-school-028',legacyIndex:27,d:2,q:"She ___ goes jogging after dinner.",c:["usually","usual","useful","use"],a:0,e:"「たいてい」の頻度を表す usually は副詞。usual は形容詞。"},
{id:'g4-school-029',legacyIndex:28,d:3,q:"I ___ dinner when the phone rang.",c:["was cooking","cooked","am cooking","cook"],a:0,e:"電話が鳴った「そのとき料理をしていた」=過去進行形 was cooking。"},
{id:'g4-school-030',legacyIndex:29,d:3,q:"If you study harder, you ___ pass the test.",c:["will","would","did","are"],a:0,e:"if 節は現在形、もう一方の文に will。「勉強すれば合格するでしょう」。"},
{id:'g4-school-031',legacyIndex:30,d:3,q:"She asked me ___ her with her homework.",c:["to help","helping","help","helped"],a:0,e:"ask 人 to do=人に〜するようたのむ。"},
{id:'g4-school-032',legacyIndex:31,d:3,q:"The days are getting ___ in spring.",c:["longer and longer","long and long","more long","longest"],a:0,e:"比較級 and 比較級=「ますます」。「日がだんだん長くなる」。"},
{id:'g4-school-033',legacyIndex:32,d:3,q:"Lake Biwa is the largest lake ___ Japan.",c:["in","of","on","between"],a:0,e:"最上級で範囲が場所なら in。of はグループ(the largest of all)。"},
{id:'g4-school-034',legacyIndex:33,d:3,q:"___ were you doing at eight last night?",c:["What","Where","Who","When"],a:0,e:"過去進行形と組み合わせ「昨夜8時に何をしていましたか」。"},
{id:'g4-school-035',legacyIndex:34,d:3,q:"Wait here ___ I come back.",c:["until","because","if","so"],a:0,e:"until(〜までずっと)。「戻ってくるまで待っていて」。"},
{id:'g4-school-036',legacyIndex:35,d:3,q:"After ___ dinner, I take a short walk.",c:["eating","eat","ate","eaten"],a:0,e:"After が前置詞のときは動名詞(-ing)がくる。"},
{id:'g4-school-037',legacyIndex:36,d:3,q:"Look! There are ten ___ in the field.",c:["sheep","sheeps","sheep's","a sheep"],a:0,e:"sheep(羊)は単数も複数も同じ形。sheeps はない!"},
{id:'g4-school-038',legacyIndex:37,d:3,q:"___ is ready for the party. Let's start!",c:["Everything","Every","Everybody are","Every things"],a:0,e:"Everything は「すべてのもの・こと」で単数扱い。Everything is の形で使う。"},
{id:'g4-school-039',legacyIndex:38,d:3,q:"Ken is ___ in his class.",c:["the tallest","taller","the taller","most tall"],a:0,e:"クラスで一番なら最上級 the tallest。比較級は2者を比べるとき。"},
{id:'g4-school-040',legacyIndex:39,d:3,q:"___ did you stay in Kyoto last month?",c:["How long","How often","How far","How soon"],a:0,e:"「どのくらいの期間」は How long。How often は頻度、How far は距離。"}
],
cafe:[
{id:'g4-cafe-001',legacyIndex:0,d:1,q:"A: Thank you for your help.\nB: ___",c:["You're welcome.","Here you are.","Yes, please.","No, thank you."],a:0,e:"「手伝ってくれてありがとう」には You're welcome.(どういたしまして)。Here you are. はものを渡すときの言葉。"},
{id:'g4-cafe-002',legacyIndex:1,d:1,q:"A: How are you today?\nB: ___",c:["I'm fine, thank you.","I'm thirteen years old.","Yes, I am.","It's sunny today."],a:0,e:"調子を聞かれているので I'm fine.(元気だよ)と答える。"},
{id:'g4-cafe-003',legacyIndex:2,d:1,q:"A: See you tomorrow!\nB: ___",c:["See you!","Me too.","Good night.","You're welcome."],a:0,e:"別れのあいさつは See you!(またね!)"},
{id:'g4-cafe-004',legacyIndex:3,d:1,q:"A: I'm sorry I'm late.\nB: ___",c:["That's OK.","Of course.","Good idea.","Nice to meet you."],a:0,e:"謝られたら That's OK.(大丈夫だよ)と返すのが自然。"},
{id:'g4-cafe-005',legacyIndex:4,d:1,q:"A: Let's play badminton after school.\nB: ___",c:["Sounds great!","I'm fine.","See you tomorrow.","You're right."],a:0,e:"誘いに乗るときは Sounds great!(いいね!)Let's の誘いには賛成の返事を。"},
{id:'g4-cafe-006',legacyIndex:5,d:1,q:"A: What day is it today?\nB: ___",c:["It's Monday.","It's nine o'clock.","It's May 5th.","It's rainy."],a:0,e:"曜日を聞かれている。It's Monday.(月曜日)。時刻・日付・天気ではない。"},
{id:'g4-cafe-007',legacyIndex:6,d:1,q:"A: Do you like ice cream?\nB: ___",c:["Yes, I love it.","Yes, I am.","Yes, it is.","No, I can't."],a:0,e:"Do you like 〜? への答えは Yes, I do./Yes, I love it. I am は be 動詞の質問への返事。"},
{id:'g4-cafe-008',legacyIndex:7,d:1,q:"A: Where are you from?\nB: ___",c:["I'm from Australia.","I'm twelve years old.","I'm fine.","I'm a student."],a:0,e:"出身地を聞かれているので国や町の名前で答える。"},
{id:'g4-cafe-009',legacyIndex:8,d:1,q:"A: What time is it now?\nB: ___",c:["It's half past three.","It's Monday.","It's March.","It's cold."],a:0,e:"時刻は It's + 時刻。half past three=3時30分。"},
{id:'g4-cafe-010',legacyIndex:9,d:1,q:"A: Hello, this is Yumi.\nB: Hi, Yumi. ___",c:["How are you?","Who are you?","Where is it?","What is that?"],a:0,e:"あいさつがすんだら How are you? で調子を聞くと会話がつづく。"},
{id:'g4-cafe-011',legacyIndex:10,d:1,q:"A: Can I use your eraser?\nB: Sure. ___",c:["Here you are.","Thank you.","You're welcome.","Excuse me."],a:0,e:"Sure.(もちろん)といってものを渡すときは Here you are.(はい、どうぞ)。"},
{id:'g4-cafe-012',legacyIndex:11,d:1,q:"A: Good morning, everyone!\nB: ___",c:["Good morning, Ms. Sato!","Good night, Ms. Sato!","Good bye, Ms. Sato!","Take care, Ms. Sato!"],a:0,e:"朝のあいさつは Good morning. 先生などには Ms. などの呼びかけをつけると丁寧。"},
{id:'g4-cafe-013',legacyIndex:12,d:2,q:"A: Could you pass the salt, please?\nB: ___",c:["Sure, here you are.","Yes, it is.","No, thanks.","I'd love to."],a:0,e:"Could you 〜? は丁寧なお願い。引き受けるときは Sure, here you are."},
{id:'g4-cafe-014',legacyIndex:13,d:2,q:"A: I passed the English exam!\nB: ___",c:["Congratulations!","I'm sorry to hear that.","Good luck!","Take care."],a:0,e:"よい知らせには Congratulations!(おめでとう!)Good luck! はこれからがんばる人にかける言葉。"},
{id:'g4-cafe-015',legacyIndex:14,d:2,q:"A: Would you like something to drink?\nB: ___",c:["Orange juice, please.","I like orange juice.","Orange juice is sweet.","I drank juice yesterday."],a:0,e:"Would you like 〜? は勧めの言葉。ほしいときは Orange juice, please. と注文のかたちで答える。"},
{id:'g4-cafe-016',legacyIndex:15,d:2,q:"A: How about going to the movies tonight?\nB: ___",c:["I'd love to!","I saw it last week.","It's five hundred yen.","By bus, please."],a:0,e:"How about 〜?(〜はどう?)への乗り気な返事は I'd love to.(ぜひ!)"},
{id:'g4-cafe-017',legacyIndex:16,d:2,q:"A: What's the matter? You look pale.\nB: ___",c:["I feel sick.","I got a present.","It's my birthday.","I won the game."],a:0,e:"顔色が悪そうと言われた理由は I feel sick.(気分が悪い)。"},
{id:'g4-cafe-018',legacyIndex:17,d:2,q:"A: Can I help you?\nB: ___",c:["Yes. I'm looking for a gift.","No problem.","Help yourself.","You're welcome."],a:0,e:"店員さんの Can I help you? には探しているものを伝える。Help yourself. は「ご自由にどうぞ」。"},
{id:'g4-cafe-019',legacyIndex:18,d:2,q:"A: What do you do in your free time?\nB: ___",c:["I play the guitar and read books.","At seven o'clock.","By myself.","Once a week."],a:0,e:"自由時間にすることを聞かれているので、習慣のことを一般動詞で答える。"},
{id:'g4-cafe-020',legacyIndex:19,d:2,q:"A: Is it OK if I open the window?\nB: ___",c:["Sure, go ahead.","Yes, I am.","Thanks a lot.","I'm opening now."],a:0,e:"許可をたずねられたら Sure, go ahead.(どうぞやって)と返す。"},
{id:'g4-cafe-021',legacyIndex:20,d:2,q:"A: I'm so hungry!\nB: ___",c:["Let's get something to eat.","Let's do our homework.","Let's clean the room.","Let's call the police."],a:0,e:"おなかがすいたら Let's get something to eat.(何か食べに行こう)"},
{id:'g4-cafe-022',legacyIndex:21,d:2,q:"A: Thanks for walking my dog.\nB: ___",c:["Anytime!","I'm afraid so.","So am I.","Well done."],a:0,e:"Anytime!(いつでもいいよ)は感謝へのカジュアルな返事。"},
{id:'g4-cafe-023',legacyIndex:22,d:2,q:"A: What's your favorite subject?\nB: ___",c:["Art. I love drawing.","Mr. Tanaka. He is kind.","Monday and Thursday.","In the art room."],a:0,e:"favorite subject は教科のこと。先生や曜日、場所ではない。"},
{id:'g4-cafe-024',legacyIndex:23,d:2,q:"A: Sorry, what did you say?\nB: ___",c:["I said let's meet at noon.","You're welcome.","That's right.","Here we are."],a:0,e:"聞き返されたら言った内容をもう一度くり返す。"},
{id:'g4-cafe-025',legacyIndex:24,d:3,q:"A: Excuse me, how can I get to the museum?\nB: ___",c:["Go straight and turn left at the second corner.","You should visit there once.","It costs eight dollars.","The museum is very old."],a:0,e:"道案内は Go straight(まっすぐ行く)/turn left(左に曲がる)などの表現で説明する。"},
{id:'g4-cafe-026',legacyIndex:25,d:3,q:"A: Could you say that again more slowly?\nB: ___",c:["Of course. The meeting starts at six.","The room is on the second floor.","My name is Ken.","It's Tuesday today."],a:0,e:"「もう一度ゆっくり」たのまれたら承知して、言った内容をゆっくりくり返す。"},
{id:'g4-cafe-027',legacyIndex:26,d:3,q:"A: What do you think of this T-shirt?\nB: ___",c:["It looks great on you!","Yes, it is a T-shirt.","I'm wearing shoes.","The shop closes at eight."],a:0,e:"意見を聞かれたら It looks ...(ように見える)で感想を伝える。"},
{id:'g4-cafe-028',legacyIndex:27,d:3,q:"A: I'm afraid I can't come to your party.\nB: ___",c:["That's too bad. Maybe next time!","Congratulations!","You're welcome!","Sounds wonderful!"],a:0,e:"断られたら残念がりつつ次のチャンスをさそう。I'm afraid はやんわり断るときの言葉。"},
{id:'g4-cafe-029',legacyIndex:28,d:3,q:"A: Do you mind if I sit here?\nB: ___",c:["Of course not. Go ahead.","Yes, I am.","No, thank you.","Yes, it is."],a:0,e:"mind(気にする)を使った許可の質問には Of course not.(全然気にしないよ)。Yes だと嫌な意味になるので注意!"},
{id:'g4-cafe-030',legacyIndex:29,d:3,q:"A: How was your trip to Kyoto?\nB: ___",c:["It was wonderful. I want to go again.","It takes two hours by train.","Maybe next spring.","With my classmates."],a:0,e:"How was 〜? には体験の評価(It was wonderful.)で答える。時間や時期は別の質問への返事。"},
{id:'g4-cafe-031',legacyIndex:30,d:3,q:"A: You speak English very well!\nB: ___",c:["Thank you. I study every day.","Yes, you speak English well.","My name is Ken.","It's my dictionary."],a:0,e:"英語圏ではほめられたら Thank you と素直にうけとるのがマナー。"},
{id:'g4-cafe-032',legacyIndex:31,d:3,q:"A: Would you mind waiting a minute?\nB: ___",c:["No, not at all.","Yes, I am.","No, thank you.","Yes, it does."],a:0,e:"Would you mind 〜? は丁寧なお願い。OK の返事は No, not at all.(全然構わない)!"},
{id:'g4-cafe-033',legacyIndex:32,d:3,q:"A: What time shall we meet tomorrow?\nB: ___",c:["How about at ten?","It's ten o'clock now.","I met him at ten.","We walked ten minutes."],a:0,e:"集合時刻を決めるときは How about 〜?(〜はどう?)を使うと自然。"},
{id:'g4-cafe-034',legacyIndex:33,d:3,q:"A: I heard you broke your leg. How are you feeling?\nB: ___",c:["Much better, thank you.","The game starts at three.","My favorite color is blue.","Turn left at the bank."],a:0,e:"体調を聞かれたら Much better.(だいぶ良くなった)など自分の状態で答える。"},
{id:'g4-cafe-035',legacyIndex:34,d:3,q:"A: May I take your order?\nB: ___",c:["Yes. I'll have a cheeseburger, please.","The waiter is very kind.","This table is small.","Lunch begins at eleven."],a:0,e:"May I take your order?(ご注文はお決まりですか)には I'll have 〜.(〜をください)で注文する。"},
{id:'g4-cafe-036',legacyIndex:35,d:3,q:"A: I'm moving to Osaka next month.\nB: ___",c:["Really? I'll miss you!","Osaka Castle is beautiful.","I visited Osaka once.","It's south of Tokyo."],a:0,e:"引っ越しの報告には Really? I'll miss you.(寂しくなるなあ)のような気持ちをそえるのが自然。"}
],
station:[
{id:'g4-station-001',legacyIndex:0,d:1,jp:"私は毎朝7時に起きます。",words:["I","get","up","at","seven","every morning"],e:"起きる=get up。時刻の前に at を置く(I get up at seven)。"},
{id:'g4-station-002',legacyIndex:1,d:1,jp:"彼女は水泳が得意です。",words:["She","is","good","at","swimming"],e:"得意=be good at。at のあとは動名詞(-ing)。"},
{id:'g4-station-003',legacyIndex:2,d:1,jp:"あなたはどこに住んでいますか。",words:["Where","do","you","live"],e:"場所の疑問詞 Where + do + 主語 + 動詞の順。"},
{id:'g4-station-004',legacyIndex:3,d:1,jp:"これは私の本です。",words:["This","is","my","book"],e:"This is + 名詞で「これは〜です」。my=私の。"},
{id:'g4-station-005',legacyIndex:4,d:1,jp:"彼は昨日サッカーをしました。",words:["He","played","soccer","yesterday"],e:"yesterday(昨日)があるので過去形 played。"},
{id:'g4-station-006',legacyIndex:5,d:1,jp:"机の上に本が2冊あります。",words:["There","are","two","books","on","the","desk"],e:"There are + 数 + 名詞 + 場所(on the desk)の順番。"},
{id:'g4-station-007',legacyIndex:6,d:1,jp:"私は犬が好きです。",words:["I","like","dogs"],e:"主語+動詞+目的語の基本の語順。好きなものが複数なら dogs。"},
{id:'g4-station-008',legacyIndex:7,d:1,jp:"彼女は毎朝牛乳を飲みます。",words:["She","drinks","milk","every morning"],e:"三人称単数(She)なので drinks に s がつく。"},
{id:'g4-station-009',legacyIndex:8,d:1,jp:"窓を閉めてください。",words:["Please","close","the","window"],e:"命令文は動詞の原形ではじめる。Please をつけるとていねい。"},
{id:'g4-station-010',legacyIndex:9,d:1,jp:"彼はとても背が高いです。",words:["He","is","very","tall"],e:"「背が高い」は He is tall. very で「とても」をくわえる。"},
{id:'g4-station-011',legacyIndex:10,d:1,jp:"私はバスで学校へ行きます。",words:["I","go","to","school","by","bus"],e:"交通手段は by bus / by car。「〜へ行く」は go to 〜。"},
{id:'g4-station-012',legacyIndex:11,d:2,jp:"私の夢は医者になることです。",words:["My","dream","is","to","become","a","doctor"],e:"「〜すること」=to 不定詞。a doctor の a も忘れずに。"},
{id:'g4-station-013',legacyIndex:12,d:2,jp:"彼女は歌うことが好きです。",words:["She","likes","to","sing"],e:"like to do / like doing どちらもOK。ここでは to sing。"},
{id:'g4-station-014',legacyIndex:13,d:2,jp:"あなたはいつ英語を勉強しますか。",words:["When","do","you","study","English"],e:"疑問詞 When を最初に。あとはふつうの疑問文と同じ語順。"},
{id:'g4-station-015',legacyIndex:14,d:2,jp:"その映画はとてもおもしろかったです。",words:["The","movie","was","very","interesting"],e:"be 動詞 + 形容詞。interesting は物事が「おもしろい」。"},
{id:'g4-station-016',legacyIndex:15,d:2,jp:"私はテニスをするのを楽しんでいます。",words:["I","enjoy","playing","tennis"],e:"enjoy のあとは動名詞(-ing)。"},
{id:'g4-station-017',legacyIndex:16,d:2,jp:"そこまで歩いて10分かかります。",words:["It","takes","ten","minutes","to","walk","there"],e:"It takes + 時間 + to do(〜するのに時間がかかる)。"},
{id:'g4-station-018',legacyIndex:17,d:2,jp:"彼は背が高くて親切です。",words:["He","is","tall","and","kind"],e:"形容詞をつなぐ and。tall and kind の順が自然。"},
{id:'g4-station-019',legacyIndex:18,d:2,jp:"どうやってその店に行きますか。",words:["How","do","I","get","to","the","store"],e:"道順を聞く How do I get to 〜?(〜へはどうやって行くの?)" },
{id:'g4-station-020',legacyIndex:19,d:2,jp:"私たちの先生はとても親切です。",words:["Our","teacher","is","very","kind"],e:"Our(私たちの)+ 名詞。kind=親切な。"},
{id:'g4-station-021',legacyIndex:20,d:2,jp:"彼女は今、昼ごはんを食べています。",words:["She","is","eating","lunch","now"],e:"今していること=現在進行形 is eating。now は文のおわりへ。"},
{id:'g4-station-022',legacyIndex:21,d:2,jp:"週末に何をしましたか。",words:["What","did","you","do","last","weekend"],e:"過去の疑問文は did + 主語 + 動詞の原形。"},
{id:'g4-station-023',legacyIndex:22,d:2,jp:"このかばんは私のです。",words:["This","bag","is","mine"],e:"「私のもの」は所有代名詞 mine(my bag = mine)。"},
{id:'g4-station-024',legacyIndex:23,d:3,jp:"その知らせを聞いて、私はうれしかった。",words:["I","was","glad","to","hear","the","news"],e:"感情の言葉 + to 不定詞(be glad to do=できてうれしい)。"},
{id:'g4-station-025',legacyIndex:24,d:3,jp:"雨がふっていたので、私は家にいました。",words:["I","stayed","home","because","it","was","raining"],e:"because のあとに理由の文。ふっていた=過去進行形 was raining。"},
{id:'g4-station-026',legacyIndex:25,d:3,jp:"彼は私にその本を読むように言いました。",words:["He","told","me","to","read","the","book"],e:"tell 人 to do(人に〜するよう言う)。"},
{id:'g4-station-027',legacyIndex:26,d:3,jp:"その山は日本でいちばん高い山です。",words:["That","mountain","is","the","highest","in","Japan"],e:"範囲が日本=in Japan。最上級 the highest。"},
{id:'g4-station-028',legacyIndex:27,d:3,jp:"自転車を見せてもらえますか。",words:["Could","you","show","me","your","bike"],e:"Could you show me 〜?(見せてくれますか)show 人 もの。"},
{id:'g4-station-029',legacyIndex:28,d:3,jp:"私は毎日練習しなければなりません。",words:["I","must","practice","every","day"],e:"must + 動詞の原形(〜しなければならない)。"},
{id:'g4-station-030',legacyIndex:29,d:3,jp:"その公園は思っていたよりも広いです。",words:["The","park","is","bigger","than","I","expected"],e:"比較級 + than I expected(思っていたより)。"},
{id:'g4-station-031',legacyIndex:30,d:3,jp:"宿題を終えたら遊びましょう。",words:["Let's","play","after","you","finish","your","homework"],e:"after + 主語 + 動詞で「〜したあとに」。"},
{id:'g4-station-032',legacyIndex:31,d:3,jp:"何か熱い飲み物がほしいです。",words:["I","want","something","hot","to","drink"],e:"something + 形容詞 + to do。形容詞は後ろに置くのがルール!"},
{id:'g4-station-033',legacyIndex:32,d:3,jp:"彼はクラスでいちばん背が高い。",words:["He","is","the","tallest","in","his","class"],e:"範囲がクラス=in his class。最上級 the tallest。"}
],
park:[
{id:'g4-park-001',legacyIndex:0,d:1,t:'pic',say:"Ken plays soccer every Sunday.",s:["👦⚽","👦⚾","👦🏀","👦🎾"],a:0,e:"音声の内容「ケンは毎週日曜日にサッカーをします」。soccer=サッカー⚽"},
{id:'g4-park-002',legacyIndex:1,d:1,t:'pic',say:"Mary is watering the flowers.",s:["🌸💧","🌸✂️","🌸👃","🌸🎁"],a:0,e:"watering the flowers=花に水をあげている。water は動詞でも使える!"},
{id:'g4-park-003',legacyIndex:2,d:1,t:'pic',say:"My father is driving a car.",s:["👨🚗","👨🚲","👨🏊","👨🍳"],a:0,e:"driving a car=車を運転している。drive は運転する。"},
{id:'g4-park-004',legacyIndex:3,d:1,t:'pic',say:"There are two apples on the table.",s:["🍎🍎🪑","🍌🍌🪑","🍇🍇🪑","🍓🍓🪑"],a:0,e:"two apples=りんご2つ。apples が複数なので There ARE。"},
{id:'g4-park-005',legacyIndex:4,d:1,t:'pic',say:"Emily is wearing a crown.",s:["👧👑","👧🎩","👧🧣","👧👒"],a:0,e:"wearing a crown=王冠をかぶっている。crown=王冠、hat=帽子。"},
{id:'g4-park-006',legacyIndex:5,d:1,t:'pic',say:"The bird is flying in the sky.",s:["🐦☁️","🐧❄️","🐔🏠","🦆💧"],a:0,e:"flying in the sky=空を飛んでいる。fly は飛ぶ。"},
{id:'g4-park-007',legacyIndex:6,d:1,t:'pic',say:"Jack is brushing his teeth.",s:["🪥👦","🧼🛁👦","👕👔👦","🛏️😴👦"],a:0,e:"brushing his teeth=歯をみがいている。brush=みがく、teeth=tooth(歯)の複数形。"},
{id:'g4-park-008',legacyIndex:7,d:1,t:'pic',say:"We eat lunch at noon.",s:["🕛🍱","🌅🍳","🌙🍛","🌃🍿"],a:0,e:"noon=正午(12時)。lunch は昼ごはん。"},
{id:'g4-park-009',legacyIndex:8,d:1,t:'pic',say:"Lisa is talking on the phone.",s:["📞👧","📺👧","🎧👧","📖👧"],a:0,e:"talking on the phone=電話で話している。"},
{id:'g4-park-010',legacyIndex:9,d:1,t:'pic',say:"The bus stops near the bank.",s:["🚌🏦","🚗🏪","✈️🏖️","🚲⛲"],a:0,e:"bank=銀行。bus stops near the bank=バスが銀行の近くにとまる。"},
{id:'g4-park-011',legacyIndex:10,d:1,t:'pic',say:"Tom is sleeping on the sofa.",s:["😴🛋️","🍚🍴","⚽🏃","📚✏️"],a:0,e:"sleeping on the sofa=ソファでねている。sofa=ソファ。"},
{id:'g4-park-012',legacyIndex:11,d:2,t:'qa',say:"Hi, Emma! Where are you going? I'm going to the library to return some books.",q:"Where is Emma going?",s:["To the library.","To the bookstore.","To her school.","To the park."],a:0,e:"return some books=本を返すために library(図書館)へ行きます。"},
{id:'g4-park-013',legacyIndex:12,d:2,t:'qa',say:"Wow, what a big dog! Is it yours? Yes, my uncle gave him to me last month.",q:"Who gave the dog to the boy?",s:["His uncle.","His friend.","His teacher.","His grandmother."],a:0,e:"my uncle gave him to me=おじさんが犬をくれた、と言っています。"},
{id:'g4-park-014',legacyIndex:13,d:2,t:'qa',say:"Do you want to play tennis this afternoon? I'd love to, but I have to practice the piano.",q:"What will the girl do this afternoon?",s:["Practice the piano.","Play tennis.","Watch a game.","Clean her room."],a:0,e:"I'd love to, but ...=行きたいけど、と断って piano の練習をしなければならないと言っています。"},
{id:'g4-park-015',legacyIndex:14,d:2,t:'qa',say:"Excuse me, when does the museum open? At nine, but today it opens at ten because it's Monday.",q:"What time does the museum open today?",s:["At ten.","At nine.","At eleven.","At noon."],a:0,e:"ふだんは9時だけど、今日は月曜日なので10時開き(today it opens at ten)。"},
{id:'g4-park-016',legacyIndex:15,d:2,t:'qa',say:"Mom, can I have some ice cream? Sure, but finish your vegetables first.",q:"What must the boy do first?",s:["Eat his vegetables.","Eat ice cream.","Wash his hands.","Set the table."],a:0,e:"finish your vegetables first=まず野菜を食べなさい、と言われています。"},
{id:'g4-park-017',legacyIndex:16,d:2,t:'qa',say:"Your new bike looks cool! Thanks. I ride it to school every day now.",q:"How does the boy go to school?",s:["By bike.","By bus.","On foot.","By train."],a:0,e:"ride it to school every day=毎日自転車で学校へ行っています。"},
{id:'g4-park-018',legacyIndex:17,d:2,t:'qa',say:"Are you good at swimming, Kate? Not really, but I enjoy it very much.",q:"What does Kate say about swimming?",s:["She enjoys it but isn't good at it.","She is very good at it.","She doesn't like it at all.","She never swims."],a:0,e:"Not really, but I enjoy it very much.=あまり得意じゃないけど大好き、という意味。"},
{id:'g4-park-019',legacyIndex:18,d:2,t:'qa',say:"Let's make a cake for Dad's birthday. Great idea! I'll buy some strawberries.",q:"What will they make?",s:["A cake.","Cookies.","Pizza.","Salad."],a:0,e:"make a cake for Dad's birthday=お父さんの誕生日にケーキを作る、ということ。"},
{id:'g4-park-020',legacyIndex:19,d:2,t:'qa',say:"Why were you late for school? I missed the bus, and I had to walk.",q:"Why was the girl late?",s:["She missed the bus.","She woke up late.","She forgot her homework.","She was sick."],a:0,e:"missed the bus=バスに乗りおくれたので歩いた、と言っています。"},
{id:'g4-park-021',legacyIndex:20,d:2,t:'qa',say:"What did you do last weekend, Sam? I helped my father wash our car. Then we watched a movie together.",q:"What did Sam do last weekend?",s:["He washed the car and watched a movie.","He played video games all day.","He visited his grandparents.","He studied for a test."],a:0,e:"helped wash our car + watched a movie together の2つのことをしました。"},
{id:'g4-park-022',legacyIndex:21,d:2,t:'qa',say:"How many brothers and sisters do you have? I have one brother and two sisters.",q:"How many brothers and sisters does she have?",s:["Three.","Two.","One.","Four."],a:0,e:"1人のお兄さん(弟)+2人の姉(妹)=合わせて3人。"},
{id:'g4-park-023',legacyIndex:22,d:3,t:'qa',say:"Hello, everyone. This is your school radio club. Today we have good news. Our basketball team won the city tournament. Let's cheer for them at Friday's assembly.",q:"What is the main topic of this announcement?",s:["The basketball team's victory.","The school festival.","A new radio program.","Friday's classes."],a:0,e:"won the city tournament(市の大会で優勝した)がメインの話題。cheer for them=応援する。"},
{id:'g4-park-024',legacyIndex:23,d:3,t:'qa',say:"Hi, Lucy. This is Mike. I'm calling about tomorrow's picnic. Let's meet at ten instead of nine, because it will rain in the morning. See you there!",q:"What time will they meet?",s:["At ten.","At nine.","At eleven.","At noon."],a:0,e:"instead of nine(9時のかわりに)=at ten(10時に会う)に変更しています。"},
{id:'g4-park-025',legacyIndex:24,d:3,t:'qa',say:"Attention, shoppers. Our store will close at six o'clock today instead of eight. We're sorry for any trouble. Please visit us again tomorrow morning at nine.",q:"What time does the store usually close?",s:["At eight.","At six.","At nine.","At seven."],a:0,e:"今日は6時閉店(instead of eight=ふだんの8時のかわり)。usually close=ふだんの閉店時刻を聞いています。"},
{id:'g4-park-026',legacyIndex:25,d:3,t:'qa',say:"Dear students, the library will be closed this Saturday for cleaning. But don't worry. You can return your books in the box outside the door. Thank you!",q:"What should students do with their books on Saturday?",s:["Put them in the box outside.","Keep them at home until Monday.","Bring them to the office.","Return them next month."],a:0,e:"the box outside the door=ドアの外の箱に返すように言っています。"},
{id:'g4-park-027',legacyIndex:26,d:3,t:'qa',say:"Welcome to Green Valley Zoo! Remember, please do not feed the animals. Our animals eat special food, and other food can make them sick. Enjoy your visit!",q:"What are visitors told NOT to do?",s:["Feed the animals.","Take pictures.","Touch the goats.","Buy food."],a:0,e:"do not feed the animals=動物にえさをあげないで。feed=えさをあげる。"},
{id:'g4-park-028',legacyIndex:27,d:3,t:'qa',say:"Hey, Jenny! I found your science notebook in the music room. I put it in your classroom desk, so please check there. If it's not there, call me tonight.",q:"Where did the speaker find the notebook?",s:["In the music room.","In the library.","In the gym.","In the classroom."],a:0,e:"見つけたのは音楽室(music room)、置いたのが教室の机です。場所を聞かれているのに注意!"},
{id:'g4-park-029',legacyIndex:28,d:3,t:'qa',say:"Our class trip to the science museum has changed. We will go next Thursday, not Tuesday. Please bring your permission slips by tomorrow. Thank you.",q:"When will the class go to the museum?",s:["Next Thursday.","Next Tuesday.","Tomorrow.","Next Monday."],a:0,e:"next Thursday, not Tuesday=火曜日ではなく来週の木曜日に行きます。"},
{id:'g4-park-030',legacyIndex:29,d:3,t:'qa',say:"Good morning! This is today's weather forecast. It will be sunny and warm all day today. But take your umbrella tomorrow because it will rain.",q:"What will the weather be like tomorrow?",s:["Rainy.","Sunny.","Snowy.","Cloudy."],a:0,e:"明日は umbrella(かさ)が必要=rain(雨)。今日は晴れです。"},
{id:'g4-park-031',legacyIndex:30,d:3,t:'qa',say:"Mom, this is Amy. I'm at my friend Sarah's house, and we're studying together. Don't worry about dinner. I'll be home by seven.",q:"When will Amy be home?",s:["By seven.","By six.","By eight.","By nine."],a:0,e:"by seven=7時までには帰る、という意味。"},
{id:'g4-park-032',legacyIndex:31,d:3,t:'qa',say:"Boys and girls, tomorrow's swimming lesson is canceled because the pool is being cleaned. Instead, we'll watch a video about ocean animals in the classroom.",q:"What will students do tomorrow?",s:["Watch a video about ocean animals.","Swim in the pool.","Clean the pool.","Visit the ocean."],a:0,e:"プールのそうじのため水泳の授業は中止。代わりに教室でビデオを見ます。"},
{id:'g4-park-033',legacyIndex:32,d:3,t:'qa',say:"Thank you for calling Sunny Bakery. We're open from eight to six, Monday through Saturday. We're closed on Sundays. Our fresh bread comes out at noon every day.",q:"When is the bakery closed?",s:["On Sundays.","On Mondays.","On Saturdays.","Every day at noon."],a:0,e:"We're closed on Sundays.=日曜日はお休みです。"}
],
flower:[
{id:'g4-flower-001',legacyIndex:0,d:1,en:"What is your favorite food? Why?",jp:"すきな食べ物と、その理由を書こう。",hints:["My favorite food is ...","It is (very / sweet / hot / good).","I eat it ..."],sample:"My favorite food is ramen. It is very hot and delicious. I eat it with my family on cold winter days."},
{id:'g4-flower-002',legacyIndex:1,d:1,en:"What did you do last weekend?",jp:"しゅうまつにしたことを過去形で書こう。",hints:["Last weekend, I ...","I went to ... / I played ...","It was fun."],sample:"Last weekend, I went to the park with my friends. We played badminton and ate ice cream there. It was so much fun."},
{id:'g4-flower-003',legacyIndex:2,d:1,en:"What is your favorite subject at school? Why?",jp:"すきな教科と理由を書こう。",hints:["My favorite subject is ...","I like ... because ...","The teacher is kind."],sample:"My favorite subject is music. I like singing songs with my friends. Music makes me happy every day."},
{id:'g4-flower-004',legacyIndex:3,d:1,en:"Do you have a pet? What is it like?",jp:"ペットについて書こう。(いない場合はほしいペットでもOK)",hints:["Yes, I have a ... / No, but I want a ...","His/Her name is ...","He/She likes to ..."],sample:"Yes, I have a cat. Her name is Momo. She is white and very small. She sleeps on my bed every night."},
{id:'g4-flower-005',legacyIndex:4,d:1,en:"What time do you get up on weekdays? Tell us about your morning.",jp:"平日の朝のじかん割を書こう。",hints:["I get up at ... on weekdays.","First, I ... Then, I ...","I go to school by ..."],sample:"I get up at seven on weekdays. First, I wash my face and eat breakfast. Then I go to school by bus with my brother."},
{id:'g4-flower-006',legacyIndex:5,d:1,en:"What is your favorite season? Why?",jp:"すきな季節と理由を書こう。",hints:["My favorite season is ...","I can swim / ski / see flowers.","It is not too hot or cold."],sample:"My favorite season is summer. I like it because I can swim in the sea. I also love summer festivals with fireworks."},
{id:'g4-flower-007',legacyIndex:6,d:1,en:"Who is your best friend? What do you do together?",jp:"だいすきな友だちといっしょにすることを書こう。",hints:["My best friend is ...","We play ... / We talk about ...","He/She always helps me."],sample:"My best friend is Yuki. We play video games and talk about comics a lot. She always helps me when I am sad."},
{id:'g4-flower-008',legacyIndex:7,d:1,en:"What do you usually eat for breakfast?",jp:"いつも朝ごはんで食べるものを書こう。",hints:["I usually eat ...","Sometimes I eat ...","Breakfast gives me energy."],sample:"I usually eat rice, eggs, and miso soup. Sometimes I eat toast with jam on busy mornings. Breakfast gives me energy for school."},
{id:'g4-flower-009',legacyIndex:8,d:2,en:"What do you like to do on sunny days?",jp:"晴れの日にしたいことを書こう。",hints:["On sunny days, I like to ...","I often ... with my friends.","After that, we ..." ],sample:"I like to ride my bike in the park on sunny days. After that, I often buy ice cream and talk with my friends near the station."},
{id:'g4-flower-010',legacyIndex:9,d:2,en:"What is your favorite place in your town? Why?",jp:"自分の町のすきな場所と理由を書こう。",hints:["My favorite place is ... in my town.","It is quiet / fun / beautiful.","I go there ..." ],sample:"My favorite place is the library in my town. It is quiet, and there are many interesting books. I go there every Saturday morning."},
{id:'g4-flower-011',legacyIndex:10,d:2,en:"Tell us about your club activity or favorite hobby.",jp:"部活や趣味について書こう。",hints:["I am in the ... club. / My hobby is ...","We practice / draw / play ...","Last month, we ..." ],sample:"I am in the art club at school. We draw pictures and paint every Tuesday after class. Last month, we showed our works at the school festival."},
{id:'g4-flower-012',legacyIndex:11,d:2,en:"What do you want to be in the future? Why?",jp:"将来なりたいものと理由を書こう。",hints:["I want to be a ... in the future.","Because I like helping / cooking / animals.","My dream is to ..." ],sample:"I want to be a nurse because I like helping people. My aunt is a nurse, and she always looks happy at work. I want to be like her."},
{id:'g4-flower-013',legacyIndex:12,d:2,en:"Describe one of your family members.",jp:"家族のだれかについて書こう。",hints:["My ... is ... years old.","He/She likes ...","Every night/day, we ..." ],sample:"My little brother is five years old. He likes dinosaurs very much. Every night, we read dinosaur books together before going to bed."},
{id:'g4-flower-014',legacyIndex:13,d:2,en:"What did you do last summer vacation?",jp:"夏休みにしたことを書こう。",hints:["In summer vacation, I went to ...","We caught / swam / climbed ...","It was exciting!" ],sample:"In summer vacation, I went to my grandfather's house in Nagano. We caught fish in the river and climbed a small mountain. It was exciting."},
{id:'g4-flower-015',legacyIndex:14,d:2,en:"Do you like rainy days? Why or why not?",jp:"雨の日がすきか、理由もいっしょに書こう。",hints:["Yes, I do. / No, I don't.","On rainy days, I stay home and ...","Because I can ..." ],sample:"Yes, I like rainy days. On rainy days, I stay home and read manga or watch movies with my family. It is very relaxing for me."},
{id:'g4-flower-016',legacyIndex:15,d:2,en:"What is your favorite movie or TV show? Why?",jp:"すきな映画や番組と理由を書こう。",hints:["My favorite movie/show is ...","The songs/story/characters are ...","I have seen it ..." ],sample:"My favorite movie is Frozen. The songs are wonderful, and the story is very exciting. I have seen it five times with my sister."},
{id:'g4-flower-017',legacyIndex:16,d:3,en:"Some people like team sports, and others like solo sports. Which do you prefer? Why?",jp:"団体競技と個人競技、どちらが好きか書こう。",hints:["I prefer team sports / solo sports.","When we win, I feel ...","I can share the joy with ..." ],sample:"I prefer team sports like soccer. When we win a game, I feel really happy, and I can share the joy with my teammates. It makes sports more fun."},
{id:'g4-flower-018',legacyIndex:17,d:3,en:"Should students have more homework? What do you think?",jp:"宿題はもっと増えるべきか、意見と理由を書こう。",hints:["I don't think so. / I think so.","Students need time to ...","If we have too much homework, ..." ],sample:"I don't think students should have more homework. Students need time to play sports and enjoy hobbies. If we have too much homework, we cannot relax after school."},
{id:'g4-flower-019',legacyIndex:18,d:3,en:"If you had one million yen, what would you do?",jp:"100万円あったら何をするか書こう。",hints:["If I had one million yen, I would ...","I want to see / buy / help ...","First, I would ... Then ..." ],sample:"If I had one million yen, I would travel around the world with my family. I want to see famous places and try many local foods in different countries."},
{id:'g4-flower-020',legacyIndex:19,d:3,en:"Which do you like better, reading books or watching videos? Why?",jp:"本を読むことと動画を見ること、どちらが好きか理由も書こう。",hints:["I like watching videos better.","They are fun and easy to understand.","But I know reading books helps me ..." ],sample:"I like watching videos better because they are fun and easy to understand. But I know reading books helps me learn new words, so I try to read books too."},
{id:'g4-flower-021',legacyIndex:20,d:3,en:"What is the most important thing for a happy life? Why?",jp:"幸せな生活にいちばん大切なことは何か書こう。",hints:["For me, ... is the most important thing.","They always support/help me.","I can talk to them about anything." ],sample:"For me, family is the most important thing in life. They always support me, and I can talk to them about anything. When I am sad, they make me smile again."},
{id:'g4-flower-022',legacyIndex:21,d:3,en:"If your friend is very sad, what should you do?",jp:"友だちがかなしいとき、どうすればいいか書こう。",hints:["First, I listen to ...","Then I stay with / cheer up ...","Small gifts or jokes make them ..." ],sample:"First, I listen to my friend's story carefully. Then I stay with them, or sometimes I cheer them up with a small gift or a funny joke. Being together is important."},
{id:'g4-flower-023',legacyIndex:22,d:3,en:"What kind of town do you want to live in the future?",jp:"将来住みたい町について書こう。",hints:["I want to live in a town with ...","People can walk safely / neighbors are friendly.","There are many parks/shops." ],sample:"I want to live in a green town with many trees and parks. People can walk safely everywhere, and neighbors are friendly to each other. It sounds wonderful."},
{id:'g4-flower-024',legacyIndex:23,d:3,en:"Do you think robots will be good for our future? Why?",jp:"ロボットは未来に役立つと思うか、理由を書こう。",hints:["Yes, I think so. / No, I don't think so.","Robots can help doctors / old people.","But we should learn how to ..." ],sample:"Yes, I think robots will be good for our future. Robots can help doctors and take care of old people. But we should also learn how to use them well."}
]
},
});
Object.assign(PRACTICE_PASSAGES, {
'g4-reading-notice-1':"School Garden Day\nPlease join us in the school garden this Saturday. We will plant flowers from nine to eleven in the morning. Bring a hat and some water. You do not need any tools. Meet Mr. Hill at the garden gate.",
'g4-reading-notice-2':"Town Library Drawing Class\nOur drawing class starts at two on Sunday afternoon in Room Three. You can draw your favorite animal. Please bring colored pencils. Paper is free. Call the library by Friday to join. The class is for children aged ten to fourteen.",
'g4-reading-email-1':"Hi Rina,\nThank you for inviting me to lunch on Saturday. I can come to your house at twelve. My brother has a soccer game that morning, so my father will drive me to your house after the game. I will bring some apple juice. Can we make sandwiches together? I want to learn your special recipe.\nSee you soon,\nMeg",
'g4-reading-email-2':"Hi Leo,\nI visited the new sports shop with my mother yesterday. I needed shoes for tennis, but the tennis shoes were too expensive. I bought a blue cap instead. The shop also has some good bags. You need a bag for swimming, right? Let's go there after school on Wednesday. It is next to the post office.\nYour friend,\nDan",
'g4-reading-story-1':"Aya likes animals, but she does not have a pet. Last month, her neighbor Mrs. Green went to another town for three days. She asked Aya to feed her rabbit.\nEvery morning, Aya walked to Mrs. Green's house before school. She gave the rabbit fresh water and food. On the second day, Aya could not find the rabbit in its box. She looked around the room and found it under a chair.\nWhen Mrs. Green came home, she thanked Aya and gave her a book about rabbits. Aya enjoyed the job. Now she wants to learn more about small animals.",
'g4-reading-story-2':"Last Sunday, Ben and his sister Lisa wanted to ride their bikes to a lake. When they woke up, it was raining. They decided to stay home and cook lunch for their parents.\nBen found a recipe for vegetable soup in a cookbook. Lisa washed the carrots and potatoes, and Ben cut them. They cooked the vegetables in a big pot. Their father came into the kitchen and helped them make bread.\nAt noon, the family ate together. Their mother liked the soup very much. In the afternoon, the rain stopped. Ben and Lisa took a short walk instead of riding their bikes.",
'g4-reading-notice-3':"School Book Fair\nOur school book fair is on Friday and Saturday in the school library. It is open from ten in the morning to four in the afternoon. You can buy old books for fifty yen. New books cost three hundred yen. Please bring your own bag.",
 'g4-reading-email-3':"Hi Sara,\nThank you for your birthday card. I was very happy. My birthday party is next Sunday at my house. It starts at two in the afternoon. My mother will make a big cake. Can you come? Please tell me by Friday. I want to play games with you.\nYour friend,\nNana",
'g4-reading-email-4':"Hi Tom,\nHow are you? Last weekend, I went camping with my family. We stayed in a tent near a lake for two nights. My father cooked fish outside, and my sister and I swam in the lake. It was cold but fun. Next time, let's go together.\nYour friend,\nHiro",
'g4-reading-story-3':"Mika lost her red pencil box yesterday morning. She looked in her desk and in her bag, but she could not find it. After school, she went back to the classroom with her friend Yui. They looked under the desks. At last, Yui found the box behind a bookshelf.\nMika was very happy. She opened the box and found all her pencils. She said thank you to Yui many times. On the way home, Mika bought two donuts and gave one to Yui.",
'g4-reading-story-4':"Last winter, Ryo's grandmother taught him how to make paper planes. They made ten planes together on a snowy afternoon. Ryo's best plane flew across the garden. It landed on a tall tree.\nRyo wanted his plane back, so his father brought a long ladder. Ryo climbed up and got the plane. He was a little afraid, but he was very happy. Now Ryo can make paper planes well, and he teaches his little sister.",
});
Object.assign(QUESTION_BANKS, {
'4': {
library:[
{id:'g4-library-101',d:1,q:"My aunt helps sick people in a hospital. She is a ___.",c:["farmer","nurse","singer","driver"],a:1,e:"「おばは病院で病気の人を助けます。看護師です」。nurse は看護師。"},
{id:'g4-library-102',d:1,q:"A: Can I ___ your dictionary? I'll give it back tomorrow.\nB: Sure.",c:["sell","wash","borrow","break"],a:2,e:"「辞書を借りてもいい？明日返すよ」。borrow は借りる。give it back は返す。"},
{id:'g4-library-103',d:1,q:"The soup is very ___. Wait a minute before you eat it.",c:["empty","young","late","hot"],a:3,e:"「スープはとても熱いです。食べる前に少し待って」。hot は熱い。"},
{id:'g4-library-104',d:1,q:"Please write your name at the ___ of the page, above the first question.",c:["top","bottom","back","end"],a:0,e:"「最初の問題より上、ページの上部に名前を書いて」。top は上部。above は〜より上に。"},
{id:'g4-library-105',d:1,q:"I didn't eat breakfast, so I am very ___ now. Let's have lunch.",c:["full","hungry","rich","famous"],a:1,e:"「朝食を食べなかったので今とてもおなかがすいています」。hungry は空腹の。"},
{id:'g4-library-106',d:1,q:"A: How did you get to the island?\nB: We went there by ___.",c:["kitchen","ticket","boat","airport"],a:2,e:"「島へどうやって行きましたか」「船で行きました」。by boat は船で。airport は空港で、乗り物ではない。"},
{id:'g4-library-107',d:2,q:"My sister is ___ of spiders. She runs away when she sees one.",c:["ready","different","late","afraid"],a:3,e:"「姉はクモを怖がります。見つけると逃げます」。be afraid of は〜を怖がる。"},
{id:'g4-library-108',d:2,q:"A: Please ___ your camera. We can take pictures at the zoo.\nB: OK.",c:["bring","lose","eat","close"],a:0,e:"「カメラを持ってきて。動物園で写真を撮れるよ」。bring は持ってくる。"},
{id:'g4-library-109',d:2,q:"We need to ___ the bus at the next stop. Our school is there.",c:["look for","get off","take care of","listen to"],a:1,e:"「次の停留所でバスを降りる必要があります。学校はそこです」。get off は乗り物から降りる。"},
{id:'g4-library-110',d:2,q:"Tom cannot find his key. He is looking ___ it in his room.",c:["after","like","for","at"],a:2,e:"「トムは鍵が見つからず、部屋で探しています」。look for は探す。look at は見る、look after は世話をする。"},
{id:'g4-library-111',d:2,q:"The movie begins at six and ___ at eight. It is two hours long.",c:["grows","opens","arrives","ends"],a:3,e:"「映画は6時に始まり8時に終わります。2時間です」。end は終わる。"},
{id:'g4-library-112',d:2,q:"A: May I ask you a question?\nB: Of ___. What is it?",c:["course","weather","minute","place"],a:0,e:"「質問してもいいですか」「もちろん。何ですか」。Of course はもちろん。"},
{id:'g4-library-113',d:3,q:"This bag costs only 500 yen. It is much ___ than that 3,000-yen bag.",c:["heavier","cheaper","slower","taller"],a:1,e:"「このかばんは500円だけで、3,000円のかばんよりずっと安い」。cheaper はより安い。"},
{id:'g4-library-114',d:3,q:"Please ___ to bring your notebook tomorrow. You will need it in class.",c:["invite","arrive","remember","happen"],a:2,e:"「明日ノートを持ってくるのを忘れないで。授業で必要です」。remember to は忘れずに〜する。"},
{id:'g4-library-115',d:3,q:"A: How long did you ___ at your uncle's house?\nB: Three nights.",c:["send","carry","reach","stay"],a:3,e:"「おじさんの家にどのくらい泊まりましたか」「3泊です」。stay at は〜に滞在する。"},
{id:'g4-library-116',d:3,q:"I want to send this letter to Canada. Where can I buy a ___ for it?",c:["stamp","seat","meal","coat"],a:0,e:"「手紙をカナダに送りたいです。切手はどこで買えますか」。stamp は切手。"},
{id:'g4-library-117',d:3,q:"Walk ___ across the icy road. It is easy to fall there.",c:["loudly","carefully","angrily","heavily"],a:1,e:"「凍った道は転びやすいので注意して渡って」。carefully は注意深く。"},
{id:'g4-library-118',d:3,q:"A: What is the ___ between these two bags?\nB: This one has two pockets, but that one has none.",c:["vacation","medicine","difference","temperature"],a:2,e:"「この二つのかばんの違いは何ですか」「こちらはポケットが二つ、あちらはありません」。difference は違い。"},
{id:'g4-library-119',d:1,q:"It is very ___ today. Take an umbrella with you.",c:["rainy","hungry","late","famous"],a:0,e:"「今日はとても雨です。傘を持って行きなさい」。rainy は雨の。take an umbrella は傘を持つ。"},
{id:'g4-library-120',d:1,q:"My father works in a ___. He teaches math to children.",c:["school","hospital","station","bank"],a:0,e:"「父は学校で働き、子どもに算数を教えます」。teach は教える。"},
{id:'g4-library-121',d:1,q:"There are four ___ in a year: spring, summer, fall, and winter.",c:["seasons","weeks","hours","minutes"],a:0,e:"「1年には春夏秋冬の4つの季節があります」。season は季節。"},
{id:'g4-library-122',d:1,q:"A: ___ is your birthday?\nB: It's on May 3rd.",c:["When","Where","What","Which"],a:0,e:"「誕生日はいつですか」「5月3日です」。日付を聞くのは When。"},
{id:'g4-library-123',d:1,q:"My grandmother is very ___ to us. She always smiles.",c:["kind","cold","late","far"],a:0,e:"「祖母は私たちにとても優しいです。いつも笑っています」。kind は親切な。"},
{id:'g4-library-124',d:1,q:"I ___ my teeth every morning and every night.",c:["brush","drink","open","close"],a:0,e:"「毎朝毎晩歯をみがきます」。brush one's teeth で歯をみがく。"},
{id:'g4-library-125',d:2,q:"The movie ___ at nine, so let's hurry.",c:["starts","finishes","opens","closes"],a:0,e:"「映画は9時に始まるので急ぎましょう」。start は始まる。finish は終える。"},
{id:'g4-library-126',d:2,q:"She ___ her grandmother every Sunday.",c:["visits","misses","watches","helps"],a:0,e:"「彼女は毎週日曜に祖母を訪ねます」。visit は訪ねる。every Sunday で習慣。"},
{id:'g4-library-127',d:2,q:"Please be ___! The baby is sleeping.",c:["quiet","noisy","bright","dark"],a:0,e:"「静かにして!赤ちゃんが寝ています」。quiet は静かな。be quiet で静かにして。"},
{id:'g4-library-128',d:2,q:"My uncle ___ me a postcard from Hokkaido.",c:["sent","bought","made","read"],a:0,e:"「おじは北海道から絵はがきを送ってくれました」。send の過去形 sent は送った。"},
{id:'g4-library-129',d:2,q:"A: ___ do you go to the library?\nB: Three times a week.",c:["How often","How long","How far","How soon"],a:0,e:"「どのくらいの頻度で図書館へ行きますか」「週3回です」。頻度は How often。"},
{id:'g4-library-130',d:2,q:"It took us two hours to ___ the top of the mountain.",c:["reach","arrive","come","go"],a:0,e:"「山頂に着くのに2時間かかりました」。reach + 場所で〜に着く。arrive は at が要る。"},
{id:'g4-library-131',d:3,q:"The test was ___ than I expected, so I finished it quickly.",c:["easier","easy","easiest","more easy"],a:0,e:"「テストは思ったより易しかったので早く終えた」。than で比べるので比較級 easier。more easy は誤り。"},
{id:'g4-library-132',d:3,q:"She has lived in this town ___ she was five years old.",c:["since","for","from","until"],a:0,e:"「彼女は5歳のときからこの町に住んでいます」。時点を表す since + 過去の文。"},
{id:'g4-library-133',d:3,q:"A: Have you finished your homework ___?\nB: Yes, just now.",c:["yet","already","ever","never"],a:0,e:"「宿題はもう終えた?」「うん、たった今」。完了の疑問文の文末は yet。"},
{id:'g4-library-134',d:3,q:"This is the ___ interesting book I have ever read.",c:["most","more","much","many"],a:0,e:"「これは今まで読んだ中でいちばん面白い本です」。the most + 長い形容詞で最上級。"},
{id:'g4-library-135',d:3,q:"If it ___ tomorrow, the game will be canceled.",c:["rains","rain","will rain","rained"],a:0,e:"「明日雨が降れば試合は中止です」。If の中は現在形 rains。will は使わない。"},
{id:'g4-library-136',d:3,q:"The teacher asked us to be quiet ___ the test.",c:["during","while","between","among"],a:0,e:"「先生はテスト中は静かにするよう求めた」。during + 名詞で〜の間。while の後は文。"}
],
school:[
{id:'g4-school-101',d:1,q:"We ___ the science museum yesterday.",c:["visit","visits","visited","visiting"],a:2,e:"「昨日、科学博物館を訪れました」。yesterday で過去の話なので visited。"},
{id:'g4-school-102',d:1,q:"Yuki ___ at home last Sunday. She was at the beach all day.",c:["isn't","aren't","weren't","wasn't"],a:3,e:"「ユキは先週の日曜、家にいませんでした。一日中海辺にいました」。単数の過去の否定は wasn't。"},
{id:'g4-school-103',d:1,q:"Did your father ___ this picture last week?",c:["draw","drew","draws","drawing"],a:0,e:"「お父さんは先週この絵を描きましたか」。Did の後は動詞の原形 draw。"},
{id:'g4-school-104',d:1,q:"We are going to ___ a cake tomorrow.",c:["made","make","makes","making"],a:1,e:"「明日ケーキを作る予定です」。be going to の後は動詞の原形 make。"},
{id:'g4-school-105',d:1,q:"These shoes are ___ than those shoes.",c:["small","smallest","smaller","the smallest"],a:2,e:"「この靴はあの靴より小さい」。than で比べるので比較級 smaller。"},
{id:'g4-school-106',d:1,q:"I couldn't ___ the door this morning because I didn't have my key.",c:["opened","opening","opens","open"],a:3,e:"「今朝は鍵がなかったのでドアを開けられませんでした」。couldn't の後は原形 open。"},
{id:'g4-school-107',d:2,q:"At eight last night, I ___ studying in my room.",c:["was","am","were","be"],a:0,e:"「昨夜8時、私は部屋で勉強していました」。過去進行形は was studying。I には was。"},
{id:'g4-school-108',d:2,q:"Mina wants ___ a cook in the future.",c:["becomes","to become","became","become"],a:1,e:"「ミナは将来料理人になりたい」。want to + 原形で〜したい。"},
{id:'g4-school-109',d:2,q:"My brothers enjoy ___ model planes together.",c:["make","made","making","to make"],a:2,e:"「兄弟は一緒に模型の飛行機を作ることを楽しみます」。enjoy の後は動名詞 making。"},
{id:'g4-school-110',d:2,q:"A: Why did you stay home yesterday?\nB: ___ I had a fever.",c:["Until","Before","Or","Because"],a:3,e:"「なぜ昨日家にいたの」「熱があったから」。Why への理由は Because で答える。"},
{id:'g4-school-111',d:2,q:"A: Must I bring lunch tomorrow?\nB: No, you ___. We will buy sandwiches.",c:["don't have to","mustn't","can't","shouldn't"],a:0,e:"「明日昼食を持参しないといけませんか」「いいえ、必要ありません。サンドイッチを買います」。必要がないのは don't have to。mustn't は禁止。"},
{id:'g4-school-112',d:2,q:"There ___ be a concert in our town next month.",c:["was","will","are","did"],a:1,e:"「来月、町でコンサートがあります」。There will be で未来にあることを表す。"},
{id:'g4-school-113',d:3,q:"This question is ___ difficult than the first one.",c:["most","many","more","much"],a:2,e:"「この問題は最初の問題より難しい」。長い形容詞 difficult の比較級は more difficult。"},
{id:'g4-school-114',d:3,q:"I went to the kitchen ___ some water.",c:["getting","got","get","to get"],a:3,e:"「水をもらうために台所へ行きました」。目的を表す to get は〜を得るために。"},
{id:'g4-school-115',d:3,q:"When Dad came home last night, we ___ watching a movie.",c:["were","are","was","be"],a:0,e:"「昨夜父が帰宅したとき、私たちは映画を見ていました」。we に合う過去進行形は were watching。"},
{id:'g4-school-116',d:3,q:"A: ___ did you stay in Kobe last summer?\nB: For five days.",c:["How far","How long","How many","How old"],a:1,e:"「去年の夏、神戸にどのくらい滞在しましたか」「5日間です」。期間を聞くのは How long。"},
{id:'g4-school-117',d:3,q:"This box is as ___ as that one.",c:["heavier","heaviest","heavy","more heavy"],a:2,e:"「この箱はあの箱と同じくらい重い」。as + 形容詞の原級 + as の形。"},
{id:'g4-school-118',d:3,q:"Thank you for ___ me with my homework yesterday.",c:["help","helped","to help","helping"],a:3,e:"「昨日宿題を手伝ってくれてありがとう」。Thank you for の後は動名詞 helping。"},
{id:'g4-school-119',d:1,q:"I ___ TV with my family last night.",c:["watch","watched","watches","watching"],a:1,e:"「昨夜は家族とテレビを見ました」。last night で過去の話なので watched。"},
{id:'g4-school-120',d:1,q:"There ___ many stars in the sky tonight.",c:["is","are","was","be"],a:1,e:"「今夜は空に星がたくさんあります」。many stars と複数なので are。"},
{id:'g4-school-121',d:1,q:"She ___ to music when I called her.",c:["listens","listened","was listening","is listening"],a:2,e:"「電話したとき彼女は音楽を聞いていました」。そのとき進行中は was listening。"},
{id:'g4-school-122',d:1,q:"My sister ___ swim very well.",c:["can","must","are","does"],a:0,e:"「姉はとても上手に泳げます」。can + 原形で〜できる。"},
{id:'g4-school-123',d:1,q:"This is ___ pen. That one is yours.",c:["my","mine","me","I"],a:0,e:"「これは私のペンです。あれはあなたの」。名詞の前は my。mine は名詞なしで使う。"},
{id:'g4-school-124',d:1,q:"We ___ our grandmother last weekend.",c:["visit","visits","visited","visiting"],a:2,e:"「先週末に祖母を訪ねました」。last weekend で過去の話なので visited。"},
{id:'g4-school-125',d:2,q:"Both of my sisters ___ married.",c:["is","are","was","be"],a:1,e:"「姉妹は二人とも結婚しています」。Both of + 複数には are。"},
{id:'g4-school-126',d:2,q:"A: ___ they busy now?\nB: Yes, very busy.",c:["Is","Are","Was","Be"],a:1,e:"「彼らは今忙しいですか」「はい、とても」。Are they busy の形。"},
{id:'g4-school-127',d:2,q:"She ___ a picture for me yesterday.",c:["draws","drew","drawing","draw"],a:1,e:"「彼女は昨日私に絵を描いてくれた」。yesterday で過去の話なので drew。"},
{id:'g4-school-128',d:2,q:"A: ___ she at home now?\nB: No, she's out.",c:["Is","Does","Are","Was"],a:0,e:"「彼女は今家にいますか」「いいえ、外出中です」。be 動詞の疑問文は Is she。"},
{id:'g4-school-129',d:2,q:"It ___ rain this afternoon. Take an umbrella.",c:["may","must","can","will"],a:0,e:"「午後は雨が降るかもしれません。傘を持って行きなさい」。〜かもしれないは may。"},
{id:'g4-school-130',d:2,q:"The station is ___ the bank and the post office.",c:["between","among","across","through"],a:0,e:"「駅は銀行と郵便局の間にあります」。二つの物の間は between。"},
{id:'g4-school-131',d:3,q:"She ___ tired yesterday.",c:["is","was","are","will be"],a:1,e:"「彼女は昨日疲れていた」。yesterday で過去の話なので was。"},
{id:'g4-school-132',d:3,q:"She ___ her room every morning.",c:["clean","cleans","cleaned","cleaning"],a:1,e:"「彼女は毎朝部屋を掃除する」。She には cleans。every morning で習慣。"},
{id:'g4-school-133',d:3,q:"He is the tallest ___ all.",c:["of","in","at","for"],a:0,e:"「彼はみんなの中でいちばん背が高い」。the tallest of all で全体の中の最上級。"},
{id:'g4-school-134',d:3,q:"My father ___ my mother can cook well.",c:["but","and","or","so"],a:1,e:"「父も母も料理が上手だ」。A and B でAとB。"},
{id:'g4-school-135',d:3,q:"I ___ Ken at the station this morning.",c:["see","sees","saw","seeing"],a:2,e:"「今朝駅でケンに会った」。過去の話なので saw。see は会うの意味もある。"},
{id:'g4-school-136',d:3,q:"We ___ to bed at ten last night.",c:["go","goes","went","going"],a:2,e:"「昨夜10時に寝た」。last night で過去の話なので went。"}
],
cafe:[
{id:'g4-cafe-101',d:1,q:"A: Where did you buy that notebook?\nB: ___",c:["At the station shop.","Last Saturday.","For my sister.","It was 200 yen."],a:0,e:"「そのノートはどこで買ったの」「駅の店で」。Where なので場所で答える。"},
{id:'g4-cafe-102',d:1,q:"A: What did you do after dinner yesterday?\nB: ___",c:["At seven o'clock.","I washed the dishes.","With my parents.","It was delicious."],a:1,e:"「昨日夕食の後、何をしたの」「食器を洗ったよ」。過去の行動を答える。"},
{id:'g4-cafe-103',d:1,q:"A: How was the weather on your trip?\nB: ___",c:["We went by train.","It took two hours.","It was sunny every day.","I stayed with my aunt."],a:2,e:"「旅行中の天気はどうだった」「毎日晴れだったよ」。weather は天気。"},
{id:'g4-cafe-104',d:1,q:"A: What are you going to do this Sunday?\nB: ___",c:["I went there on Sunday.","At the bus stop.","It was a good game.","I'm going to visit my cousin."],a:3,e:"「今度の日曜日は何をする予定」「いとこを訪ねる予定です」。be going to で未来の予定を答える。"},
{id:'g4-cafe-105',d:1,q:"A: Who made this cake?\nB: ___",c:["My older sister did.","It tastes sweet.","In the kitchen.","For the party."],a:0,e:"「誰がこのケーキを作ったの」「姉です」。Who に作った人を答え、did は made this cake の代わり。"},
{id:'g4-cafe-106',d:1,q:"A: Why were you absent yesterday?\nB: ___",c:["At my house.","I had a bad cold.","For two hours.","On Tuesday."],a:1,e:"「なぜ昨日欠席したの」「ひどい風邪をひいていたんだ」。absent は欠席の。理由を答える。"},
{id:'g4-cafe-107',d:2,q:"A: How often do you practice the piano?\nB: ___",c:["For thirty minutes.","At my teacher's house.","Four times a week.","With my sister."],a:2,e:"「どのくらいの頻度でピアノを練習するの」「週4回」。How often は頻度。練習時間の長さではない。"},
{id:'g4-cafe-108',d:2,q:"A: Which is yours, the red bike or the green one?\nB: ___",c:["By bike.","At the bike shop.","My brother can ride it.","The green one is mine."],a:3,e:"「赤と緑、どちらがあなたの自転車」「緑の方が私のです」。mine は私のもの。"},
{id:'g4-cafe-109',d:2,q:"A: How long does it take to walk to the pool?\nB: ___",c:["About fifteen minutes.","About two kilometers.","Every Saturday.","At three o'clock."],a:0,e:"「プールまで歩くとどのくらいかかる」「約15分」。How long does it take は所要時間を聞く。"},
{id:'g4-cafe-110',d:2,q:"A: Excuse me. How can I get to the post office?\nB: ___",c:["It opens at nine.","Go straight and turn right.","I bought two stamps.","My uncle works there."],a:1,e:"「郵便局へはどう行けばいいですか」「まっすぐ行って右に曲がってください」。道順を答える。"},
{id:'g4-cafe-111',d:2,q:"A: What were you doing at six yesterday evening?\nB: ___",c:["Tomorrow evening.","For my grandmother.","I was cooking dinner.","At six thirty."],a:2,e:"「昨日の夕方6時、何をしていたの」「夕食を作っていました」。過去進行形でそのときの動作を答える。"},
{id:'g4-cafe-112',d:2,q:"A: What would you like to drink with your lunch?\nB: ___",c:["A chicken sandwich, please.","At twelve, please.","Two tickets, please.","A glass of milk, please."],a:3,e:"「昼食と一緒に何を飲みますか」「牛乳を1杯ください」。drink なので飲み物を選ぶ。"},
{id:'g4-cafe-113',d:3,q:"A: Why do you like winter better than summer?\nB: ___",c:["Because I enjoy skiing.","Winter comes after fall.","Summer is a season.","For three months."],a:0,e:"「なぜ夏より冬が好きなの」「スキーを楽しめるから」。Why に Because で理由を答える。"},
{id:'g4-cafe-114',d:3,q:"A: What do I need to bring for tomorrow's art class?\nB: ___",c:["In Room Two.","Some colored pencils.","It starts at ten.","Our new teacher."],a:1,e:"「明日の美術の授業に何を持ってくればいい」「色鉛筆だよ」。必要な道具を答える。"},
{id:'g4-cafe-115',d:3,q:"A: Shall we meet at two or three tomorrow?\nB: ___. I have a lesson until two thirty.",c:["Let's meet at two","Let's meet before two","Three is better","Two is better"],a:2,e:"「明日2時と3時、どちらに会おう」「3時の方がいい。2時半までレッスンがある」。理由から3時を選ぶ。"},
{id:'g4-cafe-116',d:3,q:"A: I can't carry this heavy box. Can you help me?\nB: ___",c:["It was an interesting story.","I went there yesterday.","The train leaves at five.","Sure. Let's carry it together."],a:3,e:"「この重い箱を運べない。手伝って」「もちろん。一緒に運ぼう」。依頼への返事は Sure。"},
{id:'g4-cafe-117',d:3,q:"A: Do I have to buy a ticket for my three-year-old brother?\nB: ___. Children under five can enter for free.",c:["No, you don't","Yes, you do","Yes, he does","No, he can't"],a:0,e:"「3歳の弟の入場券を買う必要がありますか」「いいえ。5歳未満は無料です」。Do I have to に No, you don't で必要がないと答える。"},
{id:'g4-cafe-118',d:3,q:"A: How many students joined the music club this month?\nB: ___",c:["Three times.","Five students did.","For six months.","On the fourth floor."],a:1,e:"「今月何人が音楽部に入ったの」「5人です」。How many students は人数を聞く。"},
{id:'g4-cafe-119',d:1,q:"A: What did you do yesterday?\nB: ___",c:["I played tennis.","Yesterday.","With my family.","It was fun."],a:0,e:"「昨日は何をしましたか」「テニスをしました」。過去の行動を答える。"},
{id:'g4-cafe-120',d:1,q:"A: Where is the bank?\nB: ___",c:["It's over there.","It's big.","I like banks.","For money."],a:0,e:"「銀行はどこですか」「あそこです」。Where には場所で答える。"},
{id:'g4-cafe-121',d:1,q:"A: Do you have any brothers or sisters?\nB: ___",c:["Yes, one brother.","Yes, I like sports.","No, I'm fine.","No, I can't swim."],a:0,e:"「兄弟姉妹はいますか」「はい、兄が一人」。人数や有無を答える。"},
{id:'g4-cafe-122',d:1,q:"A: What time do you usually get up?\nB: ___",c:["At six thirty.","For an hour.","In my room.","With my father."],a:0,e:"「ふだん何時に起きますか」「6時半です」。時刻は At six thirty。"},
{id:'g4-cafe-123',d:1,q:"A: Do you like music?\nB: ___",c:["Yes, pop music.","Yes, I sing often.","No, it's noisy.","No, I like movies."],a:0,e:"「音楽は好きですか」「うん、ポップス」。好きな種類を答える。"},
{id:'g4-cafe-124',d:1,q:"A: What's your favorite subject?\nB: ___",c:["I like math best.","It's on Monday.","My teacher is kind.","At school."],a:0,e:"「好きな教科は何」「算数がいちばん好き」。favorite subject は好きな教科。"},
{id:'g4-cafe-125',d:2,q:"A: How did you come here today?\nB: ___",c:["By bicycle.","For two hours.","With my lunch.","At eight."],a:0,e:"「今日はどうやって来ましたか」「自転車で」。手段は By bicycle。"},
{id:'g4-cafe-126',d:2,q:"A: Would you like some tea?\nB: ___",c:["Yes, please.","Yes, I like coffee.","No, I'm Ken.","No, it's hot today."],a:0,e:"「お茶はいかがですか」「はい、お願いします」。すすめには Yes, please。"},
{id:'g4-cafe-127',d:2,q:"A: What do you want to be in the future?\nB: ___",c:["I want to be a nurse.","I want to go there.","I want to eat sushi.","I want to buy a car."],a:0,e:"「将来何になりたいですか」「看護師になりたいです」。in the future は将来。"},
{id:'g4-cafe-128',d:2,q:"A: May I open the window?\nB: ___",c:["Sure, go ahead.","Yes, it's hot.","No, it's cold.","Yes, I like it."],a:0,e:"「窓を開けてもいいですか」「どうぞ」。許可は Sure, go ahead。"},
{id:'g4-cafe-129',d:2,q:"A: How was your weekend?\nB: ___",c:["It was wonderful.","It was Saturday.","It was last week.","It was at home."],a:0,e:"「週末はどうでしたか」「すばらしかったよ」。How was は様子を聞く。"},
{id:'g4-cafe-130',d:2,q:"A: Shall I open the window?\nB: ___",c:["Yes, please.","Yes, it's clean.","No, it's new.","No, I like apples."],a:0,e:"「窓を開けましょうか」「はい、お願い」。申し出には Yes, please。"},
{id:'g4-cafe-131',d:3,q:"A: I'm sorry I'm late.\nB: ___",c:["That's all right.","You're welcome.","Don't say so.","Me, too."],a:0,e:"「遅れてごめんなさい」「大丈夫ですよ」。謝りには That's all right。"},
{id:'g4-cafe-132',d:3,q:"A: Could you tell me the way to the museum?\nB: ___",c:["It's next to the library.","It's very old.","It opens at nine.","It's my favorite place."],a:0,e:"「博物館への道を教えて」「図書館の隣です」。場所の説明で答える。"},
{id:'g4-cafe-133',d:3,q:"A: How much is this cap?\nB: ___",c:["It's 800 yen.","It's on sale.","It's popular.","It's red."],a:0,e:"「この帽子はいくらですか」「800円です」。値段は It's 800 yen。"},
{id:'g4-cafe-134',d:3,q:"A: May I sit here?\nB: ___",c:["Sure, go ahead.","Yes, I'm tired.","No, it's hard.","Yes, I like it."],a:0,e:"「ここに座ってもいいですか」「どうぞ」。許可は Sure, go ahead。"},
{id:'g4-cafe-135',d:3,q:"A: What seems to be the problem?\nB: ___",c:["I have a headache.","I am a student.","I come here often.","I like this hospital."],a:0,e:"「どうされましたか」「頭が痛いです」。病院での症状の答え。headache は頭痛。"},
{id:'g4-cafe-136',d:3,q:"A: Have you ever been to Kyoto?\nB: ___",c:["Yes, twice.","No, I went there.","Yes, I like it.","No, I live there."],a:0,e:"「京都へ行ったことがありますか」「はい、2回」。経験の回数は twice。"}
],
station:[],
park:[],
flower:[]
},
});
Object.assign(PRACTICE_ORDER_DATA, {
'4':[
["あなたは昨日何色を選びましたか。",["choose","you","What","did","color"],[3,5,4,2,1],""," yesterday?","What color did you choose yesterday? の順。What color は何色。did の後は原形 choose。"],
["私は昨日新しい靴を買いました。",["new","bought","shoes","some","I"],[5,2,4,1,3],""," yesterday.","I bought some new shoes yesterday. の順。some new shoes は「新しい靴」。yesterday は固定の文末。"],
["ケンは昨夜何を料理しましたか。",["Ken","cook","What","did","for dinner"],[3,4,1,2,5],""," last night?","What did Ken cook for dinner last night? の順。夕食に何を料理したかを聞く。did の後は原形 cook。"],
["私たちは明日おばを訪ねる予定です。",["visit","to","our aunt","are","going"],[4,5,2,1,3],"We "," tomorrow.","We are going to visit our aunt tomorrow. の順。are going to + 原形で予定。"],
["このかばんはあのかばんより小さいです。",["than","is","one","smaller","that"],[2,4,1,5,3],"This bag ",".","This bag is smaller than that one. の順。比較級 smaller + than。that one はあのかばん。"],
["あなたは今朝何時に起きましたか。",["you","get","What time","up","did"],[3,5,1,2,4],""," this morning?","What time did you get up this morning? の順。get up で起きる。"],
["昨夜彼女は何語を話していましたか。",["speaking","language","she","What","was"],[4,2,5,3,1],""," last night?","What language was she speaking last night? の順。What language は何語。was she speaking は過去進行形の疑問文。"],
["私は動物の写真を撮ることを楽しみます。",["of","pictures","enjoy","animals","taking"],[3,5,2,1,4],"I ",".","I enjoy taking pictures of animals. の順。enjoy + 動名詞。動物の写真を撮ることを楽しみます。"],
["彼女は音楽の先生になりたいと思っています。",["a","to","wants","music teacher","be"],[3,2,5,1,4],"She ",".","She wants to be a music teacher. の順。wants to be は〜になりたい。"],
["ここで写真を撮ってはいけません。",["take","You","must","pictures","not"],[2,3,5,1,4],""," here.","You must not take pictures here. の順。must not は禁止。take pictures は写真を撮る。here は固定の文末。"],
["明日この町に新しい店ができます。",["a","be","new","will","shop"],[4,2,1,3,5],"There "," in this town tomorrow.","There will be a new shop in this town tomorrow. の順。There will be は未来に存在することを表す。a new shop は新しい店。"],
["あなたは先月そこにどのくらい滞在しましたか。",["stay","How long","there","you","did"],[2,5,4,1,3],""," last month?","How long did you stay there last month? の順。How long で期間を聞く。"],
["この本はあの本より面白いです。",["interesting","that one","is","than","more"],[3,5,1,4,2],"This book ",".","This book is more interesting than that one. の順。more interesting はより面白い。"],
["私は何か冷たい飲み物が欲しいです。",["cold","drink","want","to","something"],[3,5,1,4,2],"I ",".","I want something cold to drink. の順。something + 形容詞 + to drink で飲むための冷たいもの。"],
["あなたはなぜ早く寝たのですか。",["you","Why","to bed","go","did"],[2,5,1,4,3],""," early?","Why did you go to bed early? の順。go to bed は寝る。Why は理由を聞く。"],
["彼らは昨夜8時に夕食を食べていました。",["dinner","They","having","their","were"],[2,5,3,4,1],""," at eight last night.","They were having their dinner at eight last night. の順。were having は食べていた。時刻は固定の文末。"],
["あなたは泳ぎ方を知っていますか。",["know","Do","to swim","you","how"],[2,4,1,5,3],"","?","Do you know how to swim? の順。how to swim は泳ぎ方。to swim は固定のひとまとまり。"],
["私の弟は私と同じくらい速く泳げます。",["as I can","swim","as","can","fast"],[4,2,3,5,1],"My brother ",".","My brother can swim as fast as I can. の順。as fast as は〜と同じくらい速く。"],
["私は毎朝6時半に起きます。",["every morning","half past six","get up","I","at"],[4,3,5,2,1],"",".","I get up at half past six every morning. の順。起きる=get up。時刻の前に at。"],
["彼女は昨日図書館で本を借りました。",["at the library","a book","She","borrowed"],[3,4,2,1],""," yesterday.","She borrowed a book at the library yesterday. の順。borrow は借りる。yesterday は固定の文末。"],
["あなたは放課後何を食べますか。",["after school","you","eat","What","do"],[4,5,2,3,1],"","?","What do you eat after school? の順。What + do + 主語 + 動詞。after school は放課後。"],
["この赤い自転車は私の姉のです。",["my sister's","This","red bike","is"],[2,3,4,1],"",".","This red bike is my sister's. の順。my sister's で姉のもの。"],
["彼らは先週の日曜に動物園へ行きました。",["to the zoo","They","went","last Sunday"],[2,3,1,4],"",".","They went to the zoo last Sunday. の順。went は go の過去形。"],
["私は英語の勉強が好きです。",["studying","I","English","like"],[2,4,1,3],"",".","I like studying English. の順。like のあとは動名詞 studying。"],
["あなたはこの機械を使えますか。",["you","this machine","Can","use"],[3,1,4,2],"","?","Can you use this machine? の順。Can + 主語 + 動詞の原形。"],
["母は今台所で夕食を作っています。",["now","in the kitchen","cooking dinner","My mother","is"],[4,5,3,2,1],"",".","My mother is cooking dinner in the kitchen now. の順。今していることは現在進行形。"],
["その映画は3時間も続きました。",["three hours","for","The movie","lasted"],[3,4,2,1],"",".","The movie lasted for three hours. の順。lasted for + 期間で〜続いた。"],
["彼女は私より上手にピアノを弾きます。",["than me","the piano","She","better","plays"],[3,5,2,4,1],"",".","She plays the piano better than me. の順。better than me で私より上手に。"],
["私たちは来週の日曜に試合があります。",["next Sunday","a game","We","have"],[3,4,2,1],"",".","We have a game next Sunday. の順。have a game で試合がある。"],
["あなたはどのくらい背が高いですか。",["tall","you","How","are"],[3,1,4,2],"","?","How tall are you? の順。How + 形容詞でどのくらい〜。"],
["彼は病気だったので学校を休みました。",["because","he was sick","He","stayed home"],[3,4,1,2],"",".","He stayed home because he was sick. の順。because のあとに理由の文。stay home は家にいる。"],
["このかばんはいくらでしたか。",["did","this bag","How much","cost"],[3,1,2,4],"","?","How much did this bag cost? の順。値段を聞く How much。did の後は原形 cost。"],
["私は昨日友達と公園で遊びました。",["yesterday","in the park","I","with my friends","played"],[3,5,4,2,1],"",".","I played with my friends in the park yesterday. の順。with my friends は友達と。"],
["彼女は毎晩8時に寝ます。",["every night","to bed","She","at eight","goes"],[3,5,2,4,1],"",".","She goes to bed at eight every night. の順。寝る=go to bed。時刻の前に at。"],
["あなたは週末にテニスをしますか。",["on weekends","you","tennis","Do","play"],[4,2,5,3,1],"","?","Do you play tennis on weekends? の順。Do + 主語 + 動詞の原形。on weekends は週末に。"],
["この町は冬にとても寒くなります。",["very cold","in winter","This town","gets"],[3,4,1,2],"",".","This town gets very cold in winter. の順。get + 形容詞で〜になる。"]
]
});
Object.assign(PRACTICE_LISTENING_DATA, {
'4':[
['response',1,[{speaker:'A',text:"Where did you buy your new shoes?"}],"",["Last Saturday.","At the sports shop.","They were twenty dollars."],1,"「新しい靴はどこで買ったの」「スポーツ用品店で」。Where did you buy は買った場所を聞く。",'shop'],
['response',1,[{speaker:'A',text:"What are you going to study tonight?"}],"",["At seven o'clock.","In my room.","Math and English."],2,"「今夜は何を勉強する予定？」「数学と英語」。What は教科を聞いている。be going to は予定。",'school'],
['response',2,[{speaker:'A',text:"How long can I keep this library book?"}],"",["For two weeks.","Two books.","Twice a week."],0,"「この図書館の本はどのくらい借りていてよいですか」「2週間です」。How long は期間、How many は数、How often は頻度。",'library'],
['response',2,[{speaker:'A',text:"What should I bring to the picnic tomorrow?"}],"",["By bus.","Some sandwiches.","At the park."],1,"「明日のピクニックには何を持っていけばいい？」「サンドイッチを少し」。What should I bring は持ち物を聞く。",'picnic'],
['response',3,[{speaker:'A',text:"Why did you leave soccer practice early yesterday?"}],"",["For two hours.","With my brother.","Because I felt sick."],2,"「なぜ昨日サッカーの練習を早く切り上げたの」「具合が悪かったから」。Why に Because で理由を答える。felt は feel の過去形。",'sports'],
['response',3,[{speaker:'A',text:"Hello, this is Kim. Can we meet at four instead of three tomorrow?"}],"",["Sure. Four is fine with me.","It takes three minutes.","There are four people."],0,"「キムです。明日3時の代わりに4時に会える？」「もちろん。4時で大丈夫」。instead of は〜の代わりに。",'phone'],
['dialogue',1,[{speaker:'A',text:"How did you get to the museum yesterday, Sora?"},{speaker:'B',text:"I went by train with my father."},{speaker:'A',text:"Was it crowded?"},{speaker:'B',text:"No. We both had seats."}],"How did Sora go to the museum?",["By train.","By car.","By bus.","On foot."],0,"「昨日博物館へどう行った？」「父と電車で行った」「混んでいた？」「いいえ、二人とも座れた」。交通手段は by train。"],
['dialogue',1,[{speaker:'A',text:"Did you enjoy the school concert, Mia?"},{speaker:'B',text:"Yes. My brother played the guitar."},{speaker:'A',text:"Did you play the piano?"},{speaker:'B',text:"No, I sang with my friends."}],"What did Mia do at the concert?",["She played the guitar.","She sang with her friends.","She played the piano.","She danced with her brother."],1,"「演奏会は楽しかった？」「うん。兄がギターを弾いた」「あなたはピアノ？」「いいえ、友達と歌った」。ミアがしたことは歌うこと。"],
['dialogue',2,[{speaker:'A',text:"Let's go swimming after lunch, Ken."},{speaker:'B',text:"Sorry, I have to help my mother clean the kitchen."},{speaker:'A',text:"How about tomorrow?"},{speaker:'B',text:"That's fine."}],"What will Ken do after lunch today?",["Go swimming.","Visit a friend.","Clean the kitchen.","Buy lunch."],2,"「昼食後に泳ぎに行こう」「ごめん、母の台所掃除を手伝わないと」「明日は？」「いいよ」。今日の昼食後は台所を掃除する。"],
['dialogue',2,[{speaker:'A',text:"Which bag will you buy, Amy?"},{speaker:'B',text:"The red one is nice, but it's thirty dollars. The blue one is twenty."},{speaker:'A',text:"Do you like the blue one?"},{speaker:'B',text:"Yes. I'll buy it."}],"How much will Amy pay for her bag?",["Ten dollars.","Thirty dollars.","Forty dollars.","Twenty dollars."],3,"「どのかばんを買う？」「赤は30ドル、青は20ドル」「青は好き？」「うん、それを買う」。買うのは青なので20ドル。"],
['dialogue',3,[{speaker:'A',text:"Were you watching TV when I called at seven last night, Leo?"},{speaker:'B',text:"No. I was taking a bath. My sister was watching TV."},{speaker:'A',text:"Did you call me back later?"},{speaker:'B',text:"Yes, at eight."}],"What was Leo doing at seven last night?",["Taking a bath.","Watching TV.","Calling his sister.","Eating dinner."],0,"「昨夜7時に電話したときテレビを見ていた？」「いいえ、入浴中だった。姉がテレビを見ていた」「後でかけ直した？」「うん、8時に」。7時のレオは入浴中。"],
['dialogue',3,[{speaker:'A',text:"Nina, shall we meet at the library before the movie?"},{speaker:'B',text:"It's farther from the movie theater than the station. Let's meet at the station."},{speaker:'A',text:"OK. At one thirty?"},{speaker:'B',text:"Yes. The movie starts at two."}],"Where will Nina and her friend meet?",["At the library.","At the station.","At the movie theater.","At Nina's house."],1,"「映画の前に図書館で会おうか」「図書館は駅より映画館から遠いから駅にしよう」「1時半？」「うん、映画は2時から」。待ち合わせ場所は駅に決まった。"],
['passage',1,[{speaker:'narrator',text:"My name is Mei. Last Saturday, I visited my grandfather. We worked in his garden in the morning. After lunch, he taught me how to make a small box. I used wood from his old desk."}],"What did Mei make with her grandfather?",["A desk.","A chair.","A box.","A garden gate."],2,"「メイです。先週土曜に祖父を訪ね、午前は庭仕事をしました。昼食後、祖父に小さな箱の作り方を教わりました。古い机の木を使いました」。作ったのは箱で、机は材料。"],
['passage',1,[{speaker:'narrator',text:"This is a message for the tennis club. Our practice will start at four today, not three thirty. Please meet on the tennis court. Bring your racket and a bottle of water. We will finish at five."}],"What time will tennis practice start today?",["At three.","At three thirty.","At five.","At four."],3,"「テニス部への連絡です。今日は3時半でなく4時に練習開始。コートに集まり、ラケットと水を持参してください。終了は5時です」。開始時刻は4時。"],
['passage',2,[{speaker:'narrator',text:"Last winter, Tom wanted to learn to cook. His mother was busy on weekdays, so they cooked together every Sunday. At first, Tom could only make eggs. Now he can make soup and pasta, too. Pasta is his favorite food to cook."}],"When did Tom and his mother cook together?",["Every Sunday.","Every weekday.","Every Saturday.","Every Friday evening."],0,"「去年の冬、トムは料理を習いたかった。母は平日忙しかったので毎週日曜に一緒に料理した。初めは卵料理だけだったが今はスープとパスタも作れ、パスタが一番好き」。一緒に作ったのは毎週日曜。"],
['passage',2,[{speaker:'narrator',text:"Yui usually walks to school with her friend. Yesterday morning, it was raining hard. Her father offered to drive her, but his car had a problem. Yui took the bus instead. She arrived at school before her first class."}],"How did Yui go to school yesterday?",["On foot.","By bus.","By car.","By bike."],1,"「普段ユイは友達と歩いて登校します。昨日は大雨で、父が車で送ろうとしましたが車に問題があり、代わりにバスに乗りました。最初の授業前に着きました」。昨日の交通手段はバス。"],
['passage',3,[{speaker:'narrator',text:"Welcome to our art club. Today, we are going to draw trees outside. First, choose some pencils from the box by the door. Then go to the school garden with your paper. Do not bring paint today. We will use paint in our next lesson."}],"What should the students do first?",["Go to the garden.","Draw a tree.","Choose some pencils.","Bring some paint."],2,"「美術部へようこそ。今日は外で木を描きます。まずドアのそばの箱から鉛筆を選び、その後紙を持って学校の庭へ。絵の具は次回使います」。最初は鉛筆を選ぶこと。"],
['passage',3,[{speaker:'narrator',text:"Last month, Emma joined a running club. She wanted to run faster, but she did not enjoy practicing alone. Now she runs with five other students twice a week. They encourage each other. Emma likes running much more now and wants to enter a race in October."}],"Why did Emma join the running club?",["To teach young children.","To spend less time running.","To practice alone every day.","To learn to run faster with other people."],3,"「先月エマは走るクラブに入りました。もっと速くなりたかったが一人での練習は楽しくありませんでした。今は他の生徒5人と週2回走り、互いに励まし合っています。10月の大会に出たいと思っています」。他の人と練習して速く走れるようになるために入部。"],
['response',1,[{speaker:'A',text:"What color is your new bag?"}],"",["It's red.","It's new.","I like it."],0,"「新しいかばんは何色」「赤です」。色を聞く What color。"],
['response',1,[{speaker:'A',text:"Who is that boy over there?"}],"",["He's my cousin.","He's tall.","He's fine."],0,"「あの男の子は誰」「いとこです」。人を聞く Who is。"],
['response',2,[{speaker:'A',text:"How long does it take to get to school?"}],"",["About ten minutes.","About two kilometers.","Every morning."],0,"「学校までどのくらいかかる」「約10分」。How long does it take は所要時間を聞く。"],
['response',2,[{speaker:'A',text:"What do you usually do on Sundays?"}],"",["I play tennis.","On Sunday.","With my friends."],0,"「日曜はふだん何をする」「テニスをするよ」。usually はふだん。"],
['response',3,[{speaker:'A',text:"Why were you late this morning?"}],"",["I missed the bus.","At eight.","By bike."],0,"「今朝なぜ遅れたの」「バスに乗り遅れたんだ」。miss the bus は乗り遅れる。"],
['response',3,[{speaker:'A',text:"Would you like to join our baseball team?"}],"",["Yes, I'd love to.","Yes, I like baseball games.","No, I'm a student."],0,"「野球部に入りませんか」「ぜひ」。I'd love to はぜひとも。"],
['dialogue',1,[{speaker:'A',text:"What's that, Yuki?"},{speaker:'B',text:"It's a present for my mother."},{speaker:'A',text:"What's in it?"},{speaker:'B',text:"A blue scarf."}],"What is the present?",["A blue scarf.","A red hat.","A white shirt.","A black bag."],0,"「ユキ、それは何」「母へのプレゼント」「中身は」「青いマフラー」。scarf はマフラー。"],
['dialogue',1,[{speaker:'A',text:"Where are you going, Ken?"},{speaker:'B',text:"To the post office."},{speaker:'A',text:"Why?"},{speaker:'B',text:"I want to buy stamps."}],"Why is Ken going to the post office?",["To buy stamps.","To meet his friend.","To send a bag.","To make a call."],0,"「ケン、どこへ行くの」「郵便局」「なぜ」「切手を買いたいんだ」。stamp は切手。"],
['dialogue',2,[{speaker:'A',text:"Did you watch the soccer game yesterday, Saki?"},{speaker:'B',text:"Yes. Our team won."},{speaker:'A',text:"What was the score?"},{speaker:'B',text:"Two to one."}],"What was the score of the game?",["Two to one.","One to zero.","Three to two.","Two to two."],0,"「昨日のサッカーを見た、サキ」「うん。うちのチームが勝った」「スコアは」「2対1」。Two to one は2対1。"],
['dialogue',2,[{speaker:'A',text:"How often do you go to the library, Ren?"},{speaker:'B',text:"Twice a month."},{speaker:'A',text:"What do you read there?"},{speaker:'B',text:"Books about animals."}],"What does Ren read at the library?",["Books about animals.","Books about sports.","Books about stars.","Books about cars."],0,"「どのくらい図書館へ行くの、レン」「月2回」「何を読むの」「動物の本」。about animals は動物についての。"],
['dialogue',3,[{speaker:'A',text:"Have you decided what to do this summer, Aya?"},{speaker:'B',text:"Yes. I'll visit my grandparents in Okinawa."},{speaker:'A',text:"How long will you stay there?"},{speaker:'B',text:"For a week."}],"How long will Aya stay in Okinawa?",["For a week.","For a month.","For a year.","For a day."],0,"「夏の予定は決めた、アヤ」「うん。沖縄の祖父母を訪ねる」「どのくらい滞在するの」「1週間」。For a week は1週間。"],
['dialogue',3,[{speaker:'A',text:"Why do you study English so hard, Sho?"},{speaker:'B',text:"I want to talk with people from many countries."},{speaker:'A',text:"That's great."}],"Why does Sho study English hard?",["To talk with people from many countries.","To pass a test.","To read difficult books.","To write long letters."],0,"「なぜそんなに熱心に英語を勉強するの、ショウ」「多くの国の人と話したいんだ」。"],
['passage',1,[{speaker:'narrator',text:"Hello. I'm Riku. I get up at six every morning. I eat breakfast with my family. Then I walk to school with my friend. School starts at eight thirty."}],"What time does Riku's school start?",["At eight thirty.","At eight.","At seven thirty.","At nine."],0,"「こんにちは。リクです。毎朝6時に起き、家族と朝食を食べ、友達と歩いて登校します。授業は8時半に始まります」。School starts at eight thirty とある。"],
['passage',1,[{speaker:'narrator',text:"My sister has a small dog. Its name is Pochi. Every evening, she takes Pochi to the park. They run together there for thirty minutes."}],"What does Riku's sister do every evening?",["She runs with Pochi in the park.","She swims with Pochi.","She reads with Pochi.","She cooks with Pochi."],0,"「姉は小さな犬を飼っています。名前はポチ。毎晩ポチを公園へ連れて行き、30分一緒に走ります」。run together there とある。"],
['passage',2,[{speaker:'narrator',text:"Last Sunday, Emi went to the zoo with her class. They saw many animals. Emi liked the pandas best. She took a lot of pictures. She got home at five."}],"What did Emi like best at the zoo?",["The pandas.","The lions.","The monkeys.","The bears."],0,"「先週の日曜、エミはクラスで動物園へ行き、たくさんの動物を見ました。パンダがいちばん好きで、写真をたくさん撮り、5時に帰宅しました」。liked the pandas best とある。"],
['passage',2,[{speaker:'narrator',text:"Toru wanted a new bicycle, so he saved money for six months. Last Saturday, he bought a blue bicycle. It cost twenty thousand yen. Now he rides it to school every day."}],"How did Toru get his new bicycle?",["He saved money and bought it.","His father gave it to him.","He borrowed it from his friend.","He found it in the park."],0,"「トオルは新しい自転車がほしくて6か月お金をため、先週の土曜に青い自転車を買いました。2万円で、今は毎日それで通学します」。saved money for six months とある。"],
['passage',3,[{speaker:'narrator',text:"Anna joined the cooking club last spring. At first, she could only wash vegetables. Now she can make curry and salads. Next month, she will cook lunch for her family."}],"What will Anna do next month?",["She will cook lunch for her family.","She will join a new club.","She will visit a restaurant.","She will buy new tools."],0,"「アンナは去年の春に料理部へ入りました。最初は野菜を洗うだけでしたが、今はカレーとサラダが作れます。来月は家族のために昼食を作ります」。will cook lunch for her family とある。"],
['passage',3,[{speaker:'narrator',text:"Ken's town has a famous festival every fall. Last year, more than ten thousand people came. Ken helped at a food shop with his father. They sold noodles and juice. Ken wants to help again this year."}],"What did Ken do at the festival last year?",["He helped at a food shop.","He sang on a stage.","He played soccer.","He drew pictures."],0,"「ケンの町では毎年秋に有名な祭りがあり、去年は1万人以上が来ました。ケンは父と食べ物の店を手伝い、麺とジュースを売りました。今年も手伝いたいと思っています」。helped at a food shop とある。"]
]
});
PRACTICE_READING_DATA.push(
['4','notice',1,[
["Where should students meet Mr. Hill?",["In their classroom.","At the garden gate.","At the library door.","In the school hall."],1,"集合場所は庭の門。Meet Mr. Hill at the garden gate. は「庭の門でヒル先生と会ってください」。"],
["What should students bring?",["Flowers and tools.","Lunch and a book.","A hat and some water.","Paper and pencils."],2,"持ち物は帽子と水。Bring a hat and some water. とあり、道具は不要。土曜9時から11時に花を植える活動。"]
]],
['4','notice',2,[
["What can children draw in the class?",["Their school.","Their family.","Their favorite food.","Their favorite animal."],3,"好きな動物を描ける。You can draw your favorite animal. は「好きな動物を描けます」。"],
["How can children join the class?",["Call the library by Friday.","Visit the post office on Sunday.","Send an email to their teacher.","Buy paper at the library."],0,"金曜までに図書館へ電話する。Call the library by Friday to join. の by Friday は金曜までに。授業は日曜午後2時で、紙は無料。"]
]],
['4','email',1,[
["What time can Meg come to Rina's house?",["At ten.","At twelve.","At one.","At two."],1,"メグは12時に来られる。I can come to your house at twelve. は「あなたの家に12時に行けます」。土曜の昼食への招待の返事。"],
["How will Meg get to Rina's house?",["She will walk alone.","She will take a bus.","Her father will drive her.","Her brother will ride with her on a train."],2,"父が車で送る。my father will drive me to your house after the game は「試合の後、父があなたの家まで車で送ってくれる」。"],
["What does Meg want to do with Rina?",["Play soccer.","Buy apple juice.","Visit her brother.","Make sandwiches."],3,"一緒にサンドイッチを作りたい。Can we make sandwiches together? と聞き、特別なレシピを習いたいと続けている。りんごジュースは持参する。"]
]],
['4','email',2,[
["Why didn't Dan buy tennis shoes?",["They cost too much.","They were too small.","The shop had no tennis shoes.","He needed shoes for swimming."],0,"値段が高すぎたから。the tennis shoes were too expensive は「テニス用の靴は高すぎました」。代わりに青い帽子を買った。"],
["What does Leo need?",["A cap for tennis.","A bag for swimming.","A new tennis racket.","Some shoes for school."],1,"レオには水泳用のかばんが必要。You need a bag for swimming, right? は「水泳用のかばんが必要なんだよね」。"],
["When does Dan want to visit the shop with Leo?",["On Wednesday morning.","On Sunday afternoon.","After school on Wednesday.","After school on Friday."],2,"水曜の放課後に行きたい。Let's go there after school on Wednesday. は「水曜の放課後そこへ行こう」。店は郵便局の隣。"]
]],
['4','story',1,[
["Why did Mrs. Green ask Aya to feed her rabbit?",["Aya wanted to buy a rabbit.","Mrs. Green was sick in bed.","The rabbit needed a new home.","Mrs. Green was going to another town."],3,"グリーンさんは別の町へ3日間行くため、アヤにうさぎの餌やりを頼んだ。went to another town for three days が理由。"],
["When did Aya go to Mrs. Green's house?",["Before school every morning.","After school every afternoon.","At lunchtime every day.","After dinner every night."],0,"毎朝学校へ行く前。Every morning, Aya walked to Mrs. Green's house before school. は「毎朝、登校前にグリーンさんの家まで歩いた」。"],
["Where did Aya find the rabbit on the second day?",["In its box.","Under a chair.","In the garden.","Under a bed."],1,"2日目にうさぎを見つけたのは椅子の下。found it under a chair。最初に探した箱の中にはいなかった。"],
["What did Mrs. Green give Aya?",["A new pet.","A small chair.","A book about rabbits.","A box of food."],2,"お礼にうさぎについての本をあげた。gave her a book about rabbits は「彼女にうさぎの本をあげた」。"],
["What does Aya want to do now?",["Go to another town.","Buy a bigger house.","Write a book for Mrs. Green.","Learn more about small animals."],3,"今は小動物についてもっと知りたい。Now she wants to learn more about small animals. が結末。アヤは世話の仕事を楽しんだ。"]
]],
['4','story',2,[
["Why did Ben and Lisa stay home on Sunday morning?",["It was raining.","Their bikes were broken.","They were sick.","Their parents were at the lake."],0,"起きたとき雨が降っていたから。When they woke up, it was raining. 自転車で湖へ行く予定を変え、家で昼食を作ることにした。"],
["Where did Ben find the soup recipe?",["In an email.","In a cookbook.","On a TV show.","In a letter from Lisa."],1,"料理本の中で見つけた。Ben found a recipe for vegetable soup in a cookbook. は「ベンは料理本で野菜スープのレシピを見つけた」。"],
["What did Lisa do before Ben cut the vegetables?",["She bought a pot.","She made some bread.","She washed the vegetables.","She went to the lake."],2,"リサはにんじんとじゃがいもを洗った。Lisa washed the carrots and potatoes, and Ben cut them. の順で分担している。"],
["Who helped Ben and Lisa make bread?",["Their mother.","Their teacher.","Their neighbor.","Their father."],3,"父がパン作りを手伝った。Their father came into the kitchen and helped them make bread. は「父が台所に来てパン作りを手伝った」。"],
 ["What did Ben and Lisa do in the afternoon?",["They took a short walk.","They rode their bikes to the lake.","They bought a cookbook.","They washed their bikes."],0,"午後は雨がやみ、自転車に乗る代わりに少し散歩した。took a short walk instead of riding their bikes の instead of は〜の代わりに。"]
]],
['4','notice',3,[
["When is the book fair?",["On Friday and Saturday.","On Sunday and Monday.","On Monday and Tuesday.","On Saturday and Sunday."],0,"金曜と土曜。on Friday and Saturday とある。学校の図書館で開催。"],
["How much is an old book?",["Fifty yen.","Three hundred yen.","Five hundred yen.","One thousand yen."],0,"古本は50円。old books for fifty yen とある。新刊は300円。"]
]],
['4','email',3,[
["When is Nana's birthday party?",["Next Sunday.","This Sunday.","Next Saturday.","Last Sunday."],0,"来週の日曜。next Sunday とある。ナナの家で開かれる。"],
["What time does the party start?",["At two in the afternoon.","At three in the evening.","At one in the morning.","At four in the afternoon."],0,"2時開始。starts at two in the afternoon とある。"],
["What does Nana want to do with Sara?",["Play games.","Watch a movie.","Go shopping.","Cook dinner."],0,"一緒にゲームをしたい。want to play games with you とある。金曜までに返事がほしい。"]
]],
['4','email',4,[
["Where did Hiro stay?",["In a tent near a lake.","In a hotel in town.","In his uncle's house.","In a car."],0,"湖の近くのテント。stayed in a tent near a lake for two nights とある。"],
["How long did Hiro stay there?",["For two nights.","For three nights.","For a week.","For a day."],0,"2泊。for two nights とある。先週末の家族キャンプ。"],
["What did Hiro's father cook?",["Fish.","Meat.","Rice.","Soup."],0,"魚を料理。cooked fish outside とある。姉と湖で泳いだ。"]
]],
['4','story',3,[
["When did Mika lose her pencil box?",["Yesterday morning.","Yesterday evening.","This morning.","Last night."],0,"昨日の朝なくした。lost her red pencil box yesterday morning とある。"],
["Where did Yui find the box?",["Behind a bookshelf.","Under a desk.","In Mika's bag.","On the teacher's desk."],0,"本棚の後ろ。found the box behind a bookshelf とある。机の下を探したがなかった。"],
["What did Mika buy on the way home?",["Two donuts.","Two pens.","Two books.","Two cards."],0,"帰り道にドーナツを2つ買った。bought two donuts とある。鉛筆は全部そろっていた。"],
["Why did Mika give a donut to Yui?",["To thank her.","To say goodbye.","To ask for help.","To celebrate her birthday."],0,"お礼のため。said thank you to Yui many times とあり、1つ渡した。"],
["What did Mika do with the two donuts?",["She gave one to Yui.","She ate both herself.","She gave both to Yui.","She put them in her pencil box."],0,"1つをユイに渡した。gave one to Yui とある。残りは自分で食べる分。"]
]],
['4','story',4,[
["Who taught Ryo to make paper planes?",["His grandmother.","His mother.","His teacher.","His friend."],0,"祖母が教えた。grandmother taught him とある。雪の午後に10機作った。"],
["Where did Ryo's best plane land?",["On a tall tree.","In the river.","On the roof.","Under a car."],0,"高い木の上。landed on a tall tree とある。庭をこえて飛んだ。"],
["How did Ryo get his plane back?",["He climbed a ladder.","He shook the tree.","He waited for wind.","He asked his sister."],0,"はしごを登って取った。brought a long ladder / climbed up とある。少し怖かったがうれしかった。"],
["What does Ryo do now?",["He teaches his sister.","He makes cakes.","He plays baseball.","He draws pictures."],0,"今は妹に教える。teaches his little sister とある。上手に作れるようになった。"],
["When did Ryo learn to make paper planes?",["Last winter.","Last summer.","Last spring.","Last fall."],0,"去年の冬。Last winter とある。雪の午後に祖母と10機作った。"]
]],
);
